const cnxhChapter2 = [
	{
		question: "Nội dung nào dưới đây là phạm trù trung tâm, là nguyên lí xuất phát của chủ nghĩa xã hội khoa học?",
		answers: [
			"Sứ mệnh lịch sử thế giới của giai cấp công nhân",
			"Chủ nghĩa xã hội và thời kì quá độ lên chủ nghĩa xã hội",
			"Dân chủ xã hội chủ nghĩa và nhà nước xã hội chủ nghĩa",
			"Vấn đề dân tộc trong thời kì quá độ lên chủ nghĩa xã hội",
		],
		correct: 0,
		explanation: "Dựa trên Trang 21 của chương 2 của tài liệu, chỉ ra rằng Sứ mệnh lịch sử thế giới của giai cấp công nhân là nội dung chủ yếu, điểm căn bản của chủ nghĩa Mác - Lênin, là phạm trù trung tâm, nguyên lý xuất phát của chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Giai cấp nào dưới đây là con đẻ của nền đại công nghiệp tư bản chủ nghĩa?",
		answers: [
			"Giai cấp tư sản",
			"Giai cấp địa chủ",
			"Giai cấp công nhân",
			"Giai cấp nông dân",
		],
		correct: 2,
		explanation: "Dựa trên Trang 37 của chương 3 của tài liệu (kiến thức tổng hợp về GCCN), chỉ ra rằng giai cấp công nhân, con đẻ của nền đại công nghiệp.\" và \"Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng giai cấp công nhân là sản phẩm của bản thân nền đại công nghiệp.",
	},
	{
		question: "Chọn phương án đúng nhất: Sự ra đời và phát triển của giai cấp công nhân hiện đại gắn liền với sự ra đời và phát triển của [...].",
		answers: [
			"Sản xuất thủ công",
			"Công trường thủ công",
			"Nền đại công nghiệp tư bản chủ nghĩa",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 21 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là một tập đoàn xã hội ổn định, hình thành và phát triển cùng với quá trình phát triển của nền công nghiệp hiện đại.",
	},
	{
		question: "Nội dung sứ mệnh lịch sử của giai cấp công nhân là [...].",
		answers: [
			"Xóa bỏ chế độ chiếm hữu nô lệ, xây dựng chế độ phong kiến",
			"Xóa bỏ chế độ phong kiến, xây dựng chế độ tư bản chủ nghĩa",
			"Xóa bỏ chế độ tư bản chủ nghĩa, xây dựng chủ nghĩa xã hội, chủ nghĩa cộng sản",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là giai cấp lãnh đạo nhân dân lao động đấu tranh nhằm thực hiện bước chuyển từ chủ nghĩa tư bản lên chủ nghĩa xã hội và chủ nghĩa cộng sản.",
	},
	{
		question: "Trong chủ nghĩa tư bản, giai cấp công nhân đại biểu cho phương thức sản xuất [...].",
		answers: [
			"Tiên tiến",
			"Lạc hậu",
			"Manh mún",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 21 của chương 2 của tài liệu, chỉ ra rằng Là giai cấp đại diện cho lực lượng sản xuất tiên tiến.",
	},
	{
		question: "Trong chủ nghĩa tư bản, giai cấp công nhân có mấy đặc trưng cơ bản?",
		answers: [
			"2",
			"3",
			"4",
			"5",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng đặc trưng cơ bản của giai cấp công nhân được xem xét trên 2 phương diện: Giai cấp công nhân trên phương diện kinh tế - xã hội và Giai cấp công nhân trên phương diện chính trị - xã hội.",
	},
	{
		question: "Trực tiếp hay gián tiếp vận hành các công cụ sản xuất có tính chất công nghiệp ngày càng hiện đại và xã hội hoá cao là nội dung thể hiện […].",
		answers: [
			"công cụ lao động của người công nhân",
			"phương thức lao động của người công nhân",
			"vị trí trong quan hệ sản xuất tư bản chủ nghĩa của người công nhân",
			"địa vị xã hội của người công nhân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng giai cấp công nhân với phương thức lao động công nghiệp trong nền sản xuất tư bản chủ nghĩa. Đó là những người lao động trực tiếp hay gián tiếp vận hành các công cụ sản xuất có tính chất công nghiệp ngày càng hiện đại và xã hội hóa cao.",
	},
	{
		question: "Về vị trí trong quan hệ sản xuất tư bản chủ nghĩa, công nhân là những người lao động […].",
		answers: [
			"có sở hữu tư liệu sản xuất là sức lao động",
			"có sở hữu tư liệu sản xuất là kinh nghiệm cá nhân",
			"không sở hữu tư liệu sản xuất chủ yếu của xã hội",
			"không sở hữu bất cứ tư liệu sản xuất nào của xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Đó là giai cấp của những người lao động không sở hữu tư liệu sản xuất chủ yếu của xã hội.",
	},
	{
		question: "“Các giai cấp khác đều suy tàn và tiêu vong cùng với sự phát triển của đại công nghiệp, còn giai cấp vô sản là sản phẩm của bản thân nền đại công nghiệp” là luận điểm của […].",
		answers: [
			"C. Mác và Ph.Ăngghen",
			"C. Mác",
			"Ph. Ăngghen",
			"V.I. Lênin",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng khái niệm Giai cấp công nhân là sản phẩm xã hội của quá trình phát triển tư bản chủ nghĩa (đây là luận điểm kinh điển của C.Mác và Ph.Ăngghen trong Tuyên ngôn ĐCS).",
	},
	{
		question: "Giai cấp, tầng lớp nào dưới đây không sở hữu tư liệu sản xuất chủ yếu, phải bán sức lao động cho nhà tư bản và bị nhà tư bản bóc lột giá trị thặng dư?",
		answers: [
			"Trí thức",
			"Doanh nhân",
			"Tiểu tư sản",
			"Công nhân",
		],
		correct: 3,
		explanation: "Dựa trên Trang 21-22 của chương 2 của tài liệu, chỉ ra rằng giai cấp công nhân là những người không có hoặc về cơ bản không có tư liệu sản xuất phải làm thuê cho giai cấp tư sản và bị giai cấp tư sản bóc lột giá trị thặng dư.",
	},
	{
		question: "Một số thuật ngữ khác nhau được C. Mác và Ph. Ănghen sử dụng có nghĩa tương đồng với khái niệm giai cấp công nhân là [...].",
		answers: [
			"Giai cấp vô sản",
			"Giai cấp công nhân hiện đại",
			"Giai cấp công nhân đại công nghiệp",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên nội dung khái niệm Trang 21 của chương 2 của tài liệu, các thuật ngữ: vô sản, công nhân hiện đại, công nhân được các ông sử dụng đồng nghĩa để chỉ lực lượng lao động trong nền đại công nghiệp.",
	},
	{
		question: "Giai cấp công nhân là tập đoàn người lao động sử dụng công cụ sản xuất có tính [...].",
		answers: [
			"Thủ công",
			"Công nghiệp",
			"Thô sơ",
			"Tất cả các nội dung đã nêu",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Lao động bằng phương thức công nghiệp với đặc trưng công cụ lao động là máy móc.",
	},
	{
		question: "Các thuật ngữ “giai cấp vô sản”, “giai cấp công nhân hiện đại”, “công nhân máy móc” là muốn đề cập đến giai cấp nào?",
		answers: [
			"Giai cấp công nhân hiện đại",
			"Giai cấp nông dân",
			"Giai cấp tư sản",
			"Tầng lớp trí thức",
		],
		correct: 0,
		explanation: "Dựa trên Trang 21 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là một tập đoàn xã hội ổn định, hình thành và phát triển cùng với quá trình phát triển của nền công nghiệp hiện đại; Là giai cấp đại diện cho lực lượng sản xuất tiên tiến.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chủ nghĩa tư bản, giai cấp công nhân hiện đại có nguồn gốc từ [...].",
		answers: [
			"Giai cấp nông dân",
			"Thợ thủ công",
			"Tiểu chủ",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên kiến thức lịch sử hình thành GCCN (Chương 2), công nhân hiện đại được bổ sung từ sự phá sản của những người thợ thủ công, tiểu chủ, và sự dịch chuyển cơ cấu nông dân lên thành thị.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, “không có tư liệu sản xuất, phải bán sức lao động và bị bóc lột giá trị thặng dư” là đặc trưng cơ bản của giai cấp nào?",
		answers: [
			"Giai cấp tư sản",
			"Giai cấp công nhân",
			"Giai cấp nông dân",
			"Tầng lớp trí thức",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Họ phải bán sức lao động cho nhà tư bản và bị chủ tư bản bóc lột giá trị thặng dư.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, “không có tư liệu sản xuất, phải bán sức lao động và bị bóc lột giá trị thặng dư” là đặc trưng cơ bản để phân biệt giai cấp công nhân với [...].",
		answers: [
			"Tầng lớp trí thức",
			"Giai cấp nông dân",
			"Giai cấp tư sản",
			"Tất cả các nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Mâu thuẫn về lợi ích giữa giai cấp công nhân và giai cấp tư sản. Lao động sống của công nhân là nguồn gốc giá trị thặng dư và sự giàu có của giai cấp tư sản (đây là điểm cốt lõi để phân biệt GCCN với giai cấp tư sản - những người sở hữu tư liệu sản xuất).",
	},
	{
		question: "Giai cấp, tầng lớp nào dưới đây chỉ có thể sống với điều kiện là kiếm được việc làm, và chỉ kiếm được việc làm, nếu lao động của họ làm tăng thêm tư bản?",
		answers: [
			"Nông dân",
			"Địa chủ",
			"Công nhân",
			"Tư sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Đó là giai cấp của những người lao động không sở hữu tư liệu sản xuất chủ yếu của xã hội. Họ phải bán sức lao động cho nhà tư bản.",
	},
	{
		question: "Lực lượng nào dưới đây buộc phải tự bán mình để kiếm ăn từng bữa, là một hàng hoá, tức là một món hàng đem bán như bất cứ món hàng nào khác, vì thế, họ phải chịu hết mọi sự may rủi của cạnh tranh, mọi sự lên xuống của thị trường?",
		answers: [
			"Nông dân",
			"Người làm nghề tự do",
			"Công nhân",
			"Tiểu tư sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng bản chất bán sức lao động cho các nhà tư bản để sống là thuộc về Giai cấp công nhân.",
	},
	{
		question: "Nội dung nào dưới đây là nguồn gốc cơ bản của giá trị thặng dư và sự giàu có của giai cấp tư sản?",
		answers: [
			"Lao động sống của giai cấp công nhân",
			"Quá trình trao đổi, mua bán",
			"Hoạt động thương mại",
			"Kinh tế thị trường",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Lao động sống của công nhân là nguồn gốc giá trị thặng dư và sự giàu có của giai cấp tư sản.",
	},
	{
		question: "Giai cấp công nhân lao động bằng phương thức công nghiệp với đặc trưng công cụ lao động là […].",
		answers: [
			"ruộng đất",
			"con trâu, cái cày",
			"trí óc",
			"máy móc có tính chất công nghiệp",
		],
		correct: 3,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Lao động bằng phương thức công nghiệp với đặc trưng công cụ lao động là máy móc, tạo ra năng suất lao động cao.",
	},
	{
		question: "Giai cấp nào dưới đây là sản phẩm của bản thân nền đại công nghiệp, là chủ thể của quá trình sản xuất vật chất hiện đại?",
		answers: [
			"Giai cấp chủ nô",
			"Giai cấp địa chủ",
			"Giai cấp công nhân",
			"Giai cấp tư sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng Là sản phẩm của bản thân nền đại công nghiệp, là chủ thể của quá trình sản xuất vật chất hiện đại.",
	},
	{
		question: "Lực lượng nào dưới đây là đại biểu cho lực lượng sản xuất tiên tiên, cho phương thức sản xuất tiên tiến, quyết định sự tồn tại và phát triển của xã hội hiện đại?",
		answers: [
			"Giai cấp nông dân",
			"Đội ngũ trí thức",
			"Giai cấp công nhân",
			"Giai cấp tư sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng Do đó, giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến, quyết định sự tồn tại và phát triển của xã hội hiện đại.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, mâu thuẫn giữa giai cấp công nhân và giai cấp tư sản là mâu thuẫn đối kháng […].",
		answers: [
			"Trực tiếp",
			"Gián tiếp",
			"Trực tiếp và gián tiếp",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng mâu thuẫn đó cho thấy tính chất đối kháng không thể điều hòa giữa giai cấp công nhân với giai cấp tư sản trong chế độ tư bản chủ nghĩa (đối lập trực tiếp về lợi ích kinh tế).",
	},
	{
		question: "Chọn phương án đúng nhất: Theo chủ nghĩa Mác - Lênin, trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp […].",
		answers: [
			"Không có tư liệu sản xuất",
			"Bị bóc lột giá trị thặng dư",
			"Lao động trong nền đại công nghiệp",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 21-22 của chương 2 của tài liệu, chỉ ra rằng công nhân là người làm thuê, không có tư liệu sản xuất, bị bóc lột giá trị thặng dư và lao động bằng phương thức công nghiệp.",
	},
	{
		question: "Dựa vào khái niệm giai cấp công nhân, trong chủ nghĩa tư bản hiện nay, giai cấp công nhân là giai cấp […].",
		answers: [
			"Không bị bóc lột giá trị thặng dư",
			"Bị bóc lột giá trị thặng dư",
			"Bị bóc lột một phần giá trị thặng dư",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 1,
		explanation: "Dựa trên Trang 27 của chương 2 của tài liệu, chỉ ra rằng Ở các nước tư bản chủ nghĩa hiện nay, công nhân vẫn bị giai cấp tư sản và chủ nghĩa tư bản bóc lột giá trị thặng dư.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, một trong những đặc điểm chính trị - xã hội của giai cấp công nhân là […].",
		answers: [
			"Giai cấp có tư liệu sản xuất",
			"Bộ phận quan trọng nhất của lực lượng sản xuất",
			"Giai cấp tiên phong cách mạng",
			"Tất cả các nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là giai cấp tiên tiến nhất... Giai cấp công nhân là giai cấp có tinh thần cách mạng triệt để (đặc điểm chính trị - xã hội).",
	},
	{
		question: "Ai đã khẳng định: “Lực lượng sản xuất hàng đầu của toàn nhân loại là công nhân, là người lao động”?",
		answers: [
			"C. Mác",
			"Ph. Ănghen",
			"Hồ Chí Minh",
			"V. I. Lênin",
		],
		correct: 3,
		explanation: "Dựa trên lý luận của C.Mác, Ăngghen và Lênin về vai trò của công nhân, Lênin là người đã khẳng định vai trò của LLSX hàng đầu của nhân loại là người công nhân.\" (Câu này thuộc về trích dẫn cơ bản của V.I.Lênin trong CNXHKH).",
	},
	{
		question: "Chọn phương án đúng nhất: Tìm ý đúng cho luận điểm sau: Cùng với sự phát triển của khoa học và công nghệ, giai cấp công nhân [...].",
		answers: [
			"Giảm về số lượng và nâng cao về chất lượng",
			"Tăng về số lượng và nâng cao về chất lượng",
			"Giảm về số lượng và giảm về chất lượng",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 1,
		explanation: "Dựa trên Trang 27 của chương 2 của tài liệu, chỉ ra rằng công nhân hiện đại cũng tăng nhanh về số lượng, thay đổi lớn về cơ cấu... Đồng thời được đào tạo chuẩn mực và thường xuyên được đào tạo lại.",
	},
	{
		question: "Nền sản xuất đại công nghiệp và phương thức sản xuất tiên tiến đã rèn luyện cho giai cấp công nhân những phẩm chất đặc biệt về tính tổ chức, kỷ luật lao động, tinh thần hợp tác và […].",
		answers: [
			"tâm lí lao động công nghiệp",
			"tác phong nông nghiệp",
			"tâm lí lao động nông nghiệp",
			"tâm lí lao động tự do",
		],
		correct: 0,
		explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân có những phẩm chất đặc biệt về tính tổ chức, kỷ luật lao động, tinh thần hợp tác và tâm lý lao động công nghiệp.",
	},
	{
		question: "Sự phát triển của lực lượng sản xuất mang tính xã hội hóa cao mâu thuẫn với quan hệ sản xuất dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất chủ yếu là mâu thuẫn cơ bản của phương thức sản xuất nào dưới đây?",
		answers: [
			"Chiếm hữu nô lệ",
			"Phong kiến",
			"Tư bản chủ nghĩa",
			"Cộng sản chủ nghĩa",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Mâu thuẫn cơ bản của phương thức sản xuất tư bản chủ nghĩa là mâu thuẫn giữa lực lượng sản xuất xã hội hóa ngày càng rộng lớn với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ tư hữu tư bản chủ nghĩa về tư liệu sản xuất.",
	},
	{
		question: "Biểu hiện về mặt xã hội của mâu thuẫn cơ bản trong phương thức sản xuất tư bản chủ nghĩa là mâu thuẫn giữa […].",
		answers: [
			"tư bản và lao động",
			"giai cấp công nhân và giai cấp tư sản",
			"lực lượng sản xuất và quan hệ sản xuất",
			"các tập đoàn tư bản",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Thứ hai, mâu thuẫn cơ bản của phương thức sản xuất tư bản chủ nghĩa thể hiện về mặt xã hội là mâu thuẫn về lợi ích giữa giai cấp công nhân và giai cấp tư sản.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong quan hệ sản xuất tư bản chủ nghĩa, giai cấp công nhân là giai cấp […].",
		answers: [
			"Không có tư liệu sản xuất",
			"Phải bán sức lao động",
			"Bị bóc lột giá trị thặng dư",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Đó là giai cấp của những người lao động không sở hữu tư liệu sản xuất chủ yếu của xã hội. Họ phải bán sức lao động cho nhà tư bản và bị chủ tư bản bóc lột giá trị thặng dư.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp bị giai cấp tư sản bóc lột […].",
		answers: [
			"Trực tiếp",
			"Gián tiếp",
			"Trực tiếp và gián tiếp",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Mâu thuẫn cơ bản của phương thức SX TBCN thể hiện về mặt xã hội là mâu thuẫn về lợi ích giữa giai cấp công nhân và giai cấp tư sản, lao động sống của công nhân là nguồn gốc giá trị thặng dư.\" Đây là sự bóc lột trực tiếp.",
	},
	{
		question: "Trong quan hệ sản xuất tư bản chủ nghĩa, giai cấp công nhân là giai cấp […].",
		answers: [
			"Không có tư liệu sản xuất, phải bán sức lao động cho giai cấp chủ nô và bị bóc lột",
			"Không có tư liệu sản xuất, phải bán sức lao động cho giai cấp địa chủ và bị bóc lột",
			"Không có tư liệu sản xuất, phải bán sức lao động cho giai cấp tư sản và bị bóc lột",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Họ phải bán sức lao động cho nhà tư bản và bị chủ tư bản bóc lột giá trị thặng dư.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là những người sản xuất ra […].",
		answers: [
			"Một phần của cải cho chế độ tư bản chủ nghĩa",
			"Đại đa số của cải cho chế độ tư bản chủ nghĩa",
			"Toàn bộ của cải cho mọi chế độ xã hội",
			"Tất cả các nội dung đã nêu",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Lao động sống của công nhân là nguồn gốc giá trị thặng dư và sự giàu có của giai cấp tư sản cũng chủ yếu nhờ vào việc bóc lột ngày càng nhiều hơn giá trị thặng dư.",
	},
	{
		question: "Một trong những đặc điểm chính trị - xã hội của giai cấp công nhân là giai cấp có […].",
		answers: [
			"Tinh thần cách mạng nửa vời",
			"Tinh thần cách mạng triệt để nhất",
			"Tinh thần cách mạng cải lương",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 1,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng đặc điểm chính trị - xã hội: Giai cấp công nhân là giai cấp có tinh thần cách mạng triệt để.",
	},
	{
		question: "Một trong những đặc điểm chính trị - xã hội của giai cấp công nhân là giai cấp có […].",
		answers: [
			"Ý thức tổ chức kỷ luật kém",
			"Ý thức tổ chức kỷ luật trung bình",
			"Ý thức tổ chức kỷ luật cao",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là giai cấp có ý thức tổ chức kỷ luật cao.",
	},
	{
		question: "Mâu thuẫn giữa giai cấp công nhân và giai cấp tư sản là mâu thuẫn […].",
		answers: [
			"không đối kháng về lợi ích",
			"về lợi ích không cơ bản",
			"đối kháng gián tiếp về lợi ích",
			"đối kháng trực tiếp về lợi ích",
		],
		correct: 3,
		explanation: "Dựa trên Trang 22 và Trang 26 của chương 2 của tài liệu, chỉ ra rằng mâu thuẫn đó cho thấy tính chất đối kháng không thể điều hòa... có lợi ích cơ bản đối lập trực tiếp với lợi ích của giai cấp tư sản.",
	},
	{
		question: "Giữa giai cấp công nhân và giai cấp nông dân có […].",
		answers: [
			"toàn bộ lợi ích thống nhất với nhau",
			"nhiều lợi ích cơ bản thống nhất với nhau",
			"lợi ích hoàn toàn khác nhau",
			"lợi ích hoàn toàn đối lập nhau",
		],
		correct: 1,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu (Điều kiện chủ quan), sự liên minh giai cấp giữa giai cấp công nhân với nông dân dựa trên những lợi ích cơ bản thống nhất.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp bị giai cấp tư sản bóc lột […].",
		answers: [
			"Giá trị thặng dư",
			"Giá trị sử dụng",
			"Giá trị trao đổi",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Họ phải bán sức lao động cho nhà tư bản và bị chủ tư bản bóc lột giá trị thặng dư.",
	},
	{
		question: "Giai cấp công nhân là giai cấp có mâu thuẫn đối kháng với […].",
		answers: [
			"Giai cấp nông dân",
			"Giai cấp địa chủ",
			"Giai cấp tư sản",
			"Tầng lớp trí thức",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng Mâu thuẫn cơ bản của phương thức sản xuất tư bản chủ nghĩa thể hiện về mặt xã hội là mâu thuẫn về lợi ích giữa giai cấp công nhân và giai cấp tư sản.",
	},
	{
		question: "Một trong những nội dung sứ mệnh lịch sử của giai cấp công nhân là […].",
		answers: [
			"Xóa bỏ chế độ tư bản chủ nghĩa",
			"Xóa bỏ chế độ phong kiến",
			"Xóa bỏ chế độ chiếm hữu nô lệ",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Nội dung sứ mệnh lịch sử tổng quát là: xóa bỏ chế độ người bóc lột người, xóa bỏ chủ nghĩa tư bản.",
	},
	{
		question: "Một trong những nội dung sứ mệnh lịch sử của giai cấp công nhân là […].",
		answers: [
			"Xây dựng chế độ chiếm hữu nô lệ",
			"Xây dựng chế độ phong kiến",
			"Xây dựng chế độ tư bản chủ nghĩa",
			"Xây dựng xã hội xã hội chủ nghĩa và cộng sản chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng xây dựng chủ nghĩa xã hội và chủ nghĩa cộng sản.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, có mấy điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân?",
		answers: [
			"2",
			"3",
			"4",
			"5",
		],
		correct: 0,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Những điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân gồm 2 điều kiện: a. Địa vị kinh tế - xã hội của giai cấp công nhân; b. Đặc điểm chính trị - xã hội của giai cấp công nhân.",
	},
	{
		question: "Quan điểm nào dưới đây không đúng về giai cấp công nhân?",
		answers: [
			"Giai cấp công nhân là một tập đoàn xã hội ổn định, hình thành và phát triển cùng với quá trình phát triển của nền công nghiệp hiện đại",
			"Giai cấp công nhân là giai cấp không đại diện cho quan hệ sản xuất tiên tiến",
			"Giai cấp công nhân là lực lượng chủ yếu của tiến trình lịch sử quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội",
			"Giai cấp công nhân là chủ thể của quá trình sản xuất vật chất hiện đại",
		],
		correct: 1,
		explanation: "Dựa trên Trang 21 và 23 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân đại diện cho lực lượng sản xuất tiên tiến và phương thức sản xuất tiên tiến. Nên phát biểu 'không đại diện' là sai.",
	},
	{
		question: "Phát biểu nào dưới đây không đúng về giai cấp công nhân?",
		answers: [
			"Giai cấp công nhân là người làm thuê do không có tư liệu sản xuất, buộc phải bán sức lao động để sống và bị giai cấp tư sản bóc lột giá trị thặng dư",
			"Giai cấp công nhân là người làm thuê do không có tư liệu sản xuất, buộc phải bán sức lao động để sống, không bị giai cấp tư sản bóc lột giá trị thặng dư",
			"Lợi ích cơ bản của giai cấp công nhân đối lập với lợi ích cơ bản của giai cấp tư sản",
			"Giai cấp công nhân là giai cấp có sứ mệnh phủ định chế độ tư bản chủ nghĩa, xây dựng thành công chủ nghĩa xã hội và chủ nghĩa cộng sản trên toàn thế giới",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng GCCN bị chủ tư bản bóc lột giá trị thặng dư. Phát biểu B cho rằng 'không bị bóc lột' là sai.",
	},
	{
		question: "Một trong những điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Tư tưởng",
			"Chính trị",
			"Địa vị kinh tế - xã hội",
			"Văn hóa",
		],
		correct: 2,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân gồm: Địa vị kinh tế - xã hội và Đặc điểm chính trị - xã hội.",
	},
	{
		question: "Một trong những điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Văn hóa",
			"Tư tưởng",
			"Đặc điểm chính trị - xã hội",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 25-26 của chương 2 của tài liệu, chỉ ra rằng Điều kiện khách quan thứ hai là Đặc điểm chính trị - xã hội của giai cấp công nhân.",
	},
	{
		question: "Chọn phương án đúng nhất: Điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Giai cấp công nhân là con đẻ của nền đại công nghiệp",
			"Địa vị kinh tế - xã hội và đặc điểm chính trị - xã hội của giai cấp công nhân",
			"Sự phát triển của lực lượng sản xuất",
			"Tất cả các nội dung đã nêu",
		],
		correct: 1,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Những điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân: Địa vị kinh tế - xã hội và Đặc điểm chính trị - xã hội.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp tiên phong cách mạng vì họ là giai cấp […].",
		answers: [
			"Đại biểu cho phương thức sản xuất tiên tiến",
			"Được trang bị lý luận khoa học cách mạng",
			"Luôn đi đầu trong mọi phong trào cách mạng",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 25-26 của chương 2 của tài liệu (Điều kiện khách quan và chủ quan), GCCN đại diện cho PTSX tiên tiến, có tinh thần triệt để, thông qua ĐCS được trang bị lí luận và đi đầu cách mạng.",
	},
	{
		question: "Phát biểu nào dưới đây không phải là đặc điểm của giai cấp công nhân mang sứ mệnh lịch sử thế giới?",
		answers: [
			"Giai cấp công nhân là giai cấp đại diện cho lực lượng sản xuất tiến bộ của thời đại",
			"Giai cấp công nhân là lực lượng đông đảo và tiên phong",
			"Giai cấp công nhân là lực lượng tiến bộ nhưng chỉ bảo vệ lợi ích cho giai cấp mình",
			"Giai cấp công nhân là lực lượng đại diện cho khuynh hướng tiến bộ của nhân loại",
		],
		correct: 2,
		explanation: "Dựa trên Trang 23 và 26 của chương 2 của tài liệu, giai cấp công nhân mang bản chất quốc tế và bảo vệ lợi ích không chỉ của giai cấp mình mà còn của đa số nhân dân lao động.",
	},
	{
		question: "Nội dung nào dưới đây không phải là sứ mệnh lịch sử thế giới của giai cấp công nhân?",
		answers: [
			"Giải phóng cho giai cấp công nhân và toàn thể nhân loại khỏi áp bức",
			"Xoá bỏ tận gốc chế độ người bóc lột người, xoá bỏ chủ nghĩa tư bản",
			"Xây dựng xã hội cộng sản chủ nghĩa văn minh",
			"Xoá bỏ tận gốc chế độ người bóc lột người, giải phóng cho giai cấp tư sản",
		],
		correct: 3,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, sứ mệnh là xóa bỏ chủ nghĩa tư bản, giải phóng giai cấp công nhân và nhân dân lao động, không phải là 'giải phóng cho giai cấp tư sản'.",
	},
	{
		question: "Mục tiêu nào dưới đây là mục tiêu lớn nhất mà giai cấp công nhân thực hiện?",
		answers: [
			"Xoá bỏ tận gốc chế độ người bóc lột người",
			"Xoá bỏ tận gốc chế độ tư bản chủ nghĩa",
			"Xoá bỏ tận gốc chế độ phong kiến",
			"Xoá bỏ tận gốc chế độ nô lệ làm thuê",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24-25 của chương 2 của tài liệu, Sứ mệnh lịch sử tổng quát nêu rõ: xóa bỏ chế độ người bóc lột người, giải phóng giai cấp công nhân, nhân dân lao động với mục tiêu cao nhất là giải phóng con người.",
	},
	{
		question: "Quan điểm nào sau đây phản ánh đúng về tư tưởng việc xoá bỏ hình thái kinh tế — xã hội tư bản chủ nghĩa?",
		answers: [
			"Xoá bỏ cả quan hệ sản xuất bóc lột và lực lượng sản xuất trong chủ nghĩa tư bản",
			"Xoá bỏ quan hệ sản xuất bóc lột và kế thừa thành tựu tiến bộ về lực lượng sản xuất trong chủ nghĩa tư bản",
			"Xoá bỏ lực lượng sản xuất và kế thừa thành tựu tiến bộ về quan hệ sản xuất trong chủ nghĩa tư bản",
			"Xoá bỏ văn hoá và tư tưởng bóc lột trong chủ nghĩa tư bản",
		],
		correct: 1,
		explanation: "Dựa trên sự phát triển hợp logic của hình thái kinh tế xã hội và Trang 48 (liên kết kiến thức), việc quá độ là xóa bỏ quan hệ sản xuất bóc lột TBCN nhưng tiếp thu kế thừa thành tựu LLSX.",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp có tinh thần cách mạng triệt để nhất vì họ là giai cấp […].",
		answers: [
			"Xóa bỏ tận gốc chế độ tư hữu về tư liệu sản xuất",
			"Xóa bỏ chế độ công hữu về tư liệu sản xuất",
			"Xóa bỏ mọi hình thức sở hữu về tư liệu sản xuất",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Không phải là thay thế chế độ sở hữu tư nhân này bằng một chế độ sở hữu tư nhân khác mà là xóa bỏ triệt để chế độ tư hữu về tư liệu sản xuất.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết nội bộ giai cấp vì họ có chung […].",
		answers: [
			"Địa vị kinh tế - xã hội",
			"Điều kiện làm việc",
			"Điều kiện sống",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, vì có chung địa vị kinh tế xã hội, môi trường làm việc tập trung cao độ nên GCCN có ý thức tổ chức kỷ luật và đoàn kết nội bộ tốt.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết với các giai cấp, tầng lớp lao động khác vì họ […].",
		answers: [
			"Có chung lợi ích kinh tế",
			"Đều bị giai cấp tư sản bóc lột",
			"Có chung nguyện vọng được giải phóng",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, sự liên minh giữa giai cấp công nhân với nông dân và tầng lớp lao động khác do có sự tương đồng về lợi ích (bị bóc lột, cùng mục đích giải phóng).",
	},
	{
		question: "Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có bao nhiêu đặc điểm chính trị - xã hội?",
		answers: [
			"4",
			"5",
			"6",
			"7",
		],
		correct: 0,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Đặc điểm chính trị - xã hội của giai cấp công nhân gồm 4 điểm: 1. Tiên tiến nhất; 2. Ý thức tổ chức kỷ luật cao; 3. Tinh thần cách mạng triệt để; 4. Bản chất quốc tế.",
	},
	{
		question: "Trong chủ nghĩa tư bản, mục tiêu của công nhân là xoá bỏ quan hệ sản xuất dựa trên chế độ […].",
		answers: [
			"công hữu về tư liệu sản xuất chủ yếu",
			"sở hữu chung về tư liệu sản xuất chủ yếu",
			"sở hữu công cộng về tư liệu sản xuất chủ yếu",
			"sở hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất chủ yếu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 22 và 24 của chương 2 của tài liệu, chỉ ra rằng Về kinh tế: Cải tạo quan hệ sản xuất tư nhân tư bản chủ nghĩa, xây dựng quan hệ sản xuất mới - xã hội chủ nghĩa.",
	},
	{
		question: "Muốn thực hiện sứ mệnh lịch sử thế giới của mình, giai cấp công nhân phải […].",
		answers: [
			"lật đổ sự thống trị của giai cấp tư sản, giành chính quyền về tay giai cấp mình, thiết lập nhà nước chuyên chính vô sản, cải tạo xã hội cũ, xây dựng xã hội mới",
			"lật đổ sự thống trị của giai cấp vô sản, giành chính quyền về tay giai cấp mình, thiết lập nhà nước, cải tạo xã hội cũ, xây dựng xã hội mới",
			"lật đổ sự thống trị của giai cấp tiểu tư sản, giành chính quyền về tay giai cấp mình, cải tạo xã hội cũ, xây dựng xã hội mới",
			"lật đổ sự thống trị của bộ phận tư sản hiện đại, giành chính quyền về tay giai cấp mình, cải tạo xã hội cũ, xây dựng xã hội mới",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Về nội dung chính trị - xã hội: Lật đổ sự thống trị của giai cấp tư sản, thiết lập nhà nước của giai cấp công nhân và nhân dân lao động.",
	},
	{
		question: "Để thực hiện sứ mệnh lịch sử của mình, bước đầu tiên giai cấp công nhân phải làm là […].",
		answers: [
			"giành chính quyền, thiết lập được nhà nước của giai cấp mình",
			"xoá bỏ sự bóc lột đem lại hạnh phúc, ấm no cho nhân dân",
			"cải tạo xã hội cũ, xây dựng thành công xã hội mới - xã hội cộng sản chủ nghĩa",
			"liên minh với nông dân, giải phóng cho loài người",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Trong giai đoạn hiện nay... mục tiêu lâu dài là giành chính quyền về tay giai cấp công nhân và nhân dân lao động (bước tiên quyết về mặt chính trị).",
	},
	{
		question: "Xoá bỏ quan hệ sản xuất dựa trên chế độ chiếm hữu tư nhân tư bản về tư liệu sản xuất chủ yếu, xây dựng quan hệ sản xuất mới, phù hợp với tính chất xã hội hoá cao của lực lượng sản xuất, với chế độ công hữu về tư liệu sản xuất chủ yếu của xã hội là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"kinh tế",
			"văn hoá",
			"chính trị - xã hội",
			"tư tưởng",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Về nội dung kinh tế: Cải tạo quan hệ sản xuất tư nhân tư bản chủ nghĩa, xây dựng quan hệ sản xuất mới - xã hội chủ nghĩa.",
	},
	{
		question: "Chủ thể chiếm hữu tư liệu sản xuất chủ yếu trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Giai cấp công nhân",
			"Giai cấp tư sản",
			"Giai cấp địa chủ",
			"Giai cấp nông dân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng phương thức sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất (Giai cấp tư sản).",
	},
	{
		question: "Đại biểu cho lực lượng sản xuất tiên tiến trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Giai cấp nông dân",
			"Giai cấp tư sản",
			"Giai cấp công nhân",
			"Tầng lớp trí thức",
		],
		correct: 2,
		explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến.",
	},
	{
		question: "Đại biểu cho quan hệ sản xuất chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất trong chế độ tư bản chủ nghĩa là […].",
		answers: [
			"Giai cấp công nhân",
			"Giai cấp nông dân",
			"Giai cấp tư sản",
			"Tất cả các nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên Trang 22 của chương 2 của tài liệu, chỉ ra rằng giai cấp tư sản đại biểu cho quan hệ sản xuất dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa.",
	},
	{
		question: "Quy luật ra đời của Đảng cộng sản ở các nước tư bản chủ nghĩa phát triển là sự kết hợp […].",
		answers: [
			"Chủ nghĩa Mác với phong trào công nhân",
			"Chủ nghĩa Mác với phong trào công nhân và phong trào yêu nước",
			"Chủ nghĩa Mác với phong trào công nhân và phong trào nông dân",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Quy luật ra đời và phát triển chính đảng của giai cấp công nhân - Đảng Cộng sản: sự kết hợp giữa chủ nghĩa xã hội khoa học, tức chủ nghĩa Mác với phong trào công nhân.",
	},
	{
		question: "Tổ chức chính trị cao nhất để lãnh đạo giai cấp công nhân thực hiện sứ mệnh lịch sử là […].",
		answers: [
			"Công đoàn",
			"Nghiệp đoàn",
			"Đảng cộng sản",
			"Tất cả các nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Đảng Cộng sản là đội tiên phong của giai cấp công nhân, là tổ chức chính trị cao nhất, là lãnh tụ chính trị...",
	},
	{
		question: "Phong trào đấu tranh của giai cấp công nhân chỉ trở thành phong trào chính trị khi có sự lãnh đạo của tổ chức nào?",
		answers: [
			"Đảng cộng sản",
			"Công đoàn",
			"Nghiệp đoàn",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Đảng Cộng sản đem lại sự giác ngộ, sức mạnh... trí tuệ và hành động cách mạng cho toàn bộ giai cấp công nhân (biến phong trào tự phát thành tự giác, có tính chính trị).",
	},
	{
		question: "Thực hiện công nghiệp hoá, gắn liền công nghiệp hoá với hiện đại hoá, đẩy mạnh công nghiệp hoá gắn với phát triển kinh tế tri thức, bảo vệ tài nguyên, môi trường là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"kinh tế",
			"tư tưởng",
			"chính trị - xã hội",
			"văn hoá",
		],
		correct: 0,
		explanation: "Dựa trên Trang 28 của chương 2 của tài liệu, chỉ ra rằng Về kinh tế: Giai cấp công nhân là lực lượng đi đầu trong sự nghiệp đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước.",
	},
	{
		question: "Lật đổ quyền thống trị của giai cấp tư sản, giành quyền lực về tay giai cấp công nhân và nhân dân lao động, thiết lập nhà nước mang bản chất giai cấp công nhân, xây dựng nền dân chủ xã hội chủ nghĩa, thực hiện quyền lực của nhân dân, quyền dân chủ và làm chủ xã hội của tuyệt đại đa số nhân dân lao động là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"chính trị - xã hội",
			"kinh tế",
			"văn hoá",
			"tư tưởng",
		],
		correct: 0,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Về nội dung chính trị - xã hội: Lật đổ sự thống trị của giai cấp tư sản, thiết lập nhà nước của giai cấp công nhân và nhân dân lao động.",
	},
	{
		question: "Sử dụng nhà nước của mình để cải tạo xã hội cũ và tổ chức xây dựng xã hội mới, phục vụ quyền và lợi ích của nhân dân lao động theo lí tưởng và mục tiêu của chủ nghĩa xã hội là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"kinh tế",
			"chính trị - xã hội",
			"văn hoá",
			"tư tưởng",
		],
		correct: 1,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Về nội dung chính trị - xã hội: ... tưng bước xây dựng nền dân chủ xã hội chủ nghĩa (sử dụng quyền lực chính trị để tổ chức xã hội).",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, thông qua sự lãnh đạo của Đảng cộng sản, giai cấp công nhân […].",
		answers: [
			"Nhận thức được vị trí, vai trò của mình trong xã hội",
			"Hiểu được con đường, biện pháp đấu tranh cách mạng",
			"Tập hợp được đông đảo quần chúng nhân dân lao động",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 26-27 của chương 2 của tài liệu, chỉ ra rằng Đảng Cộng sản đem lại sự giác ngộ, sức mạnh đoàn kết... đề ra mục tiêu, phương hướng, đường lối chính sách đúng đắn.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong mối quan hệ với giai cấp công nhân và nhân dân lao động, Đảng cộng sản là […].",
		answers: [
			"Đội tiên phong chiến đấu",
			"Lãnh tụ chính trị",
			"Bộ tham mưu chiến đấu",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Đảng Cộng sản là đội tiên phong của giai cấp công nhân, là tổ chức chính trị cao nhất, là lãnh tụ chính trị, là bộ tham mưu chiến đấu.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong mối quan hệ với Đảng cộng sản, giai cấp công nhân là […].",
		answers: [
			"Cơ sở kinh tế của Đảng cộng sản",
			"Cơ sở xã hội của Đảng cộng sản",
			"Cơ sở văn hóa của Đảng cộng sản",
			"Cơ sở chính trị của Đảng cộng sản",
		],
		correct: 1,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng Trong đó, giai cấp công nhân là cơ sở xã hội và nguồn bổ sung lực lượng quan trọng nhất của Đảng.",
	},
	{
		question: "Xây dựng hệ giá trị mới: lao động; công bằng; dân chủ; bình đẳng và tự do là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"kinh tế",
			"chính trị",
			"xã hội",
			"văn hoá, tư tưởng",
		],
		correct: 3,
		explanation: "Dựa trên Trang 24 và 29 của chương 2 của tài liệu, chỉ ra rằng Về nội dung văn hóa, tư tưởng: Xây dựng nền văn hóa mới, trên nền tảng hệ tư tưởng chính trị của giai cấp công nhân... đấu tranh hệ giá trị.",
	},
	{
		question: "Xây dựng và củng cố ý thức hệ tiên tiến của giai cấp công nhân, đấu tranh để khắc phục ý thức hệ tư sản và các tàn dư còn sót lại của các hệ tư tưởng cũ là nhiệm vụ của giai cấp công nhân trên lĩnh vực […].",
		answers: [
			"kinh tế",
			"chính trị",
			"văn hoá, tư tưởng",
			"xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, chỉ ra rằng Về nội dung văn hóa, tư tưởng: Xây dựng nền văn hóa mới, thay thế hệ tư tưởng chính trị của giai cấp tư sản.",
	},
	{
		question: "Tiếp thu có chọn lọc, trên tinh thần phê phán những tinh hoa giá trị những thành tựu văn hoá tư tưởng của mọi thời đại, kể cả thời đại tư sản trong lịch sử văn hóa và văn minh của nhân loại là điều mà giai cấp công nhân cần chú ý khi thực hiện sứ mệnh của mình trong lĩnh vực nào dưới đây?",
		answers: [
			"Kinh tế",
			"Chính trị",
			"Văn hoá, tư tưởng",
			"Xã hội",
		],
		correct: 2,
		explanation: "Dựa trên bản chất của nội dung lĩnh vực văn hóa, tư tưởng (Trang 24), GCCN phải tiếp thu và phát triển tinh hoa văn hóa bên cạnh việc đấu tranh ý thức hệ.",
	},
	{
		question: "Cải tạo cái lỗi thời, lạc hậu, xây dựng cái mới, tiến bộ trong lĩnh vực ý thức tư tưởng, trong tâm lí, lối sống và trong đời sống tinh thần xã hội là nhiệm vụ của giai cấp công nhân trong lĩnh vực […].",
		answers: [
			"Tâm lí, ý thức",
			"Chính trị",
			"Văn hóa, tư tưởng",
			"Xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 24 và 29 của chương 2 của tài liệu, chỉ ra rằng Về văn hóa, tư tưởng: Cuộc đấu tranh ý thức hệ... xây dựng con người mới xã hội chủ nghĩa.",
	},
	{
		question: "Xây dựng con người mới, đạo đức và lối sống mới xã hội chủ nghĩa là một trong những nhiệm vụ đặt ra đối với sứ mệnh lịch sử của giai cấp công nhân trong lĩnh vực nào dưới đây?",
		answers: [
			"Tâm lý, ý thức",
			"Đạo đức",
			"Văn hoá, tư tưởng",
			"Xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 24 và Trang 29 của chương 2 của tài liệu, việc xây dựng con người mới xã hội chủ nghĩa thuộc vào Về văn hóa, tư tưởng.",
	},
	{
		question: "Sứ mệnh lịch sử của giai cấp công nhân không phải là thay thế chế độ sở hữu tư nhân này bằng một chế độ sở hữu tư nhân khác mà là […].",
		answers: [
			"xoá bỏ một phần chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"xóa bỏ triệt để chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"xoá bỏ hoàn toàn chế độ công hữu về tư liệu sản xuất chủ yếu",
			"xoá bỏ phần lớn chế độ tư hữu về tư liệu sản xuất chủ yếu",
		],
		correct: 1,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Đặc điểm sứ mệnh: Không phải là thay thế chế độ sở hữu tư nhân này bằng một chế độ sở hữu tư nhân khác mà là xóa bỏ triệt để chế độ tư hữu về tư liệu sản xuất.",
	},
	{
		question: "Mục tiêu cao nhất trong việc thực hiện sứ mệnh lịch sử thế giới của giai cấp công nhân là […].",
		answers: [
			"giải phóng dân tộc khỏi ách áp bức của chủ nghĩa thực dân",
			"giải phóng nông dân khỏi chế độ phong kiến",
			"giải phóng con người",
			"giành chính quyền, thiết lập nhà nước mới",
		],
		correct: 2,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng việc giai cấp công nhân giành lấy quyền lực thống trị xã hội... với mục tiêu cao nhất là giải phóng con người.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong mối quan hệ với Đảng cộng sản, giai cấp công nhân là nguồn bổ sung lực lượng cho […].",
		answers: [
			"Đảng cộng sản",
			"Nhà nước xã hội chủ nghĩa",
			"Các tổ chức chính trị - xã hội",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 26 của chương 2 của tài liệu, chỉ ra rằng giai cấp công nhân là cơ sở xã hội và nguồn bổ sung lực lượng quan trọng nhất của Đảng.",
	},
	{
		question: "Cách mạng xã hội chủ nghĩa là cuộc cách mạng nhằm […].",
		answers: [
			"Thay chế độ chiếm hữu nô lệ bằng chế độ phong kiến",
			"Thay chế độ phong kiến bằng chế độ tư bản chủ nghĩa",
			"Thay chế độ tư bản chủ nghĩa bằng chế độ xã hội chủ nghĩa",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên định nghĩa về cách mạng xã hội chủ nghĩa (kiến thức tổng hợp Chương 1 & Chương 3, liên quan mật thiết mục tiêu GCCN Trang 24): thực hiện bước chuyển từ chủ nghĩa tư bản lên chủ nghĩa xã hội và chủ nghĩa cộng sản.",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, cách mạng xã hội chủ nghĩa được hiểu theo mấy nghĩa?",
		answers: [
			"2",
			"3",
			"4",
			"5",
		],
		correct: 0,
		explanation: "Dựa trên lý luận Mác-Lênin về cách mạng xã hội chủ nghĩa, cách mạng XHCN được hiểu theo 2 nghĩa: nghĩa hẹp (giành chính quyền) và nghĩa rộng (cải tạo và xây dựng toàn diện).",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, cách mạng xã hội chủ nghĩa được hiểu theo nghĩa hẹp là cuộc cách mạng […].",
		answers: [
			"Kinh tế",
			"Chính trị",
			"Văn hóa",
			"Tất cả các nội dung đã nêu",
		],
		correct: 1,
		explanation: "Dựa trên nền tảng lý luận CNXHKH (Chương 2 và 3), cách mạng XHCN theo nghĩa hẹp là cuộc cách mạng chính trị nhằm giành chính quyền về tay giai cấp vô sản.",
	},
	{
		question: "Chọn phương án đúng nhất: Theo quan điểm của chủ nghĩa Mác - Lênin, cách mạng xã hội chủ nghĩa được hiểu theo nghĩa rộng là cuộc cách mạng […].",
		answers: [
			"Giành chính quyền nhà nước",
			"Cải tạo xã hội cũ",
			"Xây dựng chế độ xã hội chủ nghĩa và cộng sản chủ nghĩa",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên quá trình thực hiện Sứ mệnh lịch sử (Trang 24), cách mạng theo nghĩa rộng bao gồm toàn bộ quá trình: giành chính quyền, thiết lập nhà nước, cải tạo xã hội cũ, xây dựng xã hội mới.",
	},
	{
		question: "Câu nói: \"Cùng với sự phát triển của đại công nghiệp (...) giai cấp tư sản sản sinh ra những người đào huyệt chôn chính nó. Sự sụp đổ của giai cấp tư sản và thắng lợi của giai cấp vô sản đều là tất yếu như nhau\" phản ánh nội dung nào dưới đây?",
		answers: [
			"Khẳng định tính tất yếu khách quan quy định sứ mệnh lịch sử của GCCN",
			"Khẳng định nguyện vọng giải phóng mình của nhân dân lao động",
			"Nhấn mạnh vai trò của Đảng Cộng sản trong việc thực hiện sứ mệnh lịch sử thế giới của giai cấp công nhân",
			"Sự phát triển tất yếu của LLSX",
		],
		correct: 0,
		explanation: "Dựa trên phân tích Điều kiện khách quan quy định sứ mệnh lịch sử (Trang 24-25), sự tất yếu sụp đổ của TBCN do chính TBCN đã tạo ra người đào huyệt chôn nó là GCCN.",
	},
	{
		question: "Sứ mệnh lịch sử thế giới của giai cấp công nhân được quy định bởi […].",
		answers: [
			"địa vị kinh tế — xã hội của giai cấp công nhân",
			"nguyện vọng của giai cấp công nhân",
			"sự lãnh đạo của Đảng Cộng sản đối với giai cấp công nhân",
			"nguyện vọng của nhân dân lao động",
		],
		correct: 0,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng Những điều kiện quy định sứ mệnh lịch sử của giai cấp công nhân gồm Điều kiện khách quan: Địa vị kinh tế - xã hội (và đặc điểm chính trị - xã hội).",
	},
	{
		question: "Giai cấp công nhân là sản phẩm của nền đại công nghiệp trong phương thức sản xuất tư bản chủ nghĩa, là chủ thể của quá trình sản xuất vật chất hiện đại, vì thế, giai cấp công nhân đại diện cho […].",
		answers: [
			"phương thức sản xuất lỗi thời và lực lượng sản xuất hiện đại",
			"phương thức sản xuất tiên tiến và lực lượng sản xuất lạc hậu",
			"phương thức sản xuất tiên tiến và lực lượng sản xuất hiện đại",
			"phương thức sản xuất lỗi thời và lực lượng sản xuất lạc hậu",
		],
		correct: 2,
		explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, chỉ ra rằng Giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến.",
	},
	{
		question: "Giai cấp công nhân là sản phẩm của nền đại công nghiệp trong phương thức sản xuất tư bản chủ nghĩa, là chủ thể của quá trình sản xuất vật chất hiện đại, vì thế, giai cấp công nhân là lực lượng […].",
		answers: [
			"Phá vỡ quan hệ sản xuất phong kiến, giành chính quyền về tay giai cấp mình",
			"phá vỡ quan hệ sản xuất xã hội chủ nghĩa, giành chính quyền về tay giai cấp mình",
			"phá vỡ quan hệ sản xuất tư bản chủ nghĩa, giành chính quyền cho giai cấp nông dân",
			"phá vỡ quan hệ sản xuất tư bản chủ nghĩa, giành chính quyền về tay giai cấp mình",
		],
		correct: 3,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng GCCN là lực lượng quyết định trong việc phá vỡ quan hệ sản xuất tư bản chủ nghĩa, xây dựng phương thức sản xuất mới.",
	},
	{
		question: "Tinh thần đoàn kết, ý thức tổ chức kỉ luật cao là nội dung thể hiện […].",
		answers: [
			"đặc điểm chính trị - xã hội của giai cấp công nhân",
			"địa vị kinh tế — xã hội của giai cấp công nhân",
			"thói quen của giai cấp công nhân",
			"đặc điểm vốn có của con người nói chung",
		],
		correct: 0,
		explanation: "Dựa trên Trang 25-26 của chương 2 của tài liệu, mục 'Đặc điểm chính trị - xã hội của giai cấp công nhân' bao gồm: ý thức tổ chức kỷ luật cao.",
	},
	{
		question: "Phát biểu nào dưới đây không đúng về điều kiện khách quan quy định sứ mệnh lịch sử thế giới của giai cấp công nhân?",
		answers: [
			"Giai cấp công nhân đại diện cho lực lượng sản xuất hiện đại",
			"Giai cấp công nhân đại diện cho phương thức sản xuất tiên tiến",
			"Giai cấp công nhân là giai cấp đại biểu cho tương lai, cho xu thế đi lên của lịch sử",
			"Giai cấp công nhân là giai cấp vô cùng nghèo khổ",
		],
		correct: 3,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, Sứ mệnh lịch sử được quy định bởi địa vị KT-XH (đại diện LLSX tiên tiến) và đặc điểm chính trị - xã hội, chứ không phải dựa trên sự nghèo khổ.",
	},
	{
		question: "Giai cấp công nhân là lực lượng quyết định […].",
		answers: [
			"máy móc trong các nhà máy xí nghiệp của các nhà tư sản",
			"quan hệ sản xuất tư bản chủ nghĩa",
			"quan hệ giữa tư sản và các giai tầng khác trong xã hội tư bản chủ nghĩa",
			"Chủ nghĩa tư bản độc quyền",
		],
		correct: 1,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng là lực lượng quyết định trong việc phá vỡ quan hệ sản xuất tư bản chủ nghĩa.",
	},
	{
		question: "Giai cấp nông dân không thể là giai cấp có sứ mệnh lịch sử thế giới xoá bỏ chế độ tư bản chủ nghĩa, xây dựng chế độ xã hội mới - cộng sản chủ nghĩa bởi […].",
		answers: [
			"họ không đại diện cho phương thức sản xuất tiên tiến",
			"họ có tư tưởng sở hữu lớn",
			"họ có số lượng không đông đảo",
			"họ có hệ tư tưởng riêng nhưng thiếu tinh thần đoàn kết",
		],
		correct: 0,
		explanation: "Dựa trên so sánh với GCCN (Trang 25), GCCN đảm nhận sứ mệnh lịch sử do họ là bộ phận quan trọng nhất, đại diện cho LLSX tiên tiến (phương thức sản xuất công nghiệp), trong khi giai cấp nông dân gắn với PTSX nhỏ lẻ, không đại diện cho PTSX tiên tiến.",
	},
	{
		question: "Chọn phương án đúng nhất: Theo quan điểm của chủ nghĩa Mác - Lênin, mục tiêu chung của cách mạng xã hội chủ nghĩa là […].",
		answers: [
			"Giải phóng giai cấp nông dân",
			"Giải phóng giai cấp công nhân",
			"Giải phóng dân tộc",
			"Giải phóng xã hội, giải phóng con người",
		],
		correct: 3,
		explanation: "Dựa trên Trang 25 của chương 2 của tài liệu, chỉ ra rằng với mục tiêu cao nhất là giải phóng con người.",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, mục tiêu giai đoạn thứ nhất của cách mạng xã hội chủ nghĩa là […].",
		answers: [
			"Giành chính quyền nhà nước",
			"Giải phóng xã hội",
			"Giải phóng con người",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên lộ trình Sứ mệnh lịch sử (Trang 24), mục tiêu trước tiên/bước đầu tiên là giành chính quyền về tay giai cấp công nhân và nhân dân lao động.",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, mục tiêu giai đoạn thứ hai của cách mạng xã hội chủ nghĩa là […].",
		answers: [
			"Lật đổ sự thống trị của giai cấp tư sản",
			"Giành chính quyền",
			"Tổ chức và xây dựng xã hội mới về mọi mặt",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 24 của chương 2 của tài liệu, sau khi thiết lập nhà nước, giai đoạn tiếp theo là sử dụng chính quyền để cải tạo xã hội cũ, xây dựng xã hội mới.",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, nguyên nhân sâu xa của mọi cuộc cách mạng xã hội trong lịch sử là mâu thuẫn giữa […].",
		answers: [
			"Giai cấp công nhân và giai cấp tư sản",
			"Giai cấp nông dân và giai cấp địa chủ",
			"Giai cấp nô lệ và giai cấp chủ nô",
			"Lực lượng sản xuất tiên tiến và quan hệ sản xuất lỗi thời, lạc hậu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 37 (Chương 3 - kiến thức nền tảng về CM XHCN), mâu thuẫn giữa tính chất xã hội hóa của LLSX với chế độ chiếm hữu tư nhân (QHSX lỗi thời) là nguyên nhân sâu xa dẫn đến cách mạng.",
	},
	{
		question: "Nội dung nào dưới đây không phải là đặc điểm chính trị - xã hội của giai cấp công nhân?",
		answers: [
			"Tiên phong cách mạng và có tinh thần cách mạng triệt để nhất",
			"Có bản chất quốc tế",
			"Có ý thức, kỷ luật cao",
			"Đại diện cho lực lượng sản xuất hiện đại",
		],
		correct: 3,
		explanation: "Dựa trên Trang 25-26 của chương 2 của tài liệu, 'Đại diện cho lực lượng sản xuất hiện đại' thuộc về Đặc điểm/Địa vị Kinh tế - xã hội, KHÔNG thuộc Đặc điểm Chính trị - xã hội.",
	},
    {
        question: "Nội dung nào dưới đây không phải là nguyên nhân của việc giai cấp công nhân có tính tổ chức kỉ luật cao?",
        answers: [
            "Đặc thù môi trường làm việc là dây chuyền sản xuất công nghiệp",
            "Sự quản lí chặt chẽ của giai cấp tư sản",
            "Bản chất sẵn có của công nhân",
            "Yêu cầu của đấu tranh cách mạng",
        ],
        correct: 2,
        explanation: "Dựa trên Trang 23 của chương 2 của tài liệu, tính tổ chức kỷ luật là do nền sản xuất đại công nghiệp rèn luyện, do môi trường làm việc khắt khe, không phải là bản chất bẩm sinh (sẵn có)."
    }
];