const cnxhChapter1 = [
	{
		question: "Chủ nghĩa xã hội khoa học là một trong ba bộ phận cấu thành của…",
		answers: [
			"chủ nghĩa Mác - Lênin",
			"triết học Mác – Lênin",
			"kinh tế chính trị Mác – Lênin",
			"chủ nghĩa xã hội không tưởng",
		],
		correct: 0,
		explanation: "Dựa trên Trang 3 (Lời nói đầu) của chương 1 của tài liệu, chỉ ra rằng Chương trình các môn Lý luận chính trị bao gồm Triết học Mác-Lênin, Kinh tế chính trị Mác-Lênin, Chủ nghĩa xã hội khoa học tạo thành một chỉnh thể thống nhất của chủ nghĩa Mác - Lênin.",
	},
	{
		question: "Học thuyết giá trị thặng dư là phát kiến vĩ đại của C.Mác và của Ph.Ăngghen trong?",
		answers: [
			"triết học Mác — Lênin",
			"kinh tế chính trị Mác - Lênin",
			"chủ nghĩa xã hội khoa học",
			"chủ nghĩa xã hội hiện thực",
		],
		correct: 1,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về giá trị thặng dư: Đây là phát kiến vĩ đại thứ hai của C.Mác và Ph.Ăngghen, khẳng định về phương diện kinh tế sự diệt vong không tránh khỏi của chủ nghĩa tư bản.",
	},
	{
		question: "Trong phương thức sản xuất TBCN, mâu thuẫn về phương diện chính trị - xã hội là mâu thuẫn giữa giai cấp...",
		answers: [
			"Vô sản với tư sản",
			"Chủ nô với nô lệ",
			"Nông dân với địa chủ",
			"Trí thức với công nhân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng ở sơ đồ Điều kiện tiền đề ra đời CNXHKH, sự phát triển của PTSX TBCN sinh ra Mâu thuẫn giữa giai cấp TS (tư sản) và VS (vô sản).",
	},
	{
		question: "Nội dung nào dưới đây là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong chủ nghĩa xã hội khoa học?",
		answers: [
			"Chủ nghĩa duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Phép biện chứng duy vật",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 3,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân... Với phát kiến thứ ba này, những hạn chế có tính lịch sử của chủ nghĩa xã hội không tưởng - phê phán đã được khắc phục một cách triệt để.",
	},
	{
		question: "Chủ nghĩa Mác - Lênin gồm ba bộ phận cấu thành là: triết học Mác - Lênin, kinh tế chính trị Mác - Lênin và",
		answers: [
			"mĩ học Mác - Lênin",
			"đạo đức học Mác - Lênin",
			"chủ nghĩa xã hội khoa học",
			"chủ nghĩa xã hội không tưởng",
		],
		correct: 2,
		explanation: "Dựa trên Trang 3 (Lời nói đầu) của chương 1 của tài liệu, chỉ ra rằng Chương trình các môn Lý luận chính trị gồm Triết học Mác-Lênin, Kinh tế chính trị Mác-Lênin, Chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Thành phần nào dưới đây KHÔNG phải là một trong ba bộ phận cấu thành của chủ nghĩa Mác - Lênin?",
		answers: [
			"Triết học Mác – Lênin",
			"Kinh tế chính trị Mác - Lênin",
			"Chủ nghĩa xã hội khoa học",
			"Chủ nghĩa xã hội không tưởng",
		],
		correct: 3,
		explanation: "Dựa trên Trang 3 (Lời nói đầu) của chương 1 của tài liệu, chỉ ra rằng ba bộ phận hợp thành chủ nghĩa Mác - Lênin là Triết học, Kinh tế chính trị và Chủ nghĩa xã hội khoa học, không bao gồm chủ nghĩa xã hội không tưởng.",
	},
	{
		question: "Trong phương thức sản xuất tư bản chủ nghĩa, mâu thuẫn trong lĩnh vực kinh tế là mâu thuẫn giữa...",
		answers: [
			"LLSX mang tính xã hội hóa với QHSX mang tính xã hội tư bản chủ nghĩa",
			"LLSX mang tính cá nhân với QHSX mang tính xã hội tư bản chủ nghĩa",
			"LLSX mang tính xã hội hóa với QHSX mang tính tư nhân tư bản chủ nghĩa",
			"LLSX mang tính cá nhân với QHSX mang tính tư nhân tư bản chủ nghĩa",
		],
		correct: 2,
		explanation: "Dựa trên Trang 37 của chương 3 của tài liệu (liên kết kiến thức), chỉ ra rằng Mâu thuẫn giữa tính chất xã hội hóa của lực lượng sản xuất với chế độ chiếm hữu tư nhân tư bản chủ nghĩa đối với tư liệu sản xuất trở thành mâu thuẫn kinh tế cơ bản của chủ nghĩa tư bản.",
	},
	{
		question: "Chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Là hệ thống lý luận luận giải từ góc độ chính trị - xã hội bước chuyển từ HTKT-XH TBCN sang HTKT-XH CSCN",
			"Là hệ thống lý luận luận giải từ góc độ chính trị - xã hội bước chuyển từ XHPK sang XHTBCN",
			"Là hệ thống lý luận luận giải từ góc độ kinh tế sự ra đời của HTKT-XH tư bản chủ nghĩa",
			"Là hệ thống lý luận luận giải từ góc độ kinh tế sự ra đời của HTKT-XH cộng sản chủ nghĩa",
		],
		correct: 0,
		explanation: "Dựa trên Trang 19 của chương 1 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội khoa học luận giải một cách khoa học về phương hướng và những nguyên tắc... nhằm hiện thực hóa sự chuyển biến từ chủ nghĩa tư bản lên chủ nghĩa xã hội và chủ nghĩa cộng sản.",
	},
	{
		question: "Những nhà chủ nghĩa xã hội không tưởng nào đã KHÔNG luận chứng được một cách khoa học về bản chất và quy luật phát triển của chủ nghĩa tư bản?",
		answers: [
			"A.Xmit và Đ. Ricácđô",
			"H.Xanh Ximông, S. Phuriê và R. Ôoen",
			"C. Mác và Ph. Ăngghen",
			"V.I. Lênin",
		],
		correct: 1,
		explanation: "Dựa trên Trang 5 của chương 1 của tài liệu, chỉ ra rằng Chủ nghĩa không tưởng phê phán mà đại biểu là H.Xanh Ximông, S.Phuriê và R.Oen có hạn chế là: Thứ nhất, không phát hiện ra được quy luật vận động và phát triển của xã hội loài người nói chung; bản chất, quy luật vận động, phát triển của chủ nghĩa tư bản nói riêng.",
	},
	{
		question: "Chỉ ra luận điểm đúng sau đây?",
		answers: [
			"Chủ nghĩa xã hội khoa học là một trong ba bộ phận cấu thành của chủ nghĩa Mác",
			"Chủ nghĩa xã hội khoa học là một trong ba xu hướng của chủ nghĩa Mác",
			"Chủ nghĩa xã hội khoa học là một trong ba tiền đề tư tưởng của chủ nghĩa Mác",
			"Chủ nghĩa xã hội khoa học là một trong ba nguồn gốc hình thành chủ nghĩa Mác",
		],
		correct: 0,
		explanation: "Dựa trên Trang 3 (Lời nói đầu) của chương 1 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội khoa học cùng với Triết học và Kinh tế chính trị học tạo thành ba bộ phận của học thuyết Mác.",
	},
	{
		question: "Trong phương thức sản xuất tư bản chủ nghĩa, mâu thuẫn sâu sắc giữa lực lượng sản xuất với quan hệ sản xuất bộc lộ qua cuộc khủng hoảng kinh tế lần thứ nhất vào năm...",
		answers: [
			"1824",
			"1825",
			"1826",
			"1827",
		],
		correct: 1,
		explanation: "Dựa trên quá trình hình thành Chủ nghĩa xã hội khoa học của chương 1 của tài liệu, chỉ ra rằng cuộc khủng hoảng kinh tế đầu tiên của phương thức sản xuất tư bản chủ nghĩa nổ ra vào năm 1825, làm bộc lộ rõ mâu thuẫn cơ bản của nó.",
	},
	{
		question: "Thành phần nào dưới đây KHÔNG phải là một trong ba phát kiến vĩ đại của chủ nghĩa Mác — Lênin?",
		answers: [
			"Chủ nghĩa duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Chủ nghĩa duy vật biện chứng",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 2,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Ba phát kiến vĩ đại của C.Mác và Ph.Ăngghen gồm: Chủ nghĩa duy vật lịch sử, Học thuyết về giá trị thặng dư và Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân. (Không liệt kê Chủ nghĩa duy vật biện chứng như một phát kiến riêng trong 3 phát kiến này).",
	},
	{
		question: "Nội dung nào dưới đây là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong triết học Mác - Lênin?",
		answers: [
			"Chủ nghĩa duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Chủ nghĩa duy vật biện chứng",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Bằng phép biện chứng duy vật, nghiên cứu chủ nghĩa tư bản, C.Mác và Ph.Ăngghen đã sáng lập chủ nghĩa duy vật lịch sử - phát kiến vĩ đại thứ nhất.",
	},
	{
		question: "Một trong những hạn chế của chủ nghĩa xã hội không tưởng Anh và Pháp là:",
		answers: [
			"Không thấy được tính lịch sử của giá trị",
			"Không phân tích được một cách chính xác những biểu hiện của giá trị trong phương thức sản xuất tư bản chủ nghĩa",
			"Không luận chứng được một cách khoa học về bản chất của CNTB và quy luật phát triển của CNTB",
			"Tìm ra sứ mệnh lịch sử của giai cấp công nhân",
		],
		correct: 2,
		explanation: "Dựa trên Trang 5 của chương 1 của tài liệu, chỉ ra rằng Hạn chế: Thứ nhất, không phát hiện ra được quy luật vận động và phát triển của xã hội loài người nói chung; bản chất, quy luật vận động, phát triển của chủ nghĩa tư bản nói riêng.",
	},
	{
		question: "Phong trào đấu tranh của giai cấp vô sản vào những năm 30, 40 của thế kỷ XIX chứng tỏ rằng...",
		answers: [
			"Giai cấp tư sản là một lực lượng chính trị độc lập",
			"Giai cấp vô sản là một lực lượng chính trị xã hội độc lập",
			"Phong trào vô sản là một phong trào tự giác",
			"Giai cấp vô sản cần liên minh với địa chủ, phong kiến chống tư sản",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng trong Điều kiện kinh tế - xã hội, giai cấp công nhân đã bước lên vũ đài chính trị, trở thành một lực lượng chính trị xã hội độc lập.",
	},
	{
		question: "Ba nguồn gốc lý luận trực tiếp hình thành chủ nghĩa Mác là?",
		answers: [
			"Học thuyết giá trị thặng dư, chủ nghĩa duy vật lịch sử, sứ mệnh lịch sử của giai cấp công nhân.",
			"Triết học cổ điển Đức, kinh tế chính trị học Anh và chủ nghĩa xã hội không tưởng Pháp",
			"Thuyết tiến hóa, Định luật bảo toàn và chuyển hóa năng lượng và Thuyết tế bào",
			"Triết học, kinh tế chính trị học và chủ nghĩa xã hội khoa học",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Sơ đồ nguồn gốc lý luận bao gồm: Triết học Cổ điển Đức, Kinh tế chính trị cổ điển Anh, CNXH không tưởng Pháp.",
	},
	{
		question: "Chọn cụm từ dưới đây điền vào chỗ trống (...) để hoàn thiện luận điểm sau: Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là những quy luật (...) của quá trình hình thành, phát triển hình thái kinh tế xã hội cộng sản chủ nghĩa?",
		answers: [
			"Chính trị - xã hội",
			"Kinh tế - xã hội",
			"Văn hóa - xã hội",
			"Tư tưởng - xã hội",
		],
		correct: 0,
		explanation: "Dựa trên Trang 19 của chương 1 của tài liệu, chỉ ra rằng đối tượng nghiên cứu của Chủ nghĩa xã hội khoa học: những qui luật, tính qui luật chính trị - xã hội của quá trình phát sinh, hình thành và phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa.",
	},
	{
		question: "Nội dung nào dưới đây là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong kinh tế chính trị Mác - Lênin?",
		answers: [
			"Chủ nghĩa duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Chủ nghĩa duy vật biện chứng",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về giá trị thặng dư: Đây là phát kiến vĩ đại thứ hai của C.Mác và Ph.Ăngghen, khẳng định về phương diện kinh tế sự diệt vong không tránh khỏi của chủ nghĩa tư bản.",
	},
	{
		question: "Nội dung nào dưới đây là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong CNXHKH?",
		answers: [
			"Chủ nghĩa duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Chủ nghĩa duy vật biện chứng",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 3,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân là phát kiến vĩ đại thứ ba... những hạn chế có tính lịch sử của chủ nghĩa xã hội không tưởng - phê phán đã được khắc phục một cách triệt để.",
	},
	{
		question: "Quy luật chính trị - xã hội phản ánh quan hệ nào sau đây?",
		answers: [
			"Quan hệ giữa các thiết chế văn hóa",
			"Quan hệ giữa các giai cấp, tầng lớp trong xã hội",
			"Quan hệ giữa các cộng đồng dân cư trong xã hội",
			"Quan hệ giữa các tổ chức trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên Trang 19 của chương 1 của tài liệu, chỉ ra rằng những quy luật, tính quy luật chính trị - xã hội gắn liền với hoạt động và quan hệ giai cấp, con đường đấu tranh cách mạng của giai cấp công nhân và nhân dân lao động.",
	},
	{
		question: "Điền vào chỗ trống để hoàn thiện luận điểm của V.I. Lênin: “Điểm chủ yếu trong học thuyết của Mác là ở chỗ nó làm sáng rõ vai trò lịch sử thế giới của (...) là người xây dựng xã hội xã hội chủ nghĩa”.",
		answers: [
			"Giai cấp vô sản",
			"Giai cấp tư sản",
			"Tầng lớp trí thức",
			"Tầng lớp doanh nhân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 10 của chương 1 của tài liệu, chỉ ra rằng Đánh giá về chủ nghĩa Mác, V.I.Lênin nhấn mạnh điểm chủ yếu là làm sáng tỏ vai trò (sứ mệnh lịch sử) của giai cấp vô sản (công nhân).",
	},
	{
		question: "CNDV lịch sử là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong …?",
		answers: [
			"Triết học Mác – Lênin",
			"Kinh tế chính trị Mác - Lênin",
			"Chủ nghĩa xã hội khoa học",
			"Chủ nghĩa xã hội hiện thực",
		],
		correct: 0,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Chủ nghĩa duy vật lịch sử là phát kiến vĩ đại thứ nhất, được sáng lập bằng phép biện chứng duy vật (thuộc lĩnh vực Triết học).",
	},
	{
		question: "Học thuyết giá trị thặng dư là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong …?",
		answers: [
			"Triết học Mác — Lênin",
			"Kinh tế chính trị Mác - Lênin",
			"Chủ nghĩa xã hội khoa học",
			"Chủ nghĩa xã hội hiện thực",
		],
		correct: 1,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về giá trị thặng dư... khẳng định về phương diện kinh tế sự diệt vong (tức là đóng góp trong lĩnh vực kinh tế chính trị).",
	},
	{
		question: "Phong trào đấu tranh nào sau đây là một trong những điều kiện ra đời của chủ nghĩa Mác?",
		answers: [
			"Phong trào Hiến chương ở Anh",
			"Công xã Pari",
			"Cách mạng Tháng Mười Nga",
			"Cách mạng Tháng Tám ở Việt Nam",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng điều kiện kinh tế - xã hội Tây Âu giữa thế kỷ XIX đi liền với các phong trào đấu tranh của giai cấp công nhân bước lên vũ đài chính trị (như phong trào Hiến chương Anh).",
	},
	{
		question: "Mảnh đất hiện thực để chủ nghĩa xã hội khoa học ra đời là gì?",
		answers: [
			"Sự phát triển kinh tế - xã hội, khoa học - kỹ thuật, văn hóa tư tưởng ở châu Âu những năm 40 của thế kỷ XVIII",
			"Sự phát triển kinh tế - xã hội, khoa học kỹ thuật, văn hóa tư tưởng ở châu Âu những năm 40 của thế kỷ XIX",
			"Sự phát triển kinh tế - xã hội, khoa học - kỹ thuật, văn hóa tư tưởng ở châu Âu những năm 40 của thế kỷ XX",
			"Sự phát triển kinh tế - xã hội, khoa học - kỹ thuật, văn hóa tư tưởng ở châu Âu những năm cuối của thế kỷ XX",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng sơ đồ Điều kiện tiền đề ra đời CNXHKH ghi rõ: Điều kiện KT-XH Tây Âu giữa thế kỷ XIX.",
	},
	{
		question: "Tiền đề lý luận trực tiếp ra đời chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Chủ nghĩa duy vật lịch sử và chủ nghĩa duy vật biện chứng",
			"Chủ nghĩa duy tâm khách quan và chủ nghĩa duy tâm chủ quan",
			"Chủ nghĩa duy vật siêu hình",
			"Chủ nghĩa xã hội không tưởng Pháp",
		],
		correct: 3,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng trong sơ đồ Nguồn gốc lý luận, Chủ nghĩa xã hội không tưởng Pháp đóng vai trò là một trong những tiền đề lý luận trực tiếp.",
	},
	{
		question: "Vai trò của C. Mác và Ph. Ăngghen đối với chủ nghĩa xã hội được biểu hiện như thế nào?",
		answers: [
			"Đưa chủ nghĩa xã hội từ không tưởng trở thành khoa học",
			"Đưa chủ nghĩa xã hội từ lý luận thành hiện thực",
			"Đưa chủ nghĩa xã hội hiện thực từ một nước trở thành hệ thống",
			"Đưa chủ nghĩa xã hội từ Đức sang Anh",
		],
		correct: 0,
		explanation: "Dựa trên Trang 7 và 8 của chương 1 của tài liệu, chỉ ra rằng với 3 phát kiến vĩ đại và Tuyên ngôn của Đảng Cộng sản, C.Mác và Ph.Ăngghen đã đưa chủ nghĩa xã hội từ không tưởng trở thành khoa học.",
	},
	{
		question: "Hạn chế lớn nhất của chủ nghĩa xã hội không tưởng Anh và Pháp cuối thế kỷ XVIII đầu thế kỷ XIX là không phát hiện ra sứ mệnh lịch sử của giai cấp…",
		answers: [
			"Nông dân",
			"Công nhân",
			"Tư sản",
			"Địa chủ",
		],
		correct: 1,
		explanation: "Dựa trên Trang 5 của chương 1 của tài liệu, chỉ ra rằng Hạn chế: Thứ hai, không phát hiện ra lực lượng xã hội tiên phong có thể thực hiện cuộc chuyển biến cách mạng... - giai cấp công nhân.",
	},
	{
		question: "Học thuyết sứ mệnh lịch sử của GCCN là phát kiến vĩ đại của C. Mác và Ph. Ăngghen trong …?",
		answers: [
			"Triết học Mác — Lênin",
			"Kinh tế chính trị Mác - Lênin",
			"Chủ nghĩa xã hội khoa học",
			"Chủ nghĩa xã hội hiện thực",
		],
		correct: 2,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân... là phát kiến vĩ đại thứ ba, cấu thành cốt lõi của Chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Vai trò của V.I. Lênin đối với chủ nghĩa xã hội biểu hiện như thế nào?",
		answers: [
			"Đưa chủ nghĩa xã hội từ khoa học, từ lý luận thành hiện thực",
			"Đưa chủ nghĩa xã hội từ một nước trở thành hệ thống",
			"Đưa chủ nghĩa xã hội từ không tưởng thành khoa học",
			"Đưa chủ nghĩa xã hội từ phương Tây sang phương Đông",
		],
		correct: 0,
		explanation: "Dựa trên Trang 10 của chương 1 của tài liệu, chỉ ra rằng công lao của V.I.Lênin là đã biến chủ nghĩa xã hội từ khoa học, từ lý luận thành hiện thực, được đánh dấu bằng sự ra đời của Nhà nước xã hội chủ nghĩa đầu tiên trên thế giới - Nhà nước Xô viết, năm 1917.",
	},
	{
		question: "Phạm trù trung tâm và xuất phát của chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Phạm trù sứ mệnh lịch sử của giai cấp công nhân",
			"Phạm trù sứ mệnh lịch sử của giai cấp nông dân",
			"Phạm trù sứ mệnh lịch sử của giai cấp tư sản",
			"Phạm trù sứ mệnh lịch sử của giai cấp chủ nô",
		],
		correct: 0,
		explanation: "Dựa trên Trang 21 (Chương 2, nhưng là hệ quả trực tiếp từ kiến thức nền của chương 1) của tài liệu, chỉ ra rằng Sứ mệnh lịch sử thế giới của giai cấp công nhân là nội dung chủ yếu, điểm căn bản của chủ nghĩa Mác - Lênin, là phạm trù trung tâm, nguyên lý xuất phát của chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Vai trò của C. Mác gắn liền với tổ chức nào?",
		answers: [
			"Tổ chức Quốc tế 1",
			"Tổ chức Quốc tế 2",
			"Tổ chức Quốc tế 3",
			"Tổ chức Quốc tế 4",
		],
		correct: 0,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng Đây là thời kỳ diễn ra rất nhiều các sự kiện...: Quốc tế I thành lập (1864) gắn với vai trò của C.Mác.",
	},
	{
		question: "Nội dung nào dưới đây KHÔNG phải là điều kiện kinh tế - xã hội cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Cách mạng công nghiệp tạo ra sự phát triển mạnh mẽ cho nền công nghiệp hiện đại",
			"Mâu thuẫn giữa LLSX mang tính XHH với QHSX dựa trên chế độ chiếm hữu tư nhân TBCN",
			"Mâu thuẫn giữa GCCN và GCTS",
			"Triết học cổ điển Đức",
		],
		correct: 3,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Sơ đồ phân chia rạch ròi Điều kiện KT-XH Tây Âu và Nguồn gốc lý luận. Triết học Cổ điển Đức thuộc Nguồn gốc lý luận, không phải điều kiện KT-XH.",
	},
	{
		question: "Phong trào đấu tranh nào dưới đây KHÔNG phải là điều kiện kinh tế - xã hội cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Phong trào công nhân dệt ở thành phố Lion",
			"Phong trào công nhân ở Nga",
			"Phong trào Hiến chương của người lao động ở Anh",
			"Phong trào công nhân dệt ở thành phố Lyon",
		],
		correct: 1,
		explanation: "Dựa trên bối cảnh Tây Âu giữa thế kỷ XIX tại Trang 6 của chương 1 của tài liệu, chỉ ra rằng điều kiện KT-XH xuất phát từ các nước tư bản Tây Âu phát triển sớm (Anh, Pháp, Đức), chưa bao gồm phong trào công nhân ở Nga lúc bấy giờ.",
	},
	{
		question: "Tác phẩm nào đánh dấu sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Hệ tư tưởng Đức",
			"Tuyên ngôn của Đảng Cộng sản",
			"Phê phán Cương lĩnh Gôta",
			"Tình cảnh giai cấp lao động Anh",
		],
		correct: 1,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng Tác phẩm Tuyên ngôn của Đảng Cộng sản do C.Mác và Ph.Ăngghen soạn thảo (2/1848), đánh dấu sự ra đời của chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Nội dung nào dưới đây là tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Định luật chuyển động Newton",
			"Thuyết Hoài nghi",
			"Định luật hấp dẫn",
			"Học thuyết Tế bào",
		],
		correct: 3,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Tiền đề khoa học tự nhiên bao gồm: Học thuyết tiến hóa, Học thuyết tế bào, Định luật bảo toàn và chuyển hóa năng lượng.",
	},
	{
		question: "Tác phẩm nào là cương lĩnh chính trị đầu tiên của giai cấp công nhân?",
		answers: [
			"Tuyên ngôn của Đảng Cộng sản",
			"Phê phán Cương lĩnh Gôta",
			"Hệ tư tưởng Đức",
			"Tư Bản",
		],
		correct: 0,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng Tuyên ngôn của Đảng Cộng sản là cương lĩnh chính trị, kim chỉ nam hành động của toàn bộ phong trào cộng sản và công nhân quốc tế.",
	},
	{
		question: "Điền vào chỗ trống để hoàn thiện luận điểm của V.I. Lênin: “Học thuyết của Mác là học thuyết (...) vì nó là một học thuyết chính xác”.",
		answers: [
			"Vạn năng",
			"Khoa học",
			"Cách mạng",
			"Tiến bộ",
		],
		correct: 0,
		explanation: "Dựa trên Trang 10 của chương 1 của tài liệu, chỉ ra rằng Đánh giá về chủ nghĩa Mác, V.I.Lênin chỉ rõ: 'Học thuyết của Mác là học thuyết vạn năng vì nó là một học thuyết chính xác'.",
	},
	{
		question: "Nội dung nào dưới đây là tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Định luật chuyển động Newton",
			"Định luật quán tính",
			"Định luật bảo toàn và chuyển hoá năng lượng",
			"Định luật hấp dẫn",
		],
		correct: 2,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Tiền đề khoa học tự nhiên bao gồm: Học thuyết tiến hóa, Học thuyết tế bào, Định luật bảo toàn và chuyển hóa năng lượng.",
	},
	{
		question: "Chọn phương án đúng nhất: Chủ nghĩa Mác - Lênin được cấu thành từ ba bộ phận lý luận cơ bản là:",
		answers: [
			"Chủ nghĩa xã hội không tưởng, Triết học Mác - Lênin, Kinh tế chính trị học Mác - Lênin",
			"Triết học Mác - Lênin, Kinh tế chính trị học Mác - Lênin, Chủ nghĩa xã hội khoa học",
			"Kinh tế chính trị học, Chủ nghĩa xã hội không tưởng, Triết học Mác – Lênin",
			"Triết học cổ điển Đức, Kinh tế học chính trị cổ điển Anh, Chủ nghĩa xã hội không tưởng Pháp",
		],
		correct: 1,
		explanation: "Dựa trên Trang 3 của chương 1 của tài liệu, chỉ ra rằng ba môn học/bộ phận cơ bản hợp thành là Triết học Mác-Lênin, Kinh tế chính trị Mác-Lênin, Chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là…",
		answers: [
			"Xây dựng lý luận về đảng kiểu mới của giai cấp công nhân",
			"Xây dựng lý luận về đảng kiểu mới của giai cấp nông dân",
			"Xây dựng lý luận về đảng của nhiều giai cấp, tầng lớp trong xã hội",
			"Xây dựng lý luận về đảng của các dân tộc thuộc địa và phụ thuộc",
		],
		correct: 0,
		explanation: "Dựa trên Trang 11 của chương 1 của tài liệu, chỉ ra rằng V.I.Lênin đã xây dựng lý luận về đảng cách mạng kiểu mới của giai cấp công nhân, về các nguyên tắc tổ chức, cương lĩnh, sách lược...",
	},
	{
		question: "Nội dung nào dưới đây là tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Học thuyết tiến hoá của Darwin",
			"Triết học cổ điển Đức",
			"Kinh tế chính trị cổ điển Anh",
			"Chủ nghĩa xã hội không tưởng Pháp",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Tiền đề khoa học tự nhiên bao gồm: Học thuyết tiến hóa, Học thuyết tế bào, Định luật bảo toàn và chuyển hóa năng lượng.",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Xây dựng lý luận về cách mạng dân chủ kiểu mới",
			"Xây dựng lý luận về cách mạng dân tộc kiểu mới",
			"Xây dựng lý luận về cách mạng phong kiến kiểu mới",
			"Xây dựng lý luận về cách mạng công nghệ",
		],
		correct: 0,
		explanation: "Dựa trên Trang 11 của chương 1 của tài liệu, chỉ ra rằng V.I.Lênin đã hoàn chỉnh lý luận về cách mạng xã hội chủ nghĩa và chuyên chính vô sản, cách mạng dân chủ tư sản kiểu mới và các điều kiện tất yếu cho sự chuyển biến...",
	},
	{
		question: "Chọn phương án đúng nhất: Giai đoạn hình thành và phát triển chủ nghĩa Mác do ai thực hiện?",
		answers: [
			"C. Mác",
			"C. Mác và Ph. Ăngghen",
			"V.I. Lênin",
			"C. Mác, Ph. Ăngghen và V.I. Lênin",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6-9 của chương 1 của tài liệu, chỉ ra rằng Giai đoạn phát triển cơ bản của CNXHKH chia làm thời kỳ hình thành do C.Mác và Ph.Ăngghen phát triển.",
	},
	{
		question: "Chọn phương án đúng nhất: Giai đoạn bảo vệ và phát triển chủ nghĩa Mác thành chủ nghĩa Mác - Lênin do ai thực hiện?",
		answers: [
			"C. Mác",
			"C. Mác và Ph. Ăngghen",
			"V.I. Lênin",
			"C. Mác, Ph. Ăngghen và V.I. Lênin",
		],
		correct: 2,
		explanation: "Dựa trên Trang 10 của chương 1 của tài liệu, chỉ ra rằng V.I.Lênin vận dụng và phát triển chủ nghĩa xã hội khoa học trong điều kiện mới (giai đoạn chủ nghĩa đế quốc).",
	},
	{
		question: "Nội dung nào dưới đây KHÔNG phải là tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Định luật bảo toàn và chuyển hoá năng lượng",
			"Thuyết tương đối",
			"Học thuyết tiến hoá",
			"Học thuyết tế bào",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Tiền đề khoa học tự nhiên gồm 3 phát minh: Thuyết tiến hoá, Định luật bảo toàn năng lượng, Thuyết tế bào. Thuyết tương đối không nằm trong số này.",
	},
	{
		question: "V.I. Lênin là người sáng lập tổ chức nào?",
		answers: [
			"Đồng minh những người cộng sản",
			"Quốc tế 1",
			"Quốc tế 2",
			"Quốc tế 3 (Quốc tế cộng sản)",
		],
		correct: 3,
		explanation: "Dựa trên kiến thức lịch sử phong trào cộng sản trong chương 1 của tài liệu, V.I.Lênin đóng vai trò nòng cốt gắn với Quốc tế 3 (Quốc tế cộng sản). (Lưu ý: Đáp án Ngân hàng ghi A nhưng theo logic tài liệu Lênin lãnh đạo Nhà nước Xô viết và Quốc tế 3).",
	},
	{
		question: "Điền vào chỗ trống để hoàn thiện khẩu hiệu của V.I. Lênin: “Vô sản tất cả các nước, các (...) bị áp bức đoàn kết lại”.",
		answers: [
			"Dân tộc",
			"Giai cấp",
			"Tổ chức",
			"Tầng lớp",
		],
		correct: 0,
		explanation: "Dựa trên lý luận về vấn đề dân tộc trong thời đại đế quốc chủ nghĩa được mở rộng bởi V.I.Lênin (Chương 1 và Chương 6), chỉ ra rằng Lênin đã bổ sung khẩu hiệu: 'Vô sản tất cả các nước và các dân tộc bị áp bức, đoàn kết lại'.",
	},
	{
		question: "Nội dung nào dưới đây là tiền đề tư tưởng lí luận cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Triết học hiện sinh",
			"Học thuyết tiến hoá của Darwin",
			"Phật giáo",
			"Kinh tế chính trị cổ điển Anh",
		],
		correct: 3,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Nguồn gốc lý luận (tiền đề tư tưởng) bao gồm Triết học Cổ điển Đức, Kinh tế chính trị cổ điển Anh, CNXH không tưởng Pháp.",
	},
	{
		question: "Cuộc cách mạng công nghiệp lần thứ nhất trong phương thức sản xuất TBCN diễn ra đầu tiên ở quốc gia nào?",
		answers: [
			"Anh",
			"Pháp",
			"Đức",
			"Nga",
		],
		correct: 0,
		explanation: "Dựa trên bối cảnh Điều kiện KT-XH Tây Âu (Chương 1), chỉ ra rằng cuộc cách mạng công nghiệp lần thứ nhất phát triển mạnh mẽ nhất bắt đầu từ nước Anh làm tiền đề cho sự phát triển của nền đại công nghiệp.",
	},
	{
		question: "Nội dung nào dưới đây là một tiền đề tư tưởng lí luận cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Triết học Hy lạp",
			"Học thuyết tiến hoá của Darwin",
			"Chủ nghĩa xã hội không tưởng Pháp",
			"Chủ nghĩa duy vật chất phác",
		],
		correct: 2,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng trong sơ đồ Nguồn gốc lý luận, Chủ nghĩa xã hội không tưởng Pháp là một trong ba nguồn gốc.",
	},
	{
		question: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là…",
		answers: [
			"Những quy luật kinh tế của sự ra đời phương thức sản xuất cộng sản chủ nghĩa",
			"Những quy luật tự nhiên của quá trình cách mạng xã hội chủ nghĩa",
			"Những quy luật vận động, phát triển chung nhất của tự nhiên, xã hội và tư duy",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 3,
		explanation: "Dựa trên Trang 19 của chương 1 của tài liệu, chỉ ra rằng đối tượng nghiên cứu của Chủ nghĩa xã hội khoa học là những qui luật, tính qui luật chính trị - xã hội của quá trình phát sinh, hình thành và phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa. Vì vậy các phương án A, B, C đều mô tả sai đối tượng (kinh tế, tự nhiên, hay chung nhất của triết học).",
	},
	{
		question: "Tác phẩm thể hiện rõ sự chuyển biến tư tưởng của Ph. Ăngghen từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa?",
		answers: [
			"Bộ Tư bản",
			"Góp phần phê phán Triết học pháp quyền của Hêghen - Lời nói đầu",
			"Bản thảo kinh tế triết học năm 1844",
			"Lược khảo khoa kinh tế chính trị",
		],
		correct: 3,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng 'Đối với Ph.Ăngghen, với tác phẩm Tình cảnh nước Anh; Lược khảo khoa kinh tế - chính trị (năm 1843), đánh dấu cho sự chuyển biến từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa'.",
	},
	{
		question: "Một trong những đóng góp quan trọng của Đảng Cộng sản Việt Nam vào lý luận của chủ nghĩa xã hội khoa học là…",
		answers: [
			"Tư tưởng độc lập dân tộc gắn liền với chủ nghĩa xã hội",
			"Tư tưởng dân chủ",
			"Tư tưởng nhân văn",
			"Tư tưởng hòa bình",
		],
		correct: 0,
		explanation: "Dựa trên Trang 16 của chương 1 của tài liệu, chỉ ra rằng những đóng góp to lớn vào kho tàng lý luận của chủ nghĩa Mác - Lênin nói chung, Chủ nghĩa xã hội khoa học nói riêng: 'Độc lập dân tộc gắn liền với chủ nghĩa xã hội là quy luật của cách mạng Việt Nam, trong điều kiện thời đại ngày nay'.",
	},
	{
		question: "Điền từ vào chỗ trống: Cách mạng Tháng Mười Nga năm 1917 thành công đã mở ra một thời đại mới thời kỳ quá độ từ [...] trên phạm vi quốc tế.",
		answers: [
			"Chủ nghĩa tư bản lên chủ nghĩa xã hội",
			"Phong kiến lên chủ nghĩa tư bản",
			"Thực dân, phong kiến lên chủ nghĩa xã hội",
			"Chủ nghĩa xã hội lên chủ nghĩa cộng sản",
		],
		correct: 0,
		explanation: "Dựa trên Trang 10 của chương 1 của tài liệu, chỉ ra rằng V.I.Lênin tiếp tục bảo vệ, vận dụng và phát triển... 'Thời đại tan rã chủ nghĩa tư bản, sự sụp đổ trong nội bộ chủ nghĩa tư bản, thời đại cách mạng cộng sản của giai cấp vô sản'; mở ra thời đại Quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội.",
	},
	{
		question: "Nội dung nào dưới đây là một tiền đề tư tưởng lí luận cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Triết học cổ điển Đức",
			"Triết học Tây Âu trung cổ",
			"Triết học hiện sinh",
			"Triết học phương Tây hiện đại",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Nguồn gốc lý luận bao gồm Triết học cổ điển Đức.",
	},
	{
		question: "Nội dung nào dưới đây KHÔNG phải là tiền đề tư tưởng lí luận cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Chủ nghĩa xã hội không tưởng Pháp",
			"Triết học cổ điển Đức",
			"Thuyết tương đối",
			"Kinh tế chính trị cổ điển Anh",
		],
		correct: 2,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng sơ đồ Nguồn gốc lý luận (tiền đề tư tưởng) chỉ gồm 3 bộ phận: Triết học cổ điển Đức, Kinh tế chính trị cổ điển Anh, CNXH không tưởng Pháp. Thuyết tương đối không nằm trong số này.",
	},
	{
		question: "Phong trào đấu tranh nào sau đây là một trong những điều kiện ra đời của chủ nghĩa Mác?",
		answers: [
			"Cách mạng tư sản Anh",
			"Công xã Pari",
			"Cách mạng Tháng Mười Nga",
			"Cuộc khởi nghĩa của công nhân dệt Lion (Pháp)",
		],
		correct: 3,
		explanation: "Dựa trên bối cảnh ra đời (Chương 1), chỉ ra rằng sự phát triển của giai cấp công nhân với các cuộc đấu tranh tiêu biểu (như công nhân dệt Lion ở Pháp, phong trào Hiến chương Anh) là mảnh đất hiện thực và điều kiện ra đời chủ nghĩa Mác.",
	},
	{
		question: "Nội dung nào dưới đây KHÔNG phải là tiền đề tư tưởng lí luận cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Định luật chuyển động Newton",
			"Triết học cổ điển Đức",
			"Chủ nghĩa xã hội không tưởng Pháp",
			"Kinh tế chính trị cổ điển Anh",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng Nguồn gốc lý luận gồm Triết học cổ điển Đức, Kinh tế chính trị cổ điển Anh, CNXH không tưởng Pháp. Định luật chuyển động Newton không thuộc tiền đề tư tưởng.",
	},
	{
		question: "Một trong những tiền đề quan trọng cho bước chuyển biến tư tưởng của C. Mác và Ph. Ăngghen từ thế giới quan duy tâm sang thế giới quan duy vật là…",
		answers: [
			"Phép biện chứng của G.W.Ph. Hêghen",
			"Chủ nghĩa duy vật vô thần của L. Phoiơbắc",
			"Tư tưởng kinh tế của A. Xmít",
			"Tư tưởng xã hội chủ nghĩa của H. Xanh Ximông",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng C.Mác và Ph.Ăngghen đã kế thừa 'cái hạt nhân hợp lý' của Hêghen và quan điểm thấm nhuần duy vật của L.Phoiơbắc để xây dựng chủ nghĩa duy vật biện chứng, tạo bước chuyển biến lập trường.",
	},
	{
		question: "Tác phẩm thể hiện rõ sự chuyển biến tư tưởng của C. Mác từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa?",
		answers: [
			"Tình cảnh nước Anh",
			"Góp phần phê phán triết học pháp quyền của Hêghen — Lời nói đầu",
			"Lược khảo khoa kinh tế - chính trị",
			"Bộ Tư bản",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng 'Với C.Mác, tác phẩm “Góp phần phê phán triết học pháp quyền của Hêghen - Lời nói đầu (1844)”... đánh dấu sự chuyển biến từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa'.",
	},
	{
		question: "Tác phẩm thể hiện rõ sự chuyển biến tư tưởng của Ph. Ăngghen từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa?",
		answers: [
			"Tình cảnh nước Anh",
			"Góp phần phê phán Triết học pháp quyền của Hêghen — Lời nói đầu",
			"Bản thảo kinh tế triết học năm 1844",
			"Bộ Tư bản",
		],
		correct: 0,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng 'Đối với Ph.Ăngghen, với tác phẩm Tình cảnh nước Anh... đánh dấu cho sự chuyển biến từ thế giới quan duy tâm sang thế giới quan duy vật từ lập trường dân chủ cách mạng sang lập trường cộng sản'.",
	},
	{
		question: "Từ 1843 đến 1848, C. Mác và Ph. Ăngghen cho ra đời nhiều tác phẩm lớn, đánh dấu sự chuyển biến tư tưởng…",
		answers: [
			"từ thế giới quan duy vật sang thế giới quan duy tâm, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa",
			"từ thế giới quan duy vật sang thế giới quan duy tâm, từ lập trường cộng sản chủ nghĩa sang lập trường dân chủ cách mạng",
			"từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa",
			"từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường cộng sản chủ nghĩa sang lập trường dân chủ cách mạng",
		],
		correct: 2,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng C.Mác và Ph.Ăngghen đã trải qua sự chuyển biến từ thế giới quan duy tâm sang thế giới quan duy vật, từ lập trường dân chủ cách mạng sang lập trường cộng sản chủ nghĩa trong giai đoạn này.",
	},
	{
		question: "Học thuyết nào dưới đây của C. Mác và Ph. Ăngghen có nội dung cơ bản là lí luận về hình thái kinh tế - xã hội, về mặt triết học nghiên cứu xã hội, là cơ sở khẳng định sự sụp đổ của chủ nghĩa tư bản và thắng lợi của chủ nghĩa xã hội, chủ nghĩa cộng sản là tất yếu như nhau?",
		answers: [
			"Học thuyết duy vật biện chứng",
			"Học thuyết duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng 'Chủ nghĩa duy vật lịch sử khẳng định sự phát triển lịch sử của xã hội loài người là một quá trình lịch sử tự nhiên, tuân theo quy luật khách quan' (là cơ sở triết học phân tích sự vận động của hình thái kinh tế - xã hội).",
	},
	{
		question: "Học thuyết nào dưới đây của C. Mác và Ph. Ăngghen đi sâu nghiên cứu chủ nghĩa tư bản, đã chứng minh một cách khoa học về loại “hàng hoá đặc biệt”, hàng hoá sức lao động của công nhân mà nhà tư bản đã mua và có những hành vi để chiếm đoạt giá trị mới do nó sinh ra?",
		answers: [
			"Học thuyết duy vật biện chứng",
			"Học thuyết duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 2,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng 'Học thuyết về giá trị thặng dư... khẳng định về phương diện kinh tế sự diệt vong không tránh khỏi của chủ nghĩa tư bản', thông qua việc phân tích bóc lột sức lao động tạo ra giá trị thặng dư.",
	},
	{
		question: "Học thuyết nào dưới đây của C. Mác và Ph. Ăngghen đã khắc phục một cách triệt để những hạn chế có tính lịch sử của chủ nghĩa xã hội không tưởng; luận chứng sâu sắc về bản chất trên phương diện chính trị - xã hội của sự diệt vong không tránh khỏi của chủ nghĩa tư bản và sự ra đời tất yếu của chủ nghĩa xã hội?",
		answers: [
			"Học thuyết duy vật biện chứng",
			"Học thuyết duy vật lịch sử",
			"Học thuyết giá trị thặng dư",
			"Học thuyết về sứ mệnh lịch sử thế giới của giai cấp công nhân",
		],
		correct: 3,
		explanation: "Dựa trên Trang 7 của chương 1 của tài liệu, chỉ ra rằng 'Học thuyết về sứ mệnh lịch sử toàn thế giới của giai cấp công nhân... Với phát kiến thứ ba này, những hạn chế có tính lịch sử của chủ nghĩa xã hội không tưởng - phê phán đã được khắc phục một cách triệt để'.",
	},
	{
		question: "Tác phẩm nào dưới đây đánh dấu sự ra đời của chủ nghĩa Mác với tư cách là chủ nghĩa xã hội khoa học theo nghĩa rộng?",
		answers: [
			"Tình cảnh giai cấp lao động ở Anh",
			"Những nguyên lí của chủ nghĩa cộng sản",
			"Tuyên ngôn của Đảng Cộng sản",
			"Điều lệ của Đồng minh những người cộng sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng 'Tác phẩm Tuyên ngôn của Đảng Cộng sản do C.Mác và Ph.Ăngghen soạn thảo (2/1848), đánh dấu sự ra đời của chủ nghĩa xã hội khoa học'.",
	},
	{
		question: "Tác phẩm Tuyên ngôn của Đảng Cộng sản ra đời vào…",
		answers: [
			"tháng 2 năm 1842",
			"tháng 2 năm 1848",
			"tháng 8 năm 1842",
			"tháng 8 năm 1848",
		],
		correct: 1,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng 'Tác phẩm Tuyên ngôn của Đảng Cộng sản do C.Mác và Ph.Ăngghen soạn thảo (2/1848)'.",
	},
	{
		question: "Một trong những tiền đề quan trọng cho bước chuyển biến tư tưởng của C. Mác và Ph. Ăngghen từ thế giới quan duy tâm sang thế giới quan duy vật là…",
		answers: [
			"Phép biện chứng của G.W.Ph. Hêghen",
			"Chủ nghĩa duy vật vô thần của L. Phoiơbắc",
			"Tư tưởng kinh tế của A. Xmít",
			"Tư tưởng xã hội chủ nghĩa của H. Xanh Ximông",
		],
		correct: 1,
		explanation: "Dựa trên Trang 6 của chương 1 của tài liệu, chỉ ra rằng C.Mác và Ph.Ăngghen tiếp thu và cải tạo triết học của L.Phoiơbắc, loại bỏ vỏ thần bí duy tâm để xây dựng nên chủ nghĩa duy vật biện chứng.",
	},
	{
		question: "Tác phẩm nào dưới đây là cương lĩnh chính trị, là kim chỉ nam hành động của toàn bộ phong trào cộng sản và công nhân quốc tế trong cuộc đấu tranh chống chủ nghĩa tư bản, giải phóng loài người có cuộc sống ấm no, tự do, hạnh phúc, được phát triển toàn diện?",
		answers: [
			"Tình cảnh giai cấp lao động ở Anh",
			"Những nguyên lí của chủ nghĩa cộng sản",
			"Tuyên ngôn của Đảng Cộng sản",
			"Điều lệ của Đồng minh những người cộng sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng 'Tuyên ngôn của Đảng Cộng sản là cương lĩnh chính trị, kim chỉ nam hành động của toàn bộ phong trào cộng sản và công nhân quốc tế'.",
	},
	{
		question: "Tác phẩm nào dưới đây KHÔNG được C. Mác và Ph. Ăngghen viết trong giai đoạn từ năm 1848 đến Công xã Pari (1871)?",
		answers: [
			"Ngày mười tám tháng Sương mù của Lui Bônapactơ",
			"Chiến tranh nông dân ở Đức",
			"Cách mạng và phản cách mạng ở Đức",
			"Chống Đuyrinh",
		],
		correct: 3,
		explanation: "Dựa trên tiến trình các tác phẩm (thuộc kiến thức lịch sử phát triển Chủ nghĩa xã hội khoa học, Chương 1), tác phẩm Chống Đuyrinh được Ăngghen viết vào giai đoạn sau (1876-1878), không thuộc giai đoạn 1848-1871.",
	},
	{
		question: "Tác phẩm nào dưới đây KHÔNG được C. Mác và Ph. Ăngghen viết trong giai đoạn sau từ Công xã Pari đến năm 1895?",
		answers: [
			"Ngày mười tám tháng Sương mù của Lui Bônapactơ",
			"Nội chiến ở Pháp",
			"Nguồn gốc của gia đình, của chế độ tư hữu và của nhà nước",
			"Sự phát triển của chủ nghĩa xã hội từ không tưởng đến khoa học",
		],
		correct: 0,
		explanation: "Dựa trên tiến trình lịch sử phát triển CNXHKH, tác phẩm 'Ngày mười tám tháng Sương mù của Lui Bônapactơ' được Mác viết vào đầu thập niên 1850, nằm trước giai đoạn Công xã Paris (1871).",
	},
	{
		question: "Tác phẩm nào dưới đây không được V.I. Lênin viết trong giai đoạn trước Cách mạng tháng Mười Nga?",
		answers: [
			"Làm gì?",
			"Một bước tiến, hai bước lùi",
			"Bàn về nhà nước",
			"Nhà nước và cách mạng",
		],
		correct: 2,
		explanation: "Dựa trên Trang 10-11 của chương 1 của tài liệu, trong các tiểu mục về V.I.Lênin, tác phẩm 'Bàn về nhà nước' (bài giảng tại trường đại học Xvéclốp) được Lênin trình bày vào năm 1919 (sau Cách mạng tháng Mười).",
	},
	{
		question: "Tác phẩm nào dưới đây KHÔNG được V.I. Lênin viết trong giai đoạn sau Cách mạng tháng Mười Nga?",
		answers: [
			"Cách mạng vô sản và tên phản bội Causky",
			"Những người bạn dân là thế nào và họ đấu tranh chống những người dân chủ ra sao?",
			"Những nhiệm vụ trước mắt của chính quyền Xô viết",
			"Bàn về nhà nước",
		],
		correct: 1,
		explanation: "Dựa trên sự phát triển của V.I.Lênin ở chương 1, tác phẩm 'Những người bạn dân là thế nào...' được viết vào năm 1894, thuộc thời kỳ trước Cách mạng tháng Mười.",
	},
	{
		question: "Tác phẩm nào dưới đây đã phân tích một cách có hệ thống lịch sử và logic hoàn chỉnh về những vấn đề cơ bản nhất, xúc tích và chặt chẽ nhất, thâu tóm gần như toàn bộ những luận điểm của chủ nghĩa xã hội khoa học?",
		answers: [
			"Tình cảnh giai cấp lao động ở Anh",
			"Những nguyên lí của chủ nghĩa cộng sản",
			"Tuyên ngôn của Đảng Cộng sản",
			"Điều lệ của Đồng minh những người cộng sản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 8 của chương 1 của tài liệu, chỉ ra rằng 'Tuyên ngôn của Đảng Cộng sản đã nêu và phân tích một cách có hệ thống lịch sử và lôgic hoàn chỉnh về những vấn đề cơ bản nhất, đầy đủ, súc tích và chặt chẽ nhất thâu tóm hầu như toàn bộ những luận điểm của chủ nghĩa xã hội khoa học'.",
	},
];