const cnxhChapter4 = [
	{
		question: "So với các nền dân chủ trước đây, nền dân chủ xã hội chủ nghĩa có điểm khác biệt nào?",
		answers: [
			"Không còn mang tính giai cấp",
			"Là nền dân chủ cho mọi giai cấp",
			"Là nền dân chủ rộng rãi nhất nhưng vẫn là nền dân chủ mang tính giai cấp",
			"Là nền dân chủ thực hiện dân chủ với riêng giai cấp công nhân",
		],
		correct: 2,
		explanation: "Dựa trên Trang 56 và Trang 58 của chương 4 của tài liệu, chỉ ra rằng trong xã hội có giai cấp thì không có 'dân chủ phi giai cấp' (tức luôn mang tính giai cấp), đồng thời dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi.",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa thực hiện ... rộng rãi với đông đảo quần chúng nhân dân.",
		answers: [
			"Dân chủ",
			"Chuyên chính",
			"Thống trị",
			"Quản lý",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Nguyên tắc cơ bản của nền dân chủ xã hội chủ nghĩa là không ngừng mở rộng dân chủ, nâng cao mức độ giải phóng cho những người lao động.",
	},
	{
		question: "Nhà nước xã hội chủ nghĩa là yếu tố cơ bản của...",
		answers: [
			"Nền dân chủ chủ nô",
			"Nền dân chủ tư sản",
			"Nền dân chủ xã hội chủ nghĩa",
			"Nền văn hóa XHCN",
		],
		correct: 2,
		explanation: "Dựa trên Trang 60 và 61 của chương 4 của tài liệu, chỉ ra rằng Nhà nước xã hội chủ nghĩa là công cụ quan trọng để thực hiện nền dân chủ mới - dân chủ xã hội chủ nghĩa.",
	},
	{
		question: "Đặc trưng cơ bản của nhà nước xã hội chủ nghĩa đó là:",
		answers: [
			"Một kiểu nhà nước đặc biệt",
			"“Nửa nhà nước”",
			"“Nhà nước không còn nguyên nghĩa”",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 59 và 64 của chương 4 của tài liệu, chỉ ra rằng Nhà nước xã hội chủ nghĩa là một kiểu nhà nước đặc biệt, và cũng là vấn đề được V.I.Lênin gọi là nhà nước “nửa nhà nước” hay nhà nước “không còn nguyên nghĩa”.",
	},
	{
		question: "Đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa mang bản chất của...",
		answers: [
			"Giai cấp nông dân",
			"Giai cấp công nhân",
			"Đội ngũ trí thức",
			"Đội ngũ doanh nhân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Bản chất chính trị: Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi.",
	},
	{
		question: "Trong chế độ phong kiến tồn tại nền dân chủ phong kiến.",
		answers: [
			"Đúng",
			"Sai",
		],
		correct: 1,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng Trong chế độ phong kiến: chế độ dân chủ chủ nô đã bị xóa bỏ và thay vào đó là chế độ độc tài chuyên chế phong kiến (không có dân chủ).",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa là nền dân chủ cho tất cả mọi người.",
		answers: [
			"Đúng",
			"Sai",
		],
		correct: 1,
		explanation: "Dựa trên Trang 57 và 58 của chương 4 của tài liệu, chỉ ra rằng nền dân chủ vô sản (dân chủ xã hội chủ nghĩa) dành cho đại đa số nhân dân, và nhà nước vẫn thực hiện trấn áp bằng vũ lực đối với bọn bóc lột (nên không phải cho 'tất cả').",
	},
	{
		question: "Dân chủ là gì?",
		answers: [
			"Là công bằng trong xã hội và thực thi công bằng trong xã hội",
			"Là quyền lực thuộc về nhân dân và thực thi quyền làm chủ của nhân dân",
			"Là tự do của mỗi người và thực thi quyền tự do của mỗi người",
			"Là bình đẳng của công dân và thực thi bình đẳng cho công dân",
		],
		correct: 1,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Theo nghĩa gốc: Dân chủ xuất phát từ chữ Hylạp 'Demokratos', có nghĩa là quyền lực thuộc về nhân dân (hay nhân dân là chủ thể quyền lực).",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là gì?",
		answers: [
			"Lực lượng sản xuất hiện đại và quan hệ sản xuất xã hội chủ nghĩa",
			"Quan hệ sản xuất tư bản chủ nghĩa",
			"Nền sản xuất thủ công",
			"Nền sản xuất đại công nghiệp",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất... đáp ứng sự phát triển ngày càng cao của lực lượng sản xuất hiện đại (tức là LLSX hiện đại và QHSX XHCN).",
	},
	{
		question: "Bản chất của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các giai cấp, tầng lớp trong xã hội",
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các dân tộc, tôn giáo và các cộng đồng khác trong xã hội",
			"Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, tính nhân dân rộng rãi và tính dân tộc sâu sắc",
			"Nhà nước xã hội chủ nghĩa mang bản chất chính trị của các giai cấp, tầng lớp trong lịch sử",
		],
		correct: 2,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng Về chính trị: Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, có tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Kiểu nhà nước nào sau đây được V.I. Lênin gọi là “nửa nhà nước”?",
		answers: [
			"Nhà nước chủ nô",
			"Nhà nước tư sản",
			"Nhà nước phong kiến",
			"Nhà nước xã hội chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 64 của chương 4 của tài liệu, chỉ ra rằng nhà nước xã hội chủ nghĩa được Lênin gọi là nhà nước “nửa nhà nước” hay nhà nước “không còn nguyên nghĩa”.",
	},
	{
		question: "Dân chủ là một phạm trù vĩnh viễn trong trường hợp nào?",
		answers: [
			"Khi dân chủ là một giá trị xã hội",
			"Khi dân chủ là một hình thái nhà nước",
			"Khi dân chủ mang tính giai cấp",
			"Khi dân chủ mang tính chính trị",
		],
		correct: 0,
		explanation: "Dựa trên Trang 56 và 57 của chương 4 của tài liệu, chỉ ra rằng Dân chủ là một giá trị xã hội phản ánh những quyền cơ bản của con người (giá trị chung nhân loại luôn tồn tại), phân biệt với khi nó là hình thái nhà nước thì là phạm trù lịch sử.",
	},
	{
		question: "Dân chủ là một phạm trù lịch sử trong trường hợp nào?",
		answers: [
			"Dân chủ là một giá trị xã hội",
			"Dân chủ là một giá trị nhân loại",
			"Khi dân chủ là một hình thức tổ chức thiết chế chính trị",
			"Khi dân chủ là quyền con người",
		],
		correct: 2,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng là một phạm trù chính trị gắn với các hình thức tổ chức nhà nước của giai cấp cầm quyền; là một phạm trù lịch sử gắn với quá trình ra đời, phát triển của lịch sử.",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa ra đời gắn với sự kiện nào?",
		answers: [
			"Giai cấp công nhân giành được chính quyền, thiết lập nhà nước",
			"Giai cấp công nhân bắt đầu đấu tranh chống áp bức, bóc lột",
			"Giai cấp công nhân xây dựng xong CNXH",
			"Giai cấp công nhân có Đảng cộng sản",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng chỉ đến khi Cách mạng Tháng Mười Nga thành công với sự ra đời của nhà nước xã hội chủ nghĩa đầu tiên (giành chính quyền), nền dân chủ xã hội chủ nghĩa mới chính thức được xác lập.",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa mang bản chất của giai cấp nào?",
		answers: [
			"Giai cấp công nhân",
			"Giai cấp nông dân",
			"Nhân dân lao động",
			"Tầng lớp doanh nhân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Bản chất chính trị: Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân...",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa đầu tiên ra đời gắn với sự kiện lịch sử nào?",
		answers: [
			"Khởi nghĩa của công nhân dệt Lion Pháp",
			"Cách mạng tư sản Pháp năm 1789",
			"Cách mạng Tháng Mười Nga năm 1917",
			"Cách mạng Tháng Tám ở Việt Nam năm 1945",
		],
		correct: 2,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng chỉ đến khi Cách mạng Tháng Mười Nga thành công với sự ra đời của nhà nước xã hội chủ nghĩa đầu tiên trên thế giới (1917), nền dân chủ xã hội chủ nghĩa mới chính thức được xác lập.",
	},
	{
		question: "Chức năng của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Đoàn kết các giai cấp, tầng lớp trong xã hội để xây dựng chủ nghĩa xã hội",
			"Đoàn kết các dân tộc, tôn giáo, gia đình để xây dựng chủ nghĩa xã hội",
			"Tổ chức xây dựng chủ nghĩa xã hội và trấn áp những lực lượng chống phá sự nghiệp xây dựng chủ nghĩa xã hội của nhân dân",
			"Tổ chức xây dựng, quản lý nền sản xuất lớn xã hội tư bản chủ nghĩa",
		],
		correct: 2,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng chức năng của nhà nước được chia thành chức năng giai cấp (trấn áp) và chức năng xã hội (tổ chức và xây dựng).",
	},
	{
		question: "Tổ chức nào là quan trọng nhất để thực thi quyền lực của nhân dân?",
		answers: [
			"Nhà nước xã hội chủ nghĩa",
			"Đảng cộng sản",
			"Mặt trận Tổ quốc",
			"Các tổ chức chính trị - xã hội và đoàn thể của nhân dân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Nhà nước xã hội chủ nghĩa là công cụ quan trọng để thực hiện nền dân chủ mới - dân chủ xã hội chủ nghĩa (thể chế hóa ý chí nhân dân).",
	},
	{
		question: "Sự ra đời của nhà nước xã hội chủ nghĩa gắn với sự kiện nào?",
		answers: [
			"Giai cấp công nhân lật đổ nhà nước của giai cấp bóc lột, giành được chính quyền",
			"Giai cấp công nhân xây dựng xong CNXH",
			"Giai cấp công nhân đấu tranh phản đối tình trạng áp bức bóc lột của giai cấp tư sản",
			"Giai cấp công nhân đấu tranh đòi tăng lương, giảm giờ làm, cải thiện điều kiện lao động",
		],
		correct: 0,
		explanation: "Dựa trên Trang 59 của chương 4 của tài liệu, chỉ ra rằng nhà nước xã hội chủ nghĩa là kết quả của cuộc cách mạng do giai cấp vô sản và nhân dân lao động tiến hành (lật đổ nhà nước cũ, giành quyền lực).",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa có sự khác biệt về chất so với dân chủ tư sản.",
		answers: [
			"Đúng",
			"Sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 57 và 58 của chương 4 của tài liệu, chỉ ra rằng Dân chủ xã hội chủ nghĩa là nền dân chủ cao hơn về chất so với nền dân chủ tư sản.",
	},
	{
		question: "Điền từ vào chỗ trống (...) trong luận điểm sau: Dân chủ xã hội chủ nghĩa vừa mang bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi, tính (...) sâu sắc.",
		answers: [
			"Giai cấp",
			"Nhân văn",
			"Dân tộc",
			"Xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi, tính dân tộc sâu sắc.",
	},
	{
		question: "Công cụ hữu hiệu nhất để Nhà nước pháp quyền xã hội chủ nghĩa quản lý xã hội là gì?",
		answers: [
			"Kế hoạch",
			"Chính sách",
			"Pháp luật",
			"Chủ trương",
		],
		correct: 2,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Dân chủ gắn liền với kỷ cương và phải thể chế hóa bằng pháp luật, được pháp luật bảo đảm.",
	},
	{
		question: "Đặc điểm của Nhà nước pháp quyền xã hội chủ nghĩa là gì?",
		answers: [
			"Quản lý xã hội bằng pháp luật",
			"Quản lý xã hội bằng mệnh lệnh hành chính",
			"Quản lý xã hội bằng dư luận",
			"Quản lý xã hội bằng niềm tin",
		],
		correct: 0,
		explanation: "Dựa trên Trang 62 của chương 4 của tài liệu, chỉ ra rằng Nhà nước pháp quyền được hiểu là nhà nước mà ở đó, tất cả mọi công dân đều được giáo dục pháp luật... Được tổ chức và hoạt động dựa trên cơ sở của Hiến pháp và pháp luật.",
	},
	{
		question: "Điền từ vào chỗ trống (...) trong câu nói của Chủ tịch Hồ Chí Minh: “Nước ta là nước dân chủ, nghĩa là nước nhà do nhân dân làm chủ. Nhân dân có quyền lợi làm chủ, thì phải có (...) làm tròn bổn phận công dân”.",
		answers: [
			"Khả năng",
			"Nghĩa vụ",
			"Quyết tâm",
			"Nguyện vọng",
		],
		correct: 1,
		explanation: "Dựa trên Trang 62 của chương 4 của tài liệu, chỉ ra quan điểm nhà nước pháp quyền là Đề cao quyền lợi và nghĩa vụ của công dân.",
	},
	{
		question: "Sự khác biệt của nền dân chủ xã hội chủ nghĩa so với các nền dân chủ trước là gì?",
		answers: [
			"Dân chủ xã hội chủ nghĩa không mang tính giai cấp",
			"Dân chủ xã hội chủ nghĩa chỉ mang lại lợi ích cho giai cấp công nhân",
			"Dân chủ xã hội chủ nghĩa là nền dân chủ cho mọi giai cấp",
			"Dân chủ xã hội chủ nghĩa là nền dân chủ rộng rãi cho nhân dân lao động",
		],
		correct: 3,
		explanation: "Dựa trên Trang 59 của chương 4 của tài liệu, trong bảng so sánh chỉ ra rằng Dân chủ xã hội chủ nghĩa Dành cho đại đa số nhân dân lao động, phục vụ lợi ích cho đại đa số.",
	},
	{
		question: "Ở Việt Nam, Nhà nước Việt Nam dân chủ cộng hòa ra đời sau thắng lợi của cuộc Cách mạng Tháng Tám năm 1945.",
		answers: [
			"Đúng",
			"Sai",
		],
		correct: 0,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Nền dân chủ xã hội chủ nghĩa ở Việt Nam ra đời từ chế độ dân chủ nhân dân, sau thắng lợi của Cách mạng Tháng Tám năm 1945.",
	},
	{
		question: "Đối với lực lượng chống đối, phá hoại sự nghiệp cách mạng xã hội chủ nghĩa, nhà nước xã hội chủ nghĩa thực hiện…",
		answers: [
			"Sự trấn áp",
			"Sự tổ chức",
			"Sự điều hành",
			"Quản lý",
		],
		correct: 0,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng chức năng giai cấp (trấn áp) của nhà nước đối với những lực lượng chống lại sự nghiệp xây dựng chủ nghĩa xã hội.",
	},
	{
		question: "Tổ chức nào thực hiện sự trấn áp đối với lực lượng chống đối, phá hoại sự nghiệp cách mạng xã hội chủ nghĩa?",
		answers: [
			"Đảng cộng sản",
			"Nhà nước xã hội chủ nghĩa",
			"Nghiệp đoàn",
			"Công đoàn",
		],
		correct: 1,
		explanation: "Dựa trên Trang 60 và 61 của chương 4 của tài liệu, chỉ ra rằng Nhà nước là công cụ bạo lực để ngăn chặn có hiệu quả các hành vi xâm phạm, thực hiện chức năng trấn áp.",
	},
	{
		question: "Nền dân chủ tư sản ra đời trong chế độ nào?",
		answers: [
			"Cộng sản nguyên thủy",
			"Chiếm hữu nô lệ",
			"Phong kiến",
			"Tư bản chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng Trong chế độ tư bản chủ nghĩa: Dân chủ tư sản ra đời là một bước tiến lớn.",
	},
	{
		question: "Dân chủ đại diện được thực hiện như thế nào?",
		answers: [
			"Nhân dân trực tiếp thực hiện quyền làm chủ nhà nước và xã hội",
			"Thực hiện thông qua trưng cầu dân ý",
			"Nhân dân giao quyền lực của mình cho hệ thống cơ quan dân cử",
			"Nhân dân tham gia vào các công việc của nhà nước và cộng đồng dân cư",
		],
		correct: 2,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Hình thức dân chủ gián tiếp là hình thức dân chủ đại diện, được thực hiện do nhân dân “ủy quyền”, giao quyền lực của mình cho tổ chức mà nhân dân trực tiếp bầu ra.",
	},
	{
		question: "“Dân chủ là dân là chủ và dân làm chủ” là quan điểm của…",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh",
		],
		correct: 3,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Theo Hồ Chí Minh: Dân chủ là dân là chủ và dân làm chủ.",
	},
	{
		question: "Theo quan niệm từ thời cổ đại, dân chủ là",
		answers: [
			"quyền bình đẳng tuyệt đối của con người.",
			"quyền lực thuộc về thiểu số người trong xã hội.",
			"quyền tự do không giới hạn của mỗi người.",
			"quyền lực thuộc về nhân dân.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, dân chủ phản ánh khát vọng hướng tới tự do, bình đẳng của con người từ xa xưa.",
	},
	{
		question: "Quan niệm nào sau đây không đúng về dân chủ?",
		answers: [
			"Dân chủ là một trong những nguyên tắc tổ chức quản lí nhà nước.",
			"Dân chủ là quyền tự do tuyệt đối của con người.",
			"Dân chủ là một giá trị chung của nhân loại.",
			"Dân chủ là một hình thái nhà nước.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 56-57 của chương 4 của tài liệu, dân chủ là một thiết chế có tính giai cấp, gắn với nhà nước, nên không có thứ quyền tự do tuyệt đối phi giai cấp cho mọi con người.",
	},
	{
		question: "Theo quan niệm của chủ nghĩa Mác — Lênin, dân chủ phản ánh cuộc đấu tranh của nhân dân lao động chống lại áp bức, cường quyền, vì thế dân chủ được coi là một…",
		answers: [
			"giá trị xã hội.",
			"yếu tố xã hội.",
			"tổ chức xã hội.",
			"thành phần xã hội.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 56 và 57 của chương 4 của tài liệu, chỉ ra rằng Dân chủ là một giá trị xã hội phản ánh những quyền cơ bản của con người trong quá trình đấu tranh.",
	},
	{
		question: "“Quyền lực thuộc về nhân dân, nhân dân tự tổ chức và thực hiện trước hết và chủ yếu là thông qua nhà nước của mình” là nội dung của khái niệm nào dưới đây?",
		answers: [
			"Dân chủ.",
			"Bình đẳng.",
			"Công bằng.",
			"Tự do.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Dân chủ xuất phát từ chữ Hylạp... quyền lực thuộc về nhân dân (hay nhân dân là chủ thể quyền lực).",
	},
	{
		question: "Nền dân chủ xuất hiện khi…",
		answers: [
			"có xã hội loài người.",
			"có nhà nước vô sản.",
			"có nhà nước.",
			"có công cụ lao động.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 56 và 57 của chương 4 của tài liệu, chỉ ra rằng nền dân chủ (với tư cách là chế độ/hình thái) gắn liền với một kiểu nhà nước và một giai cấp cầm quyền.",
	},
	{
		question: "Mức độ, phạm vi tham gia thật sự của quần chúng nhân dân vào công việc quản lí nhà nước phản ánh…",
		answers: [
			"cấu trúc của nền dân chủ",
			"trình độ phát triển của nền dân chủ.",
			"quá trình đấu tranh giành dân chủ.",
			"sự ra đời của nền dân chủ.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 59 của chương 4 của tài liệu, chỉ ra rằng phản ánh trình độ nhân dân tham gia vào mọi công việc của nhà nước, quần chúng nhân dân thực sự tham gia vào từng bước của cuộc sống.",
	},
	{
		question: "Dân chủ có sự ra đời, tồn tại và phát triển trong một giai đoạn nhất định và sẽ mất đi khi trong xã hội không còn giai cấp, vì thế, dân chủ là một…",
		answers: [
			"yếu tố văn hoá.",
			"thành phần của xã hội.",
			"phạm trù lịch sử.",
			"phạm trù giai cấp.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng là một phạm trù lịch sử gắn với quá trình ra đời, phát triển của lịch sử xã hội nhân loại.",
	},
	{
		question: "Trên phương diện quyền lực, dân chủ là…",
		answers: [
			"quyền lực thuộc về nhân dân.",
			"một hình thức hay hình thái nhà nước.",
			"một nguyên tắc - nguyên tắc dân chủ.",
			"một quan niệm - quan niệm về dân chủ, về tinh thần dân chủ.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Dân chủ... có nghĩa là quyền lực thuộc về nhân dân.",
	},
	{
		question: "Trên phương diện chế độ xã hội và trong lĩnh vực chính trị, dân chủ là",
		answers: [
			"quyền lực thuộc về nhân dân.",
			"một hình thức hay hình thái nhà nước",
			"một nguyên tắc - nguyên tắc dân chủ.",
			"một quan niệm - quan niệm về dân chủ, về tinh thần dân chủ.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Thứ hai, trên phương diện chế độ xã hội và trong lĩnh vực chính trị, dân chủ là một hình thức hay hình thái nhà nước.",
	},
	{
		question: "Trên phương diện tư tưởng, dân chủ là…",
		answers: [
			"quyền lực thuộc về nhân dân.",
			"một hình thức hay hình thái nhà nước.",
			"một nguyên tắc - nguyên tắc dân chủ.",
			"một quan niệm - quan niệm về dân chủ, về tinh thần dân chủ.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, dân chủ được nhận thức như một hệ giá trị, một quan niệm tư tưởng, sự phản ánh khát vọng tự do bình đẳng.",
	},
	{
		question: "Trên phương diện tổ chức và quản lí xã hội, dân chủ là…",
		answers: [
			"quyền lực thuộc về nhân dân.",
			"một hình thức hay hình thái nhà nước.",
			"một nguyên tắc - nguyên tắc dân chủ.",
			"một quan niệm - quan niệm về dân chủ, về tinh thần dân chủ.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, chỉ ra rằng Thứ ba, trên phương diện tổ chức và quản lý xã hội, dân chủ là một nguyên tắc - nguyên tắc dân chủ.",
	},
	{
		question: "Câu nói: “Chế độ ta là chế độ dân chủ, tức là nhân dân là người chủ, mà chính phủ là người đầy tớ trung thành của nhân dân” là của ai?",
		answers: [
			"Hồ Chí Minh.",
			"Võ Nguyên Giáp",
			"Phạm Văn Đồng.",
			"Nguyễn Phú Trọng.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 56 của chương 4 của tài liệu, thuộc về quan điểm của Hồ Chí Minh nhấn mạnh: Dân chủ là dân là chủ và dân làm chủ.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống để hoàn thiện khẳng định sau của Đảng Cộng sản Việt Nam: “Trong toàn bộ hoạt động của mình, Đảng phải quán triệt tư tưởng xây dựng và phát huy quyền làm chủ của nhân dân lao động”.",
		answers: [
			"lấy dân làm nền tảng.",
			"lấy dân làm gốc.",
			"lấy dân làm đích.",
			"lấy dân làm chỗ dựa.",
		],
		correct: 1,
		explanation: "Dựa trên lý luận xây dựng nền dân chủ XHCN ở Việt Nam xuyên suốt của Đảng (Chương 3 và Chương 4), nguyên tắc bất di bất dịch của Đảng là lấy dân làm gốc.",
	},
	{
		question: "Trong chế độ cộng sản nguyên thuỷ đã xuất hiện hình thức manh nha của dân chủ mà Ph. Ăngghen gọi là…",
		answers: [
			"dân chủ công xã.",
			"dân chủ sơ khai.",
			"dân chủ nguyên thuỷ.",
			"dân chủ cộng sản.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng Trong chế độ cộng sản nguyên thủy: Dân chủ sơ khai “dân chủ nguyên thủy”, “dân chủ quân sự”.",
	},
	{
		question: "Với tư cách là một hình thái nhà nước, một chế độ chính trị, lịch sử nhân loại có ba nền dân chủ là…",
		answers: [
			"dân chủ chủ nô, dân chủ phong kiến và dân chủ tư sản.",
			"dân chủ chủ nô, dân chủ tư sản và dân chủ xã hội chủ nghĩa.",
			"dân chủ nguyên thuỷ, dân chủ phong kiến và dân chủ tư sản.",
			"dân chủ nguyên thuỷ, dân chủ tư sản và dân chủ xã hội chủ nghĩa.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 57 và 58 của chương 4 của tài liệu, chỉ ra rằng cho đến nay có ba nền (chế độ) dân chủ: Nền dân chủ chủ nô; Nền dân chủ tư sản; Nền dân chủ xã hội chủ nghĩa.",
	},
	{
		question: "Hình thái kinh tế - xã hội nào dưới đây không có nền dân chủ?",
		answers: [
			"Chiếm hữu nô lệ.",
			"Phong kiến.",
			"Tư bản chủ nghĩa.",
			"Cộng sản chủ nghĩa.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 57 của chương 4 của tài liệu, chỉ ra rằng Trong chế độ phong kiến... chế độ dân chủ chủ nô đã bị xóa bỏ và thay vào đó là chế độ độc tài chuyên chế phong kiến (không có dân chủ).",
	},
	{
		question: "Nền dân chủ nào dưới đây là nền dân chủ rộng rãi nhất trong lịch sử?",
		answers: [
			"Dân chủ nguyên thuỷ.",
			"Dân chủ chủ nô.",
			"Dân chủ tư sản.",
			"Dân chủ xã hội chủ nghĩa.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 64 của chương 4 của tài liệu, vấn đề thảo luận: 'Vì sao nói: dân chủ xã hội chủ nghĩa là nền dân chủ rộng rãi nhất trong lịch sử?' do nó thuộc về đại đa số nhân dân.",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa là nền dân chủ mang bản chất của…",
		answers: [
			"giai cấp công nhân.",
			"giai cấp công nhân và đội ngũ trí thức",
			"giai cấp công nhân và giai cấp nông dân.",
			"giai cấp tư sản và giai cấp tiểu tư sản.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân...",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa là nền dân chủ do…",
		answers: [
			"Đảng của giai cấp công nhân lãnh đạo.",
			"Đảng cầm quyền lãnh đạo.",
			"Đảng của nhân dân lãnh đạo.",
			"Đảng của trí thức lãnh đạo.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 và 59 của chương 4 của tài liệu, nền dân chủ XHCN đặt dưới sự lãnh đạo của Đảng Cộng sản (đội tiên phong của giai cấp công nhân).",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa dựa trên hệ tư tưởng của giai cấp, tầng lớp nào sau đây?",
		answers: [
			"Giai cấp công nhân.",
			"Giai cấp nông dân.",
			"Giai cấp tư sản.",
			"Tầng lớp trí thức.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Bản chất tư tưởng - văn hóa - xã hội: Nền dân chủ xã hội chủ nghĩa lấy chủ nghĩa Mác - Lênin (hệ tư tưởng của giai cấp công nhân) làm nền tảng tư tưởng.",
	},
	{
		question: "Nền dân chủ cao hơn về chất so với nền dân chủ tư sản, ở đó mọi quyền lực thuộc về nhân dân, dân là chủ và dân làm chủ, dân chủ và pháp luật nằm trong sự thống nhất biện chứng; được thực hiện bằng nhà nước pháp quyền xã hội chủ nghĩa, đặt dưới sự lãnh đạo của Đảng Cộng sản là nền dân chủ…",
		answers: [
			"nguyên thuỷ.",
			"chủ nô.",
			"phong kiến.",
			"xã hội chủ nghĩa.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 57 và 58 của chương 4 của tài liệu, chỉ ra rằng Dân chủ xã hội chủ nghĩa là nền dân chủ cao hơn về chất... được thực hiện bằng nhà nước pháp quyền xã hội chủ nghĩa, đặt dưới sự lãnh đạo của Đảng Cộng sản.",
	},
	{
		question: "Khái niệm “dân chủ xã hội chủ nghĩa” đồng nghĩa với thuật ngữ nào dưới đây?",
		answers: [
			"Dân chủ nguyên thuỷ.",
			"Dân chủ chủ nô.",
			"Dân chủ tư sản.",
			"Dân chủ vô sản.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Nền dân chủ xã hội chủ nghĩa (dân chủ vô sản), gắn với chế độ xã hội chủ nghĩa.",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa về cơ bản thống nhất với khái niệm nào dưới đây?",
		answers: [
			"Chuyên chính vô sản.",
			"Chủ nghĩa xã hội.",
			"Nhà nước xã hội chủ nghĩa.",
			"Chính đảng của giai cấp công nhân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, nền dân chủ được thực thi bằng nhà nước vô sản, tức là nền chuyên chính cách mạng của giai cấp vô sản.",
	},
	{
		question: "Không ngừng mở rộng dân chủ, nâng cao mức độ giải phóng cho những người lao động, thu hút họ tham gia tự giác vào công việc quản lí nhà nước, quản lí xã hội là…",
		answers: [
			"nguyên tắc cơ bản của nền dân chủ chủ nô.",
			"nguyên tắc cơ bản của nền dân chủ tư sản.",
			"nguyên tắc cơ bản của nền dân chủ xã hội chủ nghĩa.",
			"nội dung cơ bản của nền dân chủ xã hội chủ nghĩa.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Nguyên tắc cơ bản của nền dân chủ xã hội chủ nghĩa là không ngừng mở rộng dân chủ, nâng cao mức độ giải phóng cho những người lao động...",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa trên thế giới chính thức được xác lập gắn với sự kiện nào sau đây?",
		answers: [
			"Công xã Pari ra đời (1871).",
			"Cách mạng tháng Hai Nga (1917).",
			"Cách mạng tháng Mười Nga (1917).",
			"Cách mạng tháng Tám ở Việt Nam (1945).",
		],
		correct: 2,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng khi Cách mạng Tháng Mười Nga thành công (1917), nền dân chủ xã hội chủ nghĩa mới chính thức được xác lập.",
	},
	{
		question: "Nội dung nào dưới đây không phải là đặc trưng cơ bản của nền dân chủ xã hội chủ nghĩa?",
		answers: [
			"Thực hiện dân chủ với mọi tầng lớp, mọi giai cấp trong xã hội.",
			"Đảm bảo quyền lực thuộc về nhân dân.",
			"Có cơ sở kinh tế là chế độ công hữu về tư liệu sản xuất chủ yếu của xã hội.",
			"Kết hợp hài hoà lợi ích cá nhân, tập thể và xã hội.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, nền dân chủ XHCN mang tính giai cấp và vẫn thực hiện trấn áp bọn bóc lột, do đó không phải là dân chủ cho 'mọi giai cấp'.",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là…",
		answers: [
			"nền kinh tế hàng hoá nhiều thành phần.",
			"chế độ công hữu về những tư liệu sản xuất chủ yếu của xã hội.",
			"chế độ sở hữu tư nhân về tư liệu sản xuất.",
			"nền kinh tế thị trường xã hội chủ nghĩa.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 58 của chương 4 của tài liệu, chỉ ra rằng Bản chất kinh tế: Nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất chủ yếu của toàn xã hội.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống: Dân chủ xã hội chủ nghĩa là nền dân chủ ...... so với nền dân chủ tư sản, là nền dân chủ mà ở đó mọi quyền lực thuộc về nhân dân, ……… , dân chủ và pháp luật nằm trong sự thống nhất biện chứng, được thực hiện bằng ….. , đặt dưới sự lãnh đạo của Đảng Cộng sản.",
		answers: [
			"cao nhất; của dân, do dân, vì dân; quyền lực nhà nước.",
			"tuyệt đối; dân bàn, dân làm, dân kiểm tra; Hiến pháp và pháp luật.",
			"cao hơn về chất; dân là chủ và dân làm chủ; Nhà nước pháp quyền xã hội chủ nghĩa.",
			"tuyệt đối; dân bàn, dân làm, dân kiểm tra; Hiến pháp và pháp luật.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 57 và 58 của chương 4 của tài liệu, chỉ ra định nghĩa nguyên văn: Dân chủ xã hội chủ nghĩa là nền dân chủ cao hơn về chất... dân là chủ và dân làm chủ... được thực hiện bằng nhà nước pháp quyền xã hội chủ nghĩa.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống để hoàn thiện khẳng định của C.Mác trong Cương lĩnh Gôta: “Quyền không bao giờ có thể ở mức độ cao hơn chế độ (….) và sự phát triển văn hoá của xã hội do chế độ đó quyết định”.",
		answers: [
			"chính trị.",
			"kinh tế.",
			"xã hội.",
			"nhà nước.",
		],
		correct: 1,
		explanation: "Dựa trên nền tảng lý luận của Mác về cơ sở hạ tầng quyết định kiến trúc thượng tầng (được học thuyết hóa trong Chương 3 và 4), quyền lợi pháp lý, dân chủ (kiến trúc thượng tầng) không bao giờ cao hơn chế độ kinh tế.",
	},
	{
		question: "Trong việc thực hiện quyền dân chủ trên lĩnh vực chính trị, công dân sẽ không thực hiện hành vi nào sau đây?",
		answers: [
			"ứng cử và bầu cử.",
			"Tham gia quản lí nhà nước.",
			"Kiểm tra, thanh tra mọi hoạt động của nhà nước.",
			"Tham gia giám sát mọi hoạt động của nhà nước.",
		],
		correct: 2,
		explanation: "Dựa trên cơ chế hoạt động của nền dân chủ XHCN ở Việt Nam (Trang 61, 62), người dân có quyền giám sát, nhưng 'thanh tra' chuyên sâu là nghiệp vụ của cơ quan công quyền chuyên trách.",
	},
	{
		question: "“Thực hành dân chủ là cái chìa khoá vạn năng có thể giải quyết mọi khó khăn” là câu nói của…",
		answers: [
			"V.l. Lênin.",
			"Mao Trạch Đông.",
			"Hồ Chí Minh.",
			"Phạm Văn Đồng.",
		],
		correct: 2,
		explanation: "Dựa trên tư tưởng Hồ Chí Minh về dân chủ và nhà nước, Bác Hồ luôn khẳng định thực hành dân chủ sâu rộng là chìa khóa vạn năng.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống để hoàn thiện khẳng định của Đảng Cộng sản Việt Nam trong Cương lĩnh năm 1991: “Dân chủ gắn liền với...... xã hội phải được thực hiện trong thực tế cuộc sống trên tất cả các lĩnh vực chính trị, kinh tế, văn hoá, xã hội thông qua hoạt động của Nhà nước do nhân dân cử ra và bằng các hình thức dân chủ…”",
		answers: [
			"công bằng; trực tiếp",
			"bình đẳng; trực tiếp.",
			"công bằng; gián tiếp.",
			"bình đẳng; gián tiếp.",
		],
		correct: 0,
		explanation: "Dựa trên tinh thần Cương lĩnh 1991 của Đảng về xây dựng dân chủ XHCN.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống để hoàn thiện khẳng định của Đảng Cộng sản Việt Nam trong Cương lĩnh năm 1991: “Dân chủ đi đôi với …. kỉ cương, phải được thể chế hoá bằng…. và được …….. bảo đảm”.",
		answers: [
			"kỉ luật; hiến pháp; hiến pháp.",
			"kỉ luật; pháp luật; pháp luật.",
			"đảm bảo; pháp luật; pháp luật.",
			"đảm bảo; hiến pháp; hiến pháp.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Dân chủ gắn liền với kỷ cương và phải thể chế hóa bằng pháp luật, được pháp luật bảo đảm.",
	},
	{
		question: "Nền dân chủ xã hội chủ nghĩa có sự kết hợp hài hoà về…",
		answers: [
			"chính trị giữa cá nhân, tập thể với toàn xã hội.",
			"văn hoá giữa cá nhân, tập thể với toàn xã hội.",
			"lợi ích giữa cá nhân, tập thể với lợi ích của toàn xã hội.",
			"nhận thức giữa cá nhân, tập thể với toàn xã hội.",
		],
		correct: 2,
		explanation: "Dựa trên định hướng xây dựng CNXH (Trang 50 - 51 và bản chất dân chủ), dân chủ XHCN luôn hướng tới bảo đảm hài hòa hệ thống lợi ích.",
	},
	{
		question: "Chế độ dân chủ nhân dân ở nước ta được xác lập…",
		answers: [
			"sau khi Đảng Cộng sản Việt Nam ra đời năm 1930.",
			"sau Cách mạng tháng Tám năm 1945.",
			"sau chiến thắng Điện Biên Phủ năm 1954.",
			"sau đại thắng mùa xuân năm 1975.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 61 của chương 4 của tài liệu, chỉ ra rằng Nền dân chủ xã hội chủ nghĩa ở Việt Nam ra đời từ chế độ dân chủ nhân dân, sau thắng lợi của Cách mạng Tháng Tám năm 1945.",
	},
	{
		question: "Đảng Cộng sản Việt Nam khẳng định: “Trong toàn bộ hoạt động của mình, Đảng phải quán triệt tư tưởng “lấy dân làm gốc”, xây dựng và phát huy quyền làm chủ của nhân dân lao động” trong Đại hội nào dưới đây?",
		answers: [
			"Đại hội IV.",
			"Đại hội V.",
			"Đại hội VI.",
			"Đại hội VII.",
		],
		correct: 2,
		explanation: "Dựa trên lịch sử đường lối đổi mới của Đảng (Đại hội VI - 1986 là đại hội đánh dấu sự đổi mới toàn diện với phương châm 'lấy dân làm gốc').",
	},
	{
		question: "Đảng Cộng sản Việt Nam khẳng định: “Chúng ta xác định mối quan hệ Đảng lãnh đạo, nhân dân làm chủ, nhà nước quản lí thành cơ chế chung trong quản lí toàn bộ xã hội” trong Đại hội nào dưới đây?",
		answers: [
			"Đại hội VI.",
			"Đại hội VII.",
			"Đại hội VIII.",
			"Đại hội IX.",
		],
		correct: 1,
		explanation: "Dựa trên kiến thức lịch sử Cương lĩnh 1991 (Đại hội VII), Đảng xác định cơ chế Đảng lãnh đạo, Nhà nước quản lý, Nhân dân làm chủ.",
	},
	{
		question: "Định hướng nào dưới đây không phải là định hướng nhằm phát huy dân chủ xã hội chủ nghĩa ở Việt Nam?",
		answers: [
			"Hoàn thiện thể chế kinh tế thị trường định hướng xã hội chủ nghĩa, tạo ra cơ sở kinh tế vững chắc.",
			"Xây dựng Đảng Cộng sản Việt Nam trong sạch, vững mạnh với tư cách là điều kiện tiên quyết để xây dựng nền dân chủ xã hội chủ nghĩa",
			"Xây dựng và từng bước hoàn thiện các hệ thống giám sát, phản biện xã hội, phát huy quyền làm chủ của nhân dân.",
			"Phát huy vai trò của các tổ chức chính trị - xã hội bằng cách tách các tổ chức này ra ngoài hệ thống chính trị nhằm tăng tính độc lập của các tổ chức.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 63 của chương 4 của tài liệu, phương hướng xây dựng Nhà nước và phát huy dân chủ đòi hỏi nâng cao vai trò các tổ chức chính trị - xã hội chứ không phải 'tách' ra ngoài hệ thống chính trị.",
	},
	{
		question: "Nguyên nhân nào dưới đây dẫn tới sự xuất hiện của nhà nước?",
		answers: [
			"Sự xuất hiện của chế độ tư hữu và phân chia giai cấp.",
			"Sự xuất hiện chế độ tư bản chủ nghĩa và phân chia giai cấp.",
			"Sự xuất hiện chế độ chiếm hữu nô lệ và phân chia giai cấp.",
			"Sự xuất hiện của chế độ xã hội chủ nghĩa và phân chia giai cấp.",
		],
		correct: 0,
		explanation: "Dựa trên nguồn gốc ra đời nhà nước trong học thuyết Mác-Lênin, nhà nước ra đời khi xã hội xuất hiện chế độ tư hữu và phân chia giai cấp đối kháng.",
	},
	{
		question: "Căn cứ vào tính chất của quyền lực, nhà nước có chức năng nào dưới đây?",
		answers: [
			"Chức năng đối nội và chức năng đối ngoại.",
			"Chức năng quản lí kinh tế và quản lí chính trị.",
			"Chức năng giai cấp và chức năng xã hội.",
			"Chức năng lãnh đạo và chức năng giám sát.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng Căn cứ vào tính chất của quyền lực nhà nước, chức năng của nhà nước được chia thành chức năng giai cấp (trấn áp) và chức năng xã hội (tổ chức và xây dựng).",
	},
	{
		question: "Căn cứ vào phạm vi tác động của quyền lực, nhà nước có chức năng nào dưới đây?",
		answers: [
			"Chức năng đối nội và chức năng đối ngoại.",
			"Chức năng quản lí kinh tế và quản lí chính trị.",
			"Chức năng giai cấp và chức năng xã hội.",
			"Chức năng lãnh đạo và chức năng giám sát.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng Căn cứ vào phạm vi tác động của quyền lực nhà nước, chức năng của nhà nước được chia thành chức năng đối nội và chức năng đối ngoại.",
	},
	{
		question: "Căn cứ vào lĩnh vực tác động của quyền lực, nhà nước có…",
		answers: [
			"chức năng đối nội và chức năng đối ngoại.",
			"chức năng chính trị, kinh tế, văn hoá.",
			"chức năng giai cấp và chức năng xã hội.",
			"chức năng lãnh đạo và chức năng giám sát.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng Căn cứ vào lĩnh vực tác động của quyền lực nhà nước... được chia thành chức năng chính trị, kinh tế, văn hóa, xã hội,..",
	},
	{
		question: "Trong xã hội có giai cấp, nhà nước luôn mang bản chất của…",
		answers: [
			"giai cấp có lực lượng đông đảo nhất.",
			"giai cấp có trình độ cao nhất.",
			"giai cấp thống trị xã hội.",
			"giai cấp đại diện cho lực lượng sản xuất tiên tiến.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 56 và 57 của chương 4 của tài liệu, chỉ ra rằng mỗi chế độ dân chủ gắn với nhà nước đều mang bản chất của giai cấp cầm quyền (giai cấp thống trị).",
	},
	{
		question: "Nhà nước tư sản mang bản chất của giai cấp…",
		answers: [
			"chủ nô.",
			"địa chủ.",
			"tư sản.",
			"công nhân.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 59 của chương 4 của tài liệu, trong bảng so sánh chỉ ra rằng Nhà nước tư sản mang bản chất của giai cấp tư sản.",
	},
	{
		question: "Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp…",
		answers: [
			"chủ nô.",
			"địa chủ.",
			"tư sản.",
			"công nhân.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 60 của chương 4 của tài liệu, chỉ ra rằng Nhà nước xã hội chủ nghĩa (nhà nước chuyên chính vô sản) mang bản chất của giai cấp công nhân.",
	},
];