const cnxhChapter5 = [
	{
		question: "Điền vào chỗ trống (...) để hoàn thành luận điểm của Đảng Cộng sản Việt Nam khi xác định chiến lược của cách mạng Việt Nam: “Tăng cường khối đại đoàn kết toàn dân tộc trên (...) liên minh giai cấp công nhân với giai cấp nông dân và đội ngũ trí thức do Đảng lãnh đạo”.",
		answers: [
			"Nền tảng",
			"Cơ sở",
			"Động lực",
			"Mục tiêu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 72 và hệ thống kiến thức chương 5 của tài liệu, chỉ ra rằng Đảng ta luôn khẳng định: Tăng cường khối đại đoàn kết toàn dân tộc trên nền tảng liên minh giai cấp công nhân với giai cấp nông dân và đội ngũ trí thức do Đảng lãnh đạo.",
	},
	{
		question: "Điền vào chỗ trống (...) để hoàn thành quan niệm về cơ cấu xã hội: Cơ cấu xã hội là những (…) cùng toàn bộ những mối (…) do sự tác động lẫn nhau của các cộng đồng đó tạo nên.",
		answers: [
			"Giai cấp … kinh tế",
			"Cộng đồng người … quan hệ xã hội",
			"Con người ... liên hệ",
			"Thiết chế … quan hệ",
		],
		correct: 1,
		explanation: "Dựa trên Trang 65 của chương 5 của tài liệu, chỉ ra rằng: cơ cấu xã hội là những cộng đồng người cùng toàn bộ những mối quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng ấy tạo nên.",
	},
	{
		question: "Điền vào chỗ trống để hoàn thành quan niệm sau: (…) là hệ thống các giai cấp, tầng lớp xã hội tồn tại khách quan trong một chế độ xã hội nhất định, thông qua những mối quan hệ về sở hữu tư liệu sản xuất, về tổ chức quản lý quá trình sản xuất, về địa vị chính trị - xã hội… giữa các giai cấp, tầng lớp đó.",
		answers: [
			"Cơ cấu xã hội – dân cư",
			"Cơ cấu xã hội – nghề nghiệp",
			"Cơ cấu xã hội – giai cấp",
			"Cơ cấu xã hội – dân tộc",
		],
		correct: 2,
		explanation: "Dựa trên Trang 66 của chương 5 của tài liệu, chỉ ra rằng: Cơ cấu xã hội - giai cấp là hệ thống các giai cấp, tầng lớp xã hội tồn tại khách quan trong một chế độ xã hội nhất định, thông qua những mối quan hệ về sở hữu tư liệu sản xuất, về tổ chức quản lý quá trình sản xuất, về địa vị chính trị - xã hội...giữa các giai cấp và tầng lớp đó.",
	},
	{
		question: "Xu hướng biến đổi của giai cấp nông dân Việt Nam trong thời kỳ quá độ lên chủ nghĩa xã hội là gì?",
		answers: [
			"Giai cấp nông dân chuyển sang sản xuất hàng hóa",
			"Giai cấp nông dân trở thành giai cấp giữ vai trò lãnh đạo xã hội",
			"Giai cấp nông dân chuyển dịch trở thành một bộ phận của giai cấp công nhân",
			"Giai cấp nông dân trở thành giai cấp thống trị xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 73 của chương 5 của tài liệu, chỉ ra rằng trong tiến trình công nghiệp hóa, lực lượng lao động nông nghiệp có xu hướng chuyển dịch cơ cấu, giảm tỷ trọng và một bộ phận chuyển hóa tham gia vào các doanh nghiệp công nghiệp, trở thành công nhân.",
	},
	{
		question: "Điền vào chỗ trống (...) để hoàn thành luận điểm sau: Cơ cấu xã hội – giai cấp biến đổi gắn liền và bị quy định bởi (…) ",
		answers: [
			"Cơ cấu kinh tế",
			"Cơ cấu dân số",
			"Cơ cấu dân tộc",
			"Cơ cấu văn hóa",
		],
		correct: 0,
		explanation: "Dựa trên Trang 67 của chương 5 của tài liệu, chỉ ra rằng quy luật biến đổi đầu tiên là: Một là, cơ cấu xã hội - giai cấp biến đổi gắn liền và bị quy định bởi cơ cấu kinh tế.",
	},
	{
		question: "Ở Việt Nam hiện nay, cơ cấu xã hội giai cấp bao gồm:",
		answers: [
			"Giai cấp công nhân",
			"Giai cấp nông dân",
			"Đội ngũ trí thức, đội ngũ doanh nhân",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 66 và Trang 74 của chương 5 của tài liệu, chỉ ra rằng cơ cấu xã hội - giai cấp của thời kỳ quá độ lên chủ nghĩa xã hội bao gồm: giai cấp công nhân, giai cấp nông dân, tầng lớp trí thức, tầng lớp doanh nhân, v.v.",
	},
	{
		question: "Điền vào chỗ trống: Sự biến đổi của (…) tất yếu ảnh hưởng đến sự biến đổi của các cơ cấu xã hội khác và tác động đến sự biến đổi của toàn bộ cơ cấu xã hội.",
		answers: [
			"cơ cấu xã hội - giai cấp",
			"cơ cấu kinh tế",
			"cơ cấu xã hội - dân cư",
			"cơ cấu dân tộc",
		],
		correct: 0,
		explanation: "Dựa trên Trang 66 của chương 5 của tài liệu, chỉ ra rằng: Sự biến đổi của cơ cấu xã hội - giai cấp tất yếu sẽ ảnh hưởng đến sự biến đổi của các cơ cấu xã hội khác và tác động đến sự biến đổi của toàn bộ cơ cấu xã hội.",
	},
	{
		question: "Giai cấp công nhân Việt Nam trong thời kỳ quá độ lên chủ nghĩa xã hội biến đổi theo xu hướng nào?",
		answers: [
			"Xu hướng tri thức hóa",
			"Xu hướng nông dân hóa",
			"Xu hướng dân tộc hóa",
			"Xu hướng khu vực hóa",
		],
		correct: 0,
		explanation: "Dựa trên Trang 74 của chương 5 của tài liệu, chỉ ra rằng Giai cấp công nhân phát triển không ngừng: Bộ phận “công nhân hiện đại”, “công nhân tri thức” ... Trình độ chuyên môn kỹ thuật, kỹ năng nghề nghiệp... ngày càng được nâng cao (tức xu hướng tri thức hóa).",
	},
	{
		question: "Vì sao các giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội vừa có sự đấu tranh vừa có sự liên minh?",
		answers: [
			"Vì nền kinh tế trong thời kỳ quá độ lên chủ nghĩa xã hội là kinh tế thị trường",
			"Vì trình độ văn hóa của các giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội có khác nhau",
			"Vì các giai cấp, tầng lớp vừa có những lợi ích cơ bản thống nhất, vừa có những lợi ích cụ thể khác nhau",
			"Vì đây là quy luật bắt buộc",
		],
		correct: 2,
		explanation: "Dựa trên Trang 72 của chương 5 của tài liệu, chỉ ra rằng quan hệ lợi ích giữa công nhân, nông dân và trí thức bên cạnh sự thống nhất về lợi ích kinh tế chung, vẫn xuất hiện những mâu thuẫn lợi ích ở những mức độ khác nhau. Do vậy quá trình liên minh đồng thời cũng là quá trình giải quyết mâu thuẫn.",
	},
	{
		question: "Cơ cấu xã hội là gì?",
		answers: [
			"Là tổng thể các chế độ xã hội trong lịch sử và mối quan hệ giữa các chế độ xã hội đó",
			"Là tổng thể những cộng đồng người cùng toàn bộ các quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng đó tạo nên",
			"Là tổng thể các hình thái kinh tế - xã hội và sự thay thế các hình thái kinh tế - xã hội trong lịch sử",
			"Là tổng thể các lực lượng lao động trong xã hội và mối quan hệ giữa các lực lượng đó trong nền sản xuất",
		],
		correct: 1,
		explanation: "Dựa trên Trang 65 của chương 5 của tài liệu, chỉ ra rằng: cơ cấu xã hội là những cộng đồng người cùng toàn bộ những mối quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng ấy tạo nên.",
	},
	{
		question: "Điền vào chỗ trống: Ở Việt Nam hiện nay, giai cấp công nhân có vai trò quan trọng đặc biệt, là giai cấp (…) cách mạng thông qua đội tiền phong là ĐCS Việt Nam.",
		answers: [
			"Quản lý",
			"Lãnh đạo",
			"Tiên tiến",
			"Đi đầu",
		],
		correct: 1,
		explanation: "Dựa trên Trang 73 của chương 5 của tài liệu, chỉ ra rằng: Giai cấp công nhân Việt Nam có vai trò quan trọng đặc biệt, là giai cấp lãnh đạo cách mạng thông qua đội tiền phong là Đảng Cộng sản Việt Nam.",
	},
	{
		question: "“Đẩy mạnh công nghiệp hóa, hiện đại hóa; giải quyết tốt mối quan hệ giữa tăng trưởng kinh tế với đảm bảo tiến bộ, công bằng xã hội tạo môi trường và điều kiện thúc đẩy biến đổi cơ cấu xã hội - giai cấp theo hướng tích cực”, đó là...",
		answers: [
			"Phương hướng liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Nội dung liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Giải pháp liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Phương pháp liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
		],
		correct: 0,
		explanation: "Dựa trên Trang 79 của chương 5 của tài liệu, đây là: Một là, đẩy mạnh công nghiệp hóa, hiện đại hóa... Nó thuộc phần Phương hướng cơ bản để xây dựng cơ cấu xã hội - giai cấp và tăng cường liên minh giai cấp.",
	},
	{
		question: "“Thực hiện đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước gắn với phát triển kinh tế tri thức theo định hướng xã hội chủ nghĩa”, đó là một…",
		answers: [
			"Phương hướng liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Nội dung kinh tế của liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Nội dung chính trị của liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Phương pháp liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
		],
		correct: 1,
		explanation: "Dựa trên Trang 76 (kiến thức tổng hợp mục 5.3.2) của chương 5 của tài liệu, đẩy mạnh CNH, HĐH gắn với kinh tế tri thức chính là Nội dung kinh tế của liên minh giai cấp, tầng lớp.",
	},
	{
		question: "“Xây dựng Nhà nước pháp quyền xã hội chủ nghĩa, từng bước hoàn thiện nền dân chủ xã hội chủ nghĩa”, đó là một…",
		answers: [
			"Phương hướng liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Nội dung kinh tế của liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Nội dung chính trị của liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
			"Phương pháp liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH ở Việt Nam",
		],
		correct: 2,
		explanation: "Dựa trên Trang 77 của chương 5 của tài liệu, chỉ ra rằng Nội dung chính trị của liên minh đòi hỏi phải hoàn thiện, phát huy dân chủ xã hội chủ nghĩa và quyền làm chủ của nhân dân, cũng như xây dựng Nhà nước pháp quyền xã hội chủ nghĩa.",
	},
	{
		question: "Những cộng đồng người cùng toàn bộ những mối quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng ấy tạo nên là nội dung thể hiện khái niệm nào dưới đây?",
		answers: [
			"Cơ cấu xã hội.",
			"Cơ cấu giai cấp.",
			"Cơ cấu dân tộc.",
			"Cơ cấu dân cư.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 65 của chương 5 của tài liệu, chỉ ra rằng cơ cấu xã hội là những cộng đồng người cùng toàn bộ những mối quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng ấy tạo nên.",
	},
	{
		question: "Nội dung nào dưới đây không phải là sự biến đổi có tính quy luật của cơ cấu xã hội - giai cấp trong thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Cơ cấu xã hội - giai cấp biến đổi gắn liền và bị quy định bởi cơ cấu kinh tế.",
			"Cơ cấu xã hội - giai cấp biến đổi phức tạp, đa dạng, làm xuất hiện các tầng lớp xã hội mới.",
			"Cơ cấu xã hội - giai cấp biến đổi trong mối quan hệ vừa đấu tranh, vừa liên minh, dẫn đến sự xích lại gần nhau giữa các giai tầng trong xã hội.",
			"Cơ cấu xã hội - giai cấp biến đối và chịu sự tác động của sự biến đổi dân số, tôn giáo.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 67 đến Trang 69 của chương 5 của tài liệu, 3 quy luật biến đổi cơ bản của cơ cấu XH-GC gồm (1) Gắn với cơ cấu kinh tế, (2) Đa dạng, phức tạp xuất hiện tầng lớp mới, (3) Trong mối quan hệ vừa đấu tranh vừa liên minh. Đáp án D không thuộc 3 tính quy luật này.",
	},
	{
		question: "Sự biến đổi của cơ cấu xã hội - giai cấp gắn liền và được quy định bởi sự biến đổi của cơ cấu nào dưới đây?",
		answers: [
			"Cơ cấu dân số.",
			"Cơ cấu kinh tế.",
			"Cơ cấu dân tộc.",
			"Cơ cấu dân cư.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 67 của chương 5 của tài liệu, chỉ ra rằng: Một là, cơ cấu xã hội - giai cấp biến đổi gắn liền và bị quy định bởi cơ cấu kinh tế.",
	},
	{
		question: "“Trong thời đại chuyên chính vô sản, các giai cấp vẫn tồn tại, nhưng bộ mặt của mỗi một giai cấp đều có thay đổi, quan hệ qua lại giữa các giai cấp cũng biến đổi. Cuộc đấu tranh giai cấp chưa chấm dứt dưới thời chuyên chính vô sản, nó chỉ diễn biến ra dưới những hình thức khác mà thôi” là câu nói của…",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 69 của chương 5 của tài liệu, V.I.Lênin nhấn mạnh về sự tồn tại của giai cấp và hình thức đấu tranh giai cấp mới trong thời kỳ quá độ (chuyên chính vô sản).",
	},
	{
		question: "Giai cấp, tầng lớp nào dưới đây được coi là “người bạn đồng minh tự nhiên” của giai cấp công nhân?",
		answers: [
			"Tư sản.",
			"Nông dân.",
			"Trí thức.",
			"Doanh nhân.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 70 của chương 5 của tài liệu, chỉ ra rằng giai cấp công nhân không tổ chức liên minh với “người bạn đồng minh tự nhiên” của mình là giai cấp nông dân sẽ dẫn tới thất bại đơn độc.",
	},
	{
		question: "Trong luận điểm: “Trước sự liên minh của các đại biểu khoa học, giai cấp vô sản và giới kĩ thuật, không một thế lực đen tối nào đứng vững được”, V.I. Lênin đã nhấn mạnh tới vai trò của giai cấp, tầng lớp nào dưới đây trong khối liên minh giai cấp?",
		answers: [
			"Trí thức.",
			"Doanh nhân.",
			"Tư sản.",
			"Nông dân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 71 của chương 5 của tài liệu, chỉ ra rằng: Khẳng định vai trò của trí thức trong khối liên minh, V.I.Lênin viết: “Trước sự liên minh của các đại biểu khoa học...",
	},
	{
		question: "Theo V.I. Lênin, để giai cấp vô sản giữ được vai trò lãnh đạo và chính quyền nhà nước, nguyên tắc cao nhất của chuyên chính là duy trì khối liên minh giữa…",
		answers: [
			"giai cấp vô sản và tầng lớp doanh nhân.",
			"giai cấp vô sản và nông dân.",
			"giai cấp nông dân và giai cấp tư sản.",
			"tầng lớp doanh nhân và đội ngũ trí thức.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 70 và 71 của chương 5 của tài liệu, chỉ ra rằng: Nguyên tắc cao nhất của chuyên chính là duy trì khối liên minh giữa giai cấp vô sản và nông dân để giai cấp vô sản có thể giữ được vai trò lãnh đạo.",
	},
	{
		question: "Trong quá trình xây dựng chủ nghĩa xã hội, liên minh giữa giai cấp công nhân, giai cấp nông dân và tầng lớp trí thức trong lĩnh vực nào dưới đây giữ vai trò quyết định?",
		answers: [
			"Chính trị.",
			"Kinh tế.",
			"Văn hoá.",
			"Tư tưởng.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 76 của chương 5 của tài liệu, chỉ ra rằng Nội dung kinh tế của liên minh: Đây là nội dung cơ bản, quyết định nhất, là cơ sở vật chất kỹ thuật của liên minh.",
	},
	{
		question: "Yếu tố nào dưới đây quyết định sự liên minh giữa giai cấp công nhân, giai cấp nông dân và tầng lớp trí thức?",
		answers: [
			"Mong muốn của giai cấp công nhân.",
			"Cùng một kẻ thù là giai cấp tư sản.",
			"Nhu cầu lợi ích kinh tế.",
			"Mục tiêu về chính trị của giai cấp công nhân.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 72 của chương 5 của tài liệu, chỉ ra rằng Việc hình thành khối liên minh giai cấp công nhân với giai cấp nông dân và tầng lớp trí thức cùng xuất phát từ chính nhu cầu và lợi ích kinh tế của họ.",
	},
	{
		question: "Câu nói “Vô sản tất cả các nước và các dân tộc bị áp bức, đoàn kết lại” là của…",
		answers: [
			"C. Mác.",
			"Ph.Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 44 và Trang 91 của tài liệu, chỉ ra rằng Khẩu hiệu 'Vô sản tất cả các nước và các dân tộc bị áp bức đoàn kết lại' được phát triển bởi V.I. Lênin trong thời kỳ chủ nghĩa đế quốc.",
	},
	{
		question: "Trong thời kì quá độ lên chủ nghĩa xã hội, các giai cấp, tầng lớp liên minh với nhau trên những lĩnh vực nào dưới đây?",
		answers: [
			"Kinh tế, chính trị, xã hội.",
			"Kinh tế, chính trị, tôn giáo.",
			"Kinh tế, chính trị, văn hoá - xã hội.",
			"Kinh tế, văn hoá, xã hội.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 76 đến Trang 78 của chương 5 của tài liệu, khối liên minh được thực hiện đồng bộ qua 3 nội dung: Nội dung kinh tế; Nội dung chính trị; Nội dung văn hóa xã hội.",
	},
	{
		question: "Lực lượng nào dưới đây được Đảng ta coi là lực lượng đặc biệt và chủ trương xây dựng thành lực lượng vững mạnh?",
		answers: [
			"Trí thức.",
			"Doanh nhân.",
			"Thanh niên.",
			"Công nhân.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 75 của chương 5 của tài liệu, chỉ ra rằng: Đội ngũ doanh nhân đang phát triển nhanh, Đảng ta đã chủ trương xây dựng đội ngũ doanh nhân lớn mạnh, có năng lực, trình độ và phẩm chất (lực lượng đặc thù trong nền kinh tế thị trường).",
	},
	{
		question: "Trong thời kì quá độ lên chủ nghĩa xã hội, giai cấp, tầng lớp nào dưới đây có xu hướng giảm dần về số lượng và tỉ lệ trong cơ cấu xã hội - giai cấp?",
		answers: [
			"Nông dân.",
			"Trí thức.",
			"Công nhân.",
			"Doanh nhân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 73 của chương 5 của tài liệu, chỉ ra rằng cùng với sự nghiệp công nghiệp hóa, hiện đại hóa, giai cấp nông dân có xu hướng chuyển dịch, giảm dần về số lượng và tỉ trọng trong lực lượng lao động xã hội.",
	},
	{
		question: "Đảng ta xác định xây dựng vững mạnh giai cấp, tầng lớp nào dưới đây là trực tiếp nâng tầm trí tuệ của dân tộc, sức mạnh của đất nước, nâng cao năng lực lãnh đạo của Đảng và chất lượng hoạt động của hệ thống chính trị?",
		answers: [
			"Trí thức.",
			"Công nhân.",
			"Doanh nhân.",
			"Thanh niên.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 74 và 75 của chương 5 của tài liệu, chỉ ra rằng Xây dựng đội ngũ trí thức vững mạnh là trực tiếp nâng tầm trí tuệ của dân tộc, sức mạnh của đất nước, nâng cao năng lực lãnh đạo của Đảng.",
	},
	{
		question: "Giai cấp, tầng lớp nào dưới đây được coi là rường cột của nước nhà, chủ nhân tương lai của đất nước?",
		answers: [
			"Thanh niên.",
			"Công nhân.",
			"Trí thức.",
			"Doanh nhân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 75 của chương 5 của tài liệu (Kiến thức cơ bản về cơ cấu nhóm tầng lớp xã hội), Đội ngũ thanh niên luôn được Đảng và Bác Hồ coi là rường cột của nước nhà, chủ nhân tương lai của đất nước.",
	},
	{
		question: "Xét dưới góc độ kinh tế, nội dung nào dưới đây không phải là nguyên nhân của liên minh giai cấp trong thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Yêu cầu khách quan của quá trình công nghiệp hoá, hiện đại hoá.",
			"Sự chuyển dịch cơ cấu kinh tế.",
			"Nhu cầu lợi ích kinh tế của các giai cấp, tầng lớp.",
			"Yêu cầu khách quan của đấu tranh giành chính quyền.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 71 của chương 5 của tài liệu (Mục 5.2.2 Xét từ góc độ kinh tế), 'Yêu cầu khách quan của đấu tranh giành chính quyền' thuộc về phương diện chính trị - xã hội, không phải là nguyên nhân kinh tế.",
	},
	{
		question: "Sự biến đổi đa dạng, phức tạp của cơ cấu xã hội - giai cấp ở Việt Nam trong thời kì quá độ lên chủ nghĩa xã hội là do…",
		answers: [
			"duy trì cơ chế kế hoạch hoá tập trung quan liêu bao cấp.",
			"sự đa dạng của văn hoá, tôn giáo, tín ngưỡng.",
			"sự đa dạng về tộc người.",
			"chuyển đổi cơ chế kinh tế kế hoạch hoá tập trung sang kinh tế thị trường.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 73 của chương 5 của tài liệu, chỉ ra rằng Từ Đại hội VI (1986), Việt Nam chuyển mạnh sang cơ chế thị trường... Sự chuyển đổi trong cơ cấu kinh tế đã dẫn đến những biến đổi phức tạp, đa dạng trong cơ cấu xã hội - giai cấp.",
	},
	{
		question: "Giai cấp, tầng lớp nào hiện nay không còn trong cơ cấu xã hội - giai cấp ở Việt Nam?",
		answers: [
			"Nông dân.",
			"Trí thức.",
			"Địa chủ.",
			"Công nhân.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 72 của chương 5 của tài liệu, sau thắng lợi cách mạng, các giai cấp bóc lột (như địa chủ, tư sản mại bản) đã bị đánh đổ và không còn duy trì vị trí thống trị bóc lột trong cơ cấu xã hội ở Việt Nam.",
	},
	{
		question: "Nội dung nào dưới đây không phải là vai trò của giai cấp công nhân trong thời kì quá độ lên chủ nghĩa xã hội ở Việt Nam?",
		answers: [
			"Là giai cấp lãnh đạo.",
			"Là giai cấp đại diện cho phương thức sản xuất mới.",
			"Là lực lượng lao động sáng tạo đặc biệt.",
			"Là lực lượng nòng cốt trong khối liên minh giai cấp.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 74 của chương 5 của tài liệu, vai trò 'Lực lượng lao động sáng tạo đặc biệt quan trọng' được Đảng ta gắn liền với Đội ngũ trí thức, không dùng để chỉ đặc quyền của riêng giai cấp công nhân.",
	},
	{
		question: "Trong thời kì quá độ lên chủ nghĩa xã hội ở Việt Nam, giai cấp, tầng lớp nào dưới đây được coi là lực lượng lao động sáng tạo đặc biệt quan trọng?",
		answers: [
			"Nông dân.",
			"Doanh nhân.",
			"Trí thức.",
			"Công nhân.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 74 của chương 5 của tài liệu, chỉ ra rõ rằng: Đội ngũ trí thức là lực lượng lao động sáng tạo đặc biệt quan trọng trong tiến trình đẩy mạnh công nghiệp hóa, hiện đại hóa.",
	},
	{
		question: "Vấn đề liên minh giai cấp công nhân với giai cấp nông dân và đội ngũ trí thức, được Đảng ta khẳng định lần đầu tiên tại…",
		answers: [
			"Đại hội đại biểu toàn quốc lần thứ II (1951).",
			"Đại hội đại biểu toàn quốc lần thứ III (1960).",
			"Đại hội đại biểu toàn quốc lần thứ IV (1976).",
			"Đại hội đại biểu toàn quốc lần thứ V (1982).",
		],
		correct: 0,
		explanation: "Dựa trên sự phát triển đường lối chiến lược của Đảng trong tài liệu, khối liên minh Công - Nông - Trí thức được Đảng Cộng sản Việt Nam (Đảng Lao động Việt Nam bấy giờ) khẳng định làm nền tảng của mặt trận đoàn kết từ Đại hội II (năm 1951).",
	},
	{
		question: "Hiện nay ở nước ta, giai cấp, tầng lớp nào dưới đây giữ vai trò lãnh đạo khối liên minh?",
		answers: [
			"Công nhân.",
			"Doanh nhân.",
			"Trí thức.",
			"Nông dân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 73 và 78 của chương 5 của tài liệu, Giai cấp công nhân giữ vai trò lãnh đạo cách mạng thông qua đội tiền phong là Đảng Cộng sản Việt Nam, do vậy nắm giữ vai trò lãnh đạo khối liên minh.",
	},
	{
		question: "Liên minh giữa các giai cấp, tầng lớp trong thời kì quá độ lên chủ nghĩa xã hội phải dựa trên lập trường tư tưởng chính trị của giai cấp, tầng lớp nào dưới đây?",
		answers: [
			"Công nhân.",
			"Doanh nhân.",
			"Trí thức.",
			"Nông dân.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 77 của chương 5 của tài liệu, nội dung chính trị của liên minh thể hiện ở việc giữ vững lập trường chính trị - tư tưởng của giai cấp công nhân.",
	},
	{
		question: "Nội dung nào dưới đây không phải là nội dung chính trị của liên minh giai cấp, tầng lớp trong thời kì quá độ lên chủ nghĩa xã hội ở Việt Nam?",
		answers: [
			"Giữ vững vai trò lãnh đạo của Đảng Cộng sản Việt Nam.",
			"Bảo vệ vững chắc chế độ chính trị.",
			"Tăng cường các hình thức giao lưu hợp tác liên kết giữa công nghiệp - nông nghiệp - khoa học công nghệ.",
			"Xây dựng hoàn thiện nền dân chủ xã hội chủ nghĩa.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 77 của chương 5 của tài liệu, hoạt động 'giao lưu hợp tác liên kết kinh tế giữa công nghiệp - nông nghiệp - khoa học và công nghệ' thuộc về Nội dung kinh tế, không phải là nội dung chính trị.",
	},
	{
		question: "Nội dung kinh tế xuyên suốt của thời kì quá độ lên chủ nghĩa xã hội ở Việt Nam là",
		answers: [
			"đẩy mạnh công nghiệp hoá, hiện đại hoá đất nước gắn với phát triển kinh tế tri thức theo định hướng xã hội chủ nghĩa.",
			"xác định đúng tiềm lực kinh tế và nhu cầu kinh tế của các giai cấp, tầng lớp và toàn xã hội.",
			"chuyển giao và ứng dụng khoa học kĩ thuật và công nghệ hiện đại vào sản xuất.",
			"xác định đúng cơ cấu kinh tế, phát triển kinh tế thị trường.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 76 (Liên kết khối kinh tế) của chương 5 của tài liệu, nội dung kinh tế cốt lõi hiện nay là việc đẩy mạnh công nghiệp hóa, hiện đại hóa đất nước gắn với nền kinh tế tri thức.",
	},
	{
		question: "Nội dung nào dưới đây không phải là nội dung kinh tế của liên minh giai cấp, tầng lớp trong thời kì quá độ lên chủ nghĩa xã hội ở Việt Nam?",
		answers: [
			"Xác định đúng tiềm lực kinh tế và nhu cầu kinh tế của các giai cấp, tầng lớp.",
			"Xác định đúng cơ cấu kinh tế.",
			"Xây dựng nhà nước pháp quyền xã hội chủ nghĩa của nhân dân, do nhân dân, vì nhân dân.",
			"Chuyển giao và ứng dụng khoa học kĩ thuật và công nghệ hiện đại vào sản xuất kinh doanh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 78 của chương 5 của tài liệu, nhiệm vụ 'Xây dựng Nhà nước pháp quyền xã hội chủ nghĩa của nhân dân...' nằm hoàn toàn ở Nội dung chính trị của liên minh.",
	},
];