const cnxhChapter3 = [
	{
		question: "Nguyên nhân sâu xa dẫn đến sự thay thế hình thái kinh tế - xã hội tư bản chủ nghĩa bằng hình thái kinh tế - xã hội cộng sản chủ nghĩa là gì?",
		answers: [
			"Mâu thuẫn giữa tư liệu lao động với đối tượng lao động trong nền sản xuất hàng hóa tư bản chủ nghĩa",
			"Mâu thuẫn giữa lực lượng sản xuất mang tính xã hội hóa ngày càng cao với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất chủ yếu",
			"Mâu thuẫn giữa phương thức sản xuất cộng sản chủ nghĩa với phương thức sản xuất tư bản chủ nghĩa",
			"Mâu thuẫn giữa các giai cấp, tầng lớp lao động trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên Trang 36 và 37 của chương 3 của tài liệu, chỉ ra rằng Mâu thuẫn giữa tính chất xã hội hóa của lực lượng sản xuất với chế độ chiếm hữu tư nhân tư bản chủ nghĩa đối với tư liệu sản xuất trở thành mâu thuẫn kinh tế cơ bản... là nguyên nhân sâu xa dẫn đến sự diệt vong của CNTB.",
	},
	{
		question: "Tiêu chí nào là quan trọng nhất để C. Mác phân chia hai giai đoạn phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa?",
		answers: [
			"Ý thức giác ngộ của nhân dân lao động",
			"Trình độ quản lý của Nhà nước",
			"Trình độ xã hội hóa của lực lượng sản xuất",
			"Trình độ dân trí của xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 34 và 40 của chương 3 của tài liệu, chỉ ra rằng Học thuyết hình thái kinh tế - xã hội dựa trên tiêu chuẩn thực sự duy vật, trong đó trình độ phát triển và tính chất xã hội hóa của lực lượng sản xuất là thước đo cơ bản để phân chia các giai đoạn phát triển.",
	},
	{
		question: "Trong các dự báo sau đây của C. Mác và Ph. Ăngghen, dự báo nào thuộc giai đoạn thấp của hình thái kinh tế - xã hội cộng sản chủ nghĩa?",
		answers: [
			"Sự đối lập giữa lao động trí óc và lao động chân tay không còn",
			"Không còn sự phân chia giai cấp",
			"Mọi người làm hết năng lực, hưởng theo nhu cầu",
			"Mọi người làm theo năng lực, hưởng theo lao động, vẫn còn pháp quyền tư sản",
		],
		correct: 3,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng ở giai đoạn đầu (chủ nghĩa xã hội), chế độ phân phối là phân phối chủ yếu theo lao động (nguyên tắc làm theo năng lực, hưởng theo lao động).",
	},
	{
		question: "Trong các dự báo của C. Mác, dự báo nào thuộc giai đoạn cao của hình thái kinh tế - xã hội cộng sản chủ nghĩa?",
		answers: [
			"Xã hội chưa thoát khỏi tàn tích của chủ nghĩa tư bản",
			"Xã hội vẫn còn sự phân chia giai cấp đối kháng, trong đó giai cấp công nhân là giai cấp thống trị xã hội",
			"Sự phát triển tự do của mỗi người là điều kiện cho sự phát triển tự do của mọi người",
			"Vẫn còn sự tồn tại kết cấu kinh tế của chủ nghĩa tư bản bên cạnh kết cấu kinh tế của chủ nghĩa xã hội",
		],
		correct: 2,
		explanation: "Dựa trên Trang 38 của chương 3 của tài liệu, chỉ ra rằng khi dự báo về xã hội tương lai (giai đoạn cao), C.Mác khẳng định: Thay cho xã hội tư bản cũ... sẽ xuất hiện một liên hợp, trong đó sự phát triển tự do của mỗi người là điều kiện phát triển tự do của tất cả mọi người.",
	},
	{
		question: "Tiền đề vật chất cho sự ra đời của chủ nghĩa xã hội là gì?",
		answers: [
			"Là điện khí hóa nền sản xuất",
			"Là tự động hóa nền sản xuất",
			"Là quá trình tin học hóa",
			"Là xã hội hóa lực lượng sản xuất",
		],
		correct: 3,
		explanation: "Dựa trên Trang 36 của chương 3 của tài liệu, chỉ ra rằng trong xã hội tư bản chủ nghĩa, lực lượng sản xuất càng được cơ khí hóa, hiện đại hóa càng mang tính xã hội hóa cao... tạo ra cơ sở vật chất cho sự ra đời của chủ nghĩa xã hội.",
	},
	{
		question: "Chỉ ra luận điểm chính xác nhất?",
		answers: [
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu phong kiến",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất hàng hóa",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất tự cấp tự túc",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu tư bản chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng từ chủ nghĩa tư bản, nhân loại chỉ có thể tiến thẳng lên chủ nghĩa xã hội, nghĩa là thiết lập chế độ công hữu về các tư liệu sản xuất chủ yếu (tức là xóa bỏ chế độ tư hữu tư bản chủ nghĩa).",
	},
	{
		question: "Chỉ ra luận điểm KHÔNG chính xác?",
		answers: [
			"Giữa xã hội tư bản chủ nghĩa và xã hội xã hội chủ nghĩa là thời kỳ cải biến cách mạng lâu dài và phức tạp",
			"Nhà nước trong thời kỳ quá độ lên chủ nghĩa xã hội là nền chuyên chính cách mạng của giai cấp công nhân",
			"Trong thời kỳ quá độ có thể và cần thủ tiêu mọi tàn tích của chủ nghĩa tư bản",
			"Thời kỳ quá độ lên chủ nghĩa xã hội còn tồn tại nhiều tư tưởng - văn hóa cũ và mới đan xen, đấu tranh lẫn nhau",
		],
		correct: 2,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Ph.Ăngghen dứt khoát cho rằng: 'Không, không thể được cũng như không thể làm cho lực lượng sản xuất hiện có tăng lên ngay lập tức...', do đó không thể thủ tiêu ngay lập tức và toàn bộ mọi tàn tích tư hữu tư bản chủ nghĩa.",
	},
	{
		question: "Đặc điểm chủ yếu của thời kỳ quá độ lên chủ nghĩa xã hội là gì?",
		answers: [
			"Chính quyền của giai cấp lao động được thành lập, nhân dân lao động hoàn toàn làm chủ xã hội",
			"Hệ tư tưởng chính trị của giai cấp công nhân là hệ tư tưởng duy nhất tồn tại trong xã hội. Giai cấp công nhân là chủ thể toàn bộ giá trị văn hóa tinh thần của xã hội",
			"Tồn tại đan xen và đấu tranh lẫn nhau giữa những nhân tố của xã hội mới và những tàn dư của xã hội cũ trên mọi lĩnh vực của đời sống xã hội",
			"Tồn tại kinh tế thị trường định hướng xã hội chủ nghĩa, ở đó, các chủ thể kinh tế đều chịu sự chi phối của quy luật thị trường",
		],
		correct: 2,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Xã hội của thời kỳ quá độ là xã hội có sự đan xen của nhiều tàn dư về mọi phương diện kinh tế, đạo đức, tinh thần của chủ nghĩa tư bản và những yếu tố mới mang tính chất xã hội chủ nghĩa.",
	},
	{
		question: "Thời kỳ quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội nằm trong hình thái kinh tế - xã hội nào?",
		answers: [
			"Chiếm hữu nô lệ",
			"Phong kiến",
			"Tư bản chủ nghĩa",
			"Cộng sản chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng Hình thái kinh tế - xã hội cộng sản chủ nghĩa phát triển từ thấp lên cao... Giữa xã hội TBCN và xã hội CSCN là một thời kỳ quá độ. Nó thuộc về tiến trình mở đầu của hình thái kinh tế - xã hội CSCN.",
	},
	{
		question: "Chọn phương án đúng nhất: Chủ nghĩa xã hội dựa trên chế độ sở hữu nào về tư liệu sản xuất chủ yếu?",
		answers: [
			"Tư hữu",
			"Tập thể",
			"Hỗn hợp",
			"Công hữu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội có nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và chế độ công hữu về tư liệu sản xuất chủ yếu.",
	},
	{
		question: "Đặc điểm của thời kỳ quá độ lên chủ nghĩa xã hội trên lĩnh vực kinh tế là gì?",
		answers: [
			"Còn tồn tại nhiều hệ tư tưởng khác nhau",
			"Còn tồn tại nhiều thành phần kinh tế khác nhau",
			"Còn tồn tại giai cấp đối kháng và đấu tranh giai cấp",
			"Còn tồn tại nhiều tàn dư của chế độ cũ để lại",
		],
		correct: 1,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực kinh tế: Thời kỳ quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội, về phương diện kinh tế, tất yếu tồn tại nền kinh tế nhiều thành phần.",
	},
	{
		question: "Đặc điểm của thời kỳ quá độ lên chủ nghĩa xã hội trên lĩnh vực chính trị là gì?",
		answers: [
			"Còn tồn tại nhiều hình thức sở hữu khác nhau",
			"Còn tồn tại nhiều thành phần kinh tế khác nhau",
			"Còn tồn tại giai cấp đối kháng và đấu tranh giai cấp",
			"Còn tồn tại tàn dư tư tưởng và văn hóa của chế độ cũ để lại",
		],
		correct: 2,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực chính trị: ... là tiếp tục cuộc đấu tranh giai cấp giữa giai cấp vô sản đã chiến thắng nhưng chưa phải đã toàn thắng với giai cấp tư sản đã thất bại.",
	},
	{
		question: "Thời kì quá độ lên CNXH ở Việt Nam còn những hình thức sở hữu nào về tư liệu sản xuất?",
		answers: [
			"Tư nhân",
			"Tập thể, công hữu",
			"Hỗn hợp",
			"Tất cả các nội dung đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu, chỉ ra rằng Điều đó có nghĩa là trong thời kỳ quá độ còn nhiều hình thức sở hữu, nhiều thành phần kinh tế.",
	},
	{
		question: "Cơ sở kinh tế của chủ nghĩa xã hội khác về bản chất so với chủ nghĩa tư bản là:",
		answers: [
			"Chế độ sở hữu về tư liệu sản xuất",
			"Chế độ tư hữu về tư liệu sản xuất",
			"Chế độ công hữu về những tư liệu sản xuất chủ yếu",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Đặc trưng về phương diện kinh tế của chủ nghĩa xã hội: chế độ công hữu về tư liệu sản xuất chủ yếu, khác biệt hoàn toàn với tư hữu TBCN.",
	},
	{
		question: "Đặc điểm của thời kỳ quá độ lên chủ nghĩa xã hội trên lĩnh vực tư tưởng - văn hóa là gì?",
		answers: [
			"Còn tồn tại nhiều hình thức sở hữu khác nhau",
			"Còn tồn tại nhiều thành phần kinh tế khác nhau",
			"Còn tồn tại giai cấp đối kháng và đấu tranh giai cấp",
			"Còn tồn tại nhiều tư tưởng - văn hóa cũ và mới đan xen, đấu tranh lẫn nhau",
		],
		correct: 3,
		explanation: "Dựa trên Trang 47 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực tư tưởng - văn hóa: Thời kỳ quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội còn tồn tại nhiều tư tưởng khác nhau... tiếp thu giá trị văn hóa... tồn tại đan xen.",
	},
	{
		question: "Thực chất của thời kỳ quá độ lên chủ nghĩa xã hội là gì?",
		answers: [
			"Là tiếp tục cuộc đấu tranh giai cấp giữa giai cấp công nhân, nhân dân lao động chống lại giai cấp tư sản và các thế lực đi ngược lại lợi ích của giai cấp công nhân và nhân dân lao động",
			"Là phát triển kinh tế hàng hóa nhiều thành phần theo định hướng xã hội chủ nghĩa",
			"Là duy trì nhiều hình thức phân phối khác nhau, trong đó phân phối theo lao động là cơ bản",
			"Là duy trì nhiều hình thức sở hữu khác nhau, trong đó sở hữu toàn dân là hình thức sở hữu chủ yếu",
		],
		correct: 0,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng xét về bản chất chính trị, thời kỳ quá độ là việc thiết lập chuyên chính vô sản, thực chất là tiếp tục cuộc đấu tranh giai cấp giữa giai cấp vô sản đã chiến thắng với giai cấp tư sản đã thất bại.",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống: “Giữa xã hội tư bản chủ nghĩa và xã hội cộng sản chủ nghĩa là một thời kỳ cải biến cách mạng từ xã hội nọ sang xã hội kia. Thích ứng với thời kỳ ấy là một (...), và nhà nước của thời kỳ ấy không thể là cái gì khác hơn là nền chuyên chính cách mạng của giai cấp vô sản”.",
		answers: [
			"Thời kỳ khó khăn, phức tạp và lâu dài",
			"Thời kỳ phát triển kinh tế thị trường",
			"Thời kỳ quá độ chính trị",
			"Thời kỳ cải biến nền văn hóa cũ",
		],
		correct: 2,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng C.Mác khẳng định: Giữa xã hội tư bản chủ nghĩa và xã hội cộng sản chủ nghĩa là một thời kỳ cải biến cách mạng... Thích ứng với thời kỳ ấy là một thời kỳ quá độ chính trị.",
	},
	{
		question: "Chỉ ra luận điểm KHÔNG chính xác?",
		answers: [
			"Chủ nghĩa xã hội là một xã hội tốt đẹp, xóa bỏ mọi hình thức sở hữu",
			"Chủ nghĩa xã hội là giai đoạn đầu của hình thái kinh tế-xã hội cộng sản chủ nghĩa",
			"Thời kỳ quá độ là thời kỳ tồn tại đan xen những yếu tố của xã hội cũ và những nhân tố của xã hội mới",
			"Xã hội hóa lực lượng sản xuất là cơ sở vật chất chủ yếu cho sự ra đời của chủ nghĩa xã hội",
		],
		correct: 0,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội xây dựng dựa trên chế độ 'công hữu về tư liệu sản xuất chủ yếu', nó xóa bỏ sở hữu tư nhân tư bản chủ nghĩa chứ không phải 'xóa bỏ mọi hình thức sở hữu'.",
	},
	{
		question: "Đối với những nước chưa trải qua quá trình công nghiệp hóa tư bản chủ nghĩa, thời kỳ quá độ có thể phải kéo dài với nhiệm vụ trọng tâm là:",
		answers: [
			"Xây dựng quan hệ sản xuất xã hội chủ nghĩa",
			"Xây dựng nền văn hóa xã hội chủ nghĩa",
			"Công nghiệp hóa tư bản chủ nghĩa",
			"Công nghiệp hóa xã hội chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu, chỉ ra rằng đối với những nước quá độ gián tiếp bỏ qua CNTB, nhiệm vụ trọng tâm là phải phát triển nhanh lực lượng sản xuất, xây dựng nền kinh tế hiện đại (tức là tiến hành CNH, HĐH xã hội chủ nghĩa).",
	},
	{
		question: "Đặc điểm nổi bật của thời kỳ quá độ lên chủ nghĩa xã hội là:",
		answers: [
			"Chỉ tồn tại những yếu tố của xã hội cũ",
			"Chỉ tồn tại những nhân tố mới của chủ nghĩa xã hội",
			"Những yếu tố của xã hội cũ đan xen với những nhân tố mới của chủ nghĩa xã hội",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Xã hội của thời kỳ quá độ là xã hội có sự đan xen của nhiều tàn dư về mọi phương diện kinh tế, đạo đức... và những yếu tố mới mang tính chất xã hội chủ nghĩa.",
	},
	{
		question: "Điền vào chỗ trống để hoàn thiện luận điểm của C. Mác và Ph. Ăngghen: “Đặc trưng của (...) không phải là xóa bỏ chế độ sở hữu nói chung, mà là xóa bỏ chế độ sở hữu tư sản”.",
		answers: [
			"Chủ nghĩa xã hội",
			"Chủ nghĩa tư bản",
			"Chủ nghĩa cộng sản",
			"Thời kỳ quá độ lên chủ nghĩa xã hội",
		],
		correct: 2,
		explanation: "Dựa trên bản chất luận điểm của C.Mác trong Tuyên ngôn của Đảng Cộng sản (được nhắc xuyên suốt lý luận sở hữu chương 2 & 3), đặc trưng cốt lõi của 'Chủ nghĩa cộng sản' là xóa bỏ sở hữu tư sản.",
	},
	{
		question: "Thực chất của con đường quá độ lên chủ nghĩa xã hội ở Việt Nam là gì?",
		answers: [
			"Là bỏ qua cả những thành tựu và hạn chế của chủ nghĩa tư bản",
			"Là bỏ qua việc xác lập vị trí thống trị của quan hệ sản xuất và kiến trúc thượng tầng tư bản chủ nghĩa",
			"Là bỏ qua sự phát triển của nền sản xuất hàng hóa",
			"Là bỏ qua sự phát triển của nền đại công nghiệp tiến thẳng lên kinh tế tri thức",
		],
		correct: 1,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu, chỉ ra rằng quá độ lên chủ nghĩa xã hội bỏ qua chế độ tư bản chủ nghĩa, tức là bỏ qua việc xác lập vị trí thống trị của quan hệ sản xuất và kiến trúc thượng tầng tư bản chủ nghĩa.",
	},
	{
		question: "Đặc điểm của con đường quá độ lên chủ nghĩa xã hội ở Việt Nam là gì?",
		answers: [
			"Quá độ trực tiếp từ chủ nghĩa tư bản lên chủ nghĩa xã hội",
			"Quá độ lên chủ nghĩa xã hội bỏ qua chế độ tư bản chủ nghĩa",
			"Quá độ lên chủ nghĩa xã hội bỏ qua hình thái kinh tế - xã hội tư bản chủ nghĩa",
			"Quá độ lên chủ nghĩa xã hội từ chủ nghĩa tư bản phát triển ở mức độ trung bình",
		],
		correct: 1,
		explanation: "Dựa trên Trang 47 và 48 của chương 3 của tài liệu, chỉ ra rằng Đặc điểm quá độ lên chủ nghĩa xã hội ở Việt Nam là bỏ qua chế độ tư bản chủ nghĩa.",
	},
	{
		question: "Chọn phương án đúng nhất: Đặc điểm về mặt kinh tế trong thời kỳ quá độ lên chủ nghĩa xã hội ở Việt Nam hiện nay là tồn tại:",
		answers: [
			"Các thành phần kinh tế phong kiến",
			"Các thành phần kinh tế tư bản chủ nghĩa",
			"Các thành phần kinh tế xã hội chủ nghĩa",
			"Nền kinh tế nhiều thành phần",
		],
		correct: 3,
		explanation: "Dựa trên Trang 48 và 49 của chương 3 của tài liệu, chỉ ra rằng trong thời kỳ quá độ còn nhiều hình thức sở hữu, nhiều thành phần kinh tế.",
	},
	{
		question: "Đặc điểm về mặt chính trị trong thời kỳ quá độ lên chủ nghĩa xã hội ở Việt Nam là tồn tại:",
		answers: [
			"Kết cấu xã hội - giai cấp đa dạng, phức tạp",
			"Kết cấu xã hội - giai cấp đơn nhất",
			"Kết cấu xã hội - giai cấp thuần nhất",
			"Chỉ còn giai cấp công nhân",
		],
		correct: 0,
		explanation: "Dựa trên Trang 47 của chương 3 của tài liệu (phần chuyển ý kết cấu XH), chỉ ra rằng Do kết cấu nền kinh tế nhiều thành phần quy định nên trong thời kỳ quá độ còn tồn tại nhiều giai cấp, tầng lớp và sự khác biệt giữa các giai cấp (đa dạng, phức tạp).",
	},
	{
		question: "Trong Đại hội XIII, Đảng ta xác định đến năm 2045, Việt Nam sẽ là…",
		answers: [
			"Là nước đang phát triển, có công nghiệp theo hướng hiện đại, vượt qua mức thu nhập trung bình thấp",
			"Là nước đang phát triển, có công nghiệp hiện đại, thu nhập trung bình cao.",
			"Là nước phát triển, có thu nhập cao",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 2,
		explanation: "Dựa trên Trang 51 của chương 3 của tài liệu, chỉ ra rằng Đến giữa năm 2045, kỷ niệm 100 năm thành lập nước... Trở thành nước phát triển, thu nhập cao.",
	},
	{
		question: "Chọn câu trả lời đúng nhất: Cơ sở vật chất - kỹ thuật của chủ nghĩa xã hội là…",
		answers: [
			"Nền sản xuất nông nghiệp có trình độ cao",
			"Nền sản xuất đại công nghiệp có trình độ cao",
			"Nền sản xuất thủ công nghiệp",
			"Có kiến trúc thượng tầng hiện đại",
		],
		correct: 1,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội có nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại (tức nền đại công nghiệp phát triển cao).",
	},
	{
		question: "Sự khác nhau giữa giai đoạn thấp và cao của hình thái kinh tế - xã hội cộng sản chủ nghĩa là gì?",
		answers: [
			"Giai đoạn thấp còn sự phân chia giai cấp, giai đoạn cao còn một giai cấp",
			"Giai đoạn thấp sử dụng pháp quyền tư sản, giai đoạn cao sử dụng pháp quyền xã hội chủ nghĩa",
			"Giai đoạn thấp thực hiện phân phối theo lao động, giai đoạn cao thực hiện phân phối theo nhu cầu",
			"Giai đoạn thấp thực hiện phân phối theo nhu cầu, giai đoạn cao thực hiện phân phối theo lao động",
		],
		correct: 2,
		explanation: "Dựa trên Trang 39 và 40 của chương 3 của tài liệu, chỉ ra rằng ở giai đoạn cao (cộng sản chủ nghĩa) thực hiện nguyên tắc 'làm theo năng lực, hưởng theo nhu cầu', còn giai đoạn thấp (chủ nghĩa xã hội) là 'phân phối chủ yếu theo lao động'.",
	},
	{
		question: "C. Mác đã dựa vào nhân tố nào trong sự vận động của chủ nghĩa tư bản để kết luận rằng xã hội tư bản sẽ chuyển sang xã hội xã hội chủ nghĩa?",
		answers: [
			"C. Mác đã phân tích những áp bức về tinh thần trong xã hội tư bản",
			"C. Mác đã phân tích sự phân hóa giàu nghèo trong xã hội tư bản",
			"C. Mác đã phân tích những tiến bộ trong chủ nghĩa tư bản",
			"C. Mác đã phân tích những quy luật kinh tế trong chủ nghĩa tư bản",
		],
		correct: 2,
		explanation: "Dựa trên Trang 36 của chương 3 của tài liệu, chỉ ra rằng Sự ra đời của chủ nghĩa tư bản là một giai đoạn mới... Nhờ những bước tiến to lớn của lực lượng sản xuất... C.Mác xuất phát từ chỗ LLSX hiện đại để chứng minh CNTB tạo ra tiền đề vật chất cho sự ra đời của CNXH.",
	},
	{
		question: "Theo quan điểm của chủ nghĩa Mác - Lênin, nguyên nhân sâu xa của mọi cuộc cách mạng xã hội trong lịch sử là mâu thuẫn giữa:",
		answers: [
			"Giai cấp công nhân và giai cấp tư sản",
			"Giai cấp nông dân và giai cấp địa chủ",
			"Giai cấp nô lệ và giai cấp chủ nô",
			"Lực lượng sản xuất tiên tiến và quan hệ sản xuất lỗi thời, lạc hậu",
		],
		correct: 3,
		explanation: "Dựa trên Trang 36 và 37 của chương 3 của tài liệu, chỉ ra rằng Mâu thuẫn giữa tính chất xã hội hóa của lực lượng sản xuất với chế độ chiếm hữu tư nhân tư bản chủ nghĩa... dẫn đến kìm hãm (lỗi thời) và đòi hỏi cuộc cách mạng xã hội.",
	},
	{
		question: "Cách hiểu nào dưới đây không đúng về chủ nghĩa xã hội?",
		answers: [
			"Là một phong trào thực tiễn, phong trào đấu tranh của nhân dân lao động chống các giai cấp thống trị",
			"Là trào lưu tư tưởng, lí luận phản ánh lí tưởng giải phóng nhân dân lao động khỏi áp bức, bóc lột, bất công.",
			"Là một khoa học nghiên cứu về những quy luật chung nhất của tự nhiên, xã hội và tư duy.",
			"Là một chế độ xã hội hiện thực tốt đẹp, giai đoạn đầu của hình thái kinh tế - xã hội cộng sản chủ nghĩa.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 34 của chương 3 của tài liệu, chỉ ra 4 cách tiếp cận CNXH: 1. phong trào thực tiễn, 2. trào lưu tư tưởng, 3. một khoa học (khoa học về sứ mệnh lịch sử GCCN), 4. một chế độ xã hội. Phương án C miêu tả đối tượng của Triết học (quy luật chung nhất), không phải của CNXHKH.",
	},
	{
		question: "Tác phẩm Phê phán cương lĩnh Gôta là của….",
		answers: [
			"C. Mác",
			"Ph. Ăngghen",
			"C. Mác và Ph. Ăngghen",
			"V.I. Lênin",
		],
		correct: 0,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng Trong tác phẩm 'Phê phán cương lĩnh Gôta' (1875) C.Mác đã cho rằng...",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống: “Giữa xã hội tư bản chủ nghĩa và xã hội cộng sản chủ nghĩa là một thời kì cải biến cách mạng từ xã hội nọ sang xã hội kia. Thích ứng với thời kì ấy là một […] chính trị, và nhà nước của thời kì ấy không thể là cái gì khác hơn là nền chuyên chính cách mạng của giai cấp vô sản” (C. Mác).",
		answers: [
			"thời kì quá độ",
			"giai đoạn",
			"hình thái",
			"thể chế",
		],
		correct: 0,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng C.Mác đã định nghĩa: Thích ứng với thời kỳ ấy là một thời kỳ quá độ chính trị.",
	},
	{
		question: "Điền từ thích hợp vào chỗ trống: V.I. Lênin khẳng định “về lý luận, không thể nghi ngờ gì được rằng giữa chủ nghĩa tư bản và chủ nghĩa cộng sản, có một …. nhất định”.",
		answers: [
			"thời kì cách mạng",
			"thời kì chuyển giao",
			"thời kì quá độ",
			"thời kì cải biến",
		],
		correct: 2,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin khẳng định: về lý luận, không thể nghi ngờ gì được rằng giữa chủ nghĩa tư bản và chủ nghĩa cộng sản, có một thời kỳ quá độ nhất định.",
	},
	{
		question: "Từ thực tiễn nước Nga, V.I. Lênin cho rằng: Đối với những nước chưa có chủ nghĩa tư bản phát triển cao, cần phải có một thời kì quá độ…",
		answers: [
			"khá lâu dài từ chủ nghĩa tư bản lên chủ nghĩa xã hội.",
			"khá nhanh chóng từ chủ nghĩa tư bản lên chủ nghĩa xã hội.",
			"rất nhanh từ chủ nghĩa tư bản lên chủ nghĩa xã hội.",
			"rất lâu dài và gian khổ từ chủ nghĩa tư bản lên chủ nghĩa xã hội.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 35 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin cho rằng, đối với những nước chưa có chủ nghĩa tư bản phát triển cao 'cần phải có thời kỳ quá độ khá lâu dài từ chủ nghĩa tư bản lên chủ nghĩa xã hội'.",
	},
	{
		question: "Theo các nhà sáng lập chủ nghĩa xã hội khoa học, quá độ lên chủ nghĩa xã hội có hai hình thức là…",
		answers: [
			"nhanh và chậm.",
			"đơn giản và phức tạp.",
			"trực tiếp và gián tiếp.",
			"sớm và muộn.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 44 và 45 của chương 3 của tài liệu, chỉ ra rằng các nhà sáng lập phân biệt có hai loại quá độ: Quá độ trực tiếp (từ CNTB phát triển) và Quá độ gián tiếp (từ nước chưa trải qua CNTB phát triển).",
	},
	{
		question: "Điền từ ngữ thích hợp vào chỗ trống: V.I.Lênin viết: “Với sự giúp đỡ của giai cấp vô sản các nước tiên tiến, các nước lạc hậu có thể tiến tới chế độ Xô viết, và qua những (...) phát triển nhất định, tiến tới chủ nghĩa cộng sản, không phải trải qua…. phát triển tư bản chủ nghĩa”.",
		answers: [
			"chế độ",
			"giai đoạn",
			"quá trình",
			"hình thức",
		],
		correct: 1,
		explanation: "Dựa trên Trang 45 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin khẳng định: ...và qua những giai đoạn phát triển nhất định, tiến tới chủ nghĩa cộng sản không phải trải qua giai đoạn phát triển tư bản chủ nghĩa.",
	},
	{
		question: "Nội dung nào dưới đây không phải là điều kiện dẫn tới sự ra đời của chủ nghĩa xã hội?",
		answers: [
			"Sự phát triển của lực lượng sản xuất",
			"Sự trưởng thành của giai cấp công nhân",
			"Quan hệ sản xuất tư bản chủ nghĩa trở nên lỗi thời",
			"Mong muốn chủ quan của giai cấp công nhân",
		],
		correct: 3,
		explanation: "Dựa trên Trang 36 và 37 của chương 3 của tài liệu, chỉ ra rằng Điều kiện ra đời CNXH mang tính khách quan từ sự phát triển của LLSX (kinh tế) và sự trưởng thành của GCCN (chính trị - xã hội), không phụ thuộc vào mong muốn chủ quan.",
	},
	{
		question: "Giải phóng giai cấp, giải phóng dân tộc, giải phóng xã hội, giải phóng con người, tạo điều kiện để con người phát triển toàn diện là đặc trưng của…",
		answers: [
			"chủ nghĩa xã hội",
			"chủ nghĩa tư bản",
			"xã hội phong kiến",
			"xã hội chiếm hữu nô lệ",
		],
		correct: 0,
		explanation: "Dựa trên Trang 38 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội giải phóng giai cấp, giải phóng dân tộc, giải phóng xã hội, giải phóng con người, tạo điều kiện để con người phát triển toàn diện.",
	},
	{
		question: "Đặc trưng nào dưới đây thể hiện sự khác biệt về chất giữa chủ nghĩa xã hội với các chế độ xã hội khác?",
		answers: [
			"Có quan hệ sản xuất phù hợp với lực lượng sản xuất.",
			"Là chế độ giải phóng giai cấp, giải phóng dân tộc, giải phóng xã hội, giải phóng con người.",
			"Có nền văn hoá phát triển cao, kế thừa và phát huy những giá trị của văn hoá dân tộc và tinh hoa văn hoá nhân loại.",
			"Bảo đảm, đoàn kết giữa các dân tộc.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 38 của chương 3 của tài liệu, chỉ ra rằng Đây là sự khác biệt về chất giữa hình thái kinh tế - xã hội cộng sản chủ nghĩa so với các hình thái trước, thể hiện ở bản chất nhân văn, nhân đạo, vì sự nghiệp giải phóng giai cấp, giải phóng xã hội, giải phóng con người.",
	},
	{
		question: "Nội dung nào dưới đây là đặc trưng về phương diện kinh tế của chủ nghĩa xã hội?",
		answers: [
			"Có nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và chế độ công hữu về tư liệu sản xuất chủ yếu.",
			"Có nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và chế độ công hữu về tư liệu sản xuất.",
			"Phát triển lực lượng sản xuất, đẩy mạnh công nghiệp hoá, hiện đại hoá.",
			"Xác lập chế độ công hữu về tư liệu sản xuất, tổ chức lao động theo trình độ cao hơn.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 40 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội có nền kinh tế phát triển cao dựa trên lực lượng sản xuất hiện đại và chế độ công hữu về tư liệu sản xuất chủ yếu.",
	},
	{
		question: "Khi phân tích về thời kì quá độ lên chủ nghĩa xã hội, người đầu tiên đặt vấn đề phải học tập các kinh nghiệm tổ chức, quản lí kinh tế của chủ nghĩa tư bản để cải tạo nền kinh tế tiểu nông lạc hậu là …",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 40 và 41 của chương 3 của tài liệu, chỉ ra rằng Đối với những nước chưa trải qua CNTB, V.I.Lênin chỉ rõ tất yếu phải 'bắc những chiếc cầu nhỏ'... và cần thiết phải học hỏi kinh nghiệm từ các nước phát triển.",
	},
	{
		question: "Ai là người đưa ra quan điểm: “Trong một nước tiểu nông, trước hết các đồng chí phải bắc những chiếc cầu nhỏ vững chắc, đi xuyên qua chủ nghĩa tư bản nhà nước, tiến lên chủ nghĩa xã hội”?",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 41 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin viết: Trong một nước tiểu nông, trước hết các đồng chí phải bắc những chiếc cầu nhỏ vững chắc...",
	},
	{
		question: "Ai cho rằng: “Dùng cả hai tay mà lấy những cái tốt của nước ngoài: Chính quyền Xô viết + trật tự ở đường sắt Phổ + kĩ thuật và cách tổ chức các tơ-rớt ở Mỹ + ngành giáo dục quốc dân Mỹ etc. etc. = (tổng số) = chủ nghĩa xã hội”?",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 41 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin chỉ rõ cách thức: Dùng cả hai tay mà lấy những cái tốt của nước ngoài...",
	},
	{
		question: "Trong chế độ xã hội chủ nghĩa, nhà nước mang bản chất của giai cấp, tầng lớp nào dưới đây?",
		answers: [
			"Giai cấp công nhân.",
			"Nhân dân lao động.",
			"Tầng lớp trí thức.",
			"Giai cấp tư sản.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 41 của chương 3 của tài liệu, chỉ ra rằng Chủ nghĩa xã hội có nhà nước kiểu mới mang bản chất giai cấp công nhân.",
	},
	{
		question: "Nhà nước kiểu mới thực hiện dân chủ cho tuyệt đại đa số nhân dân và trấn áp bọn bóc lột, bọn áp bức nhân dân bằng vũ lực là…",
		answers: [
			"nhà nước chiếm hữu nô lệ.",
			"nhà nước phong kiến,",
			"nhà nước tư sản.",
			"nhà nước vô sản.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 41 của chương 3 của tài liệu, chỉ ra rằng Nhà nước vô sản... là một công cụ... thực hiện dân chủ cho tuyệt đại đa số nhân dân và trấn áp bằng vũ lực bọn bóc lột, bọn áp bức nhân dân.",
	},
	{
		question: "“Người ta chỉ có thể trở thành người cộng sản khi biết làm giàu trí óc của mình bằng sự hiểu biết tất cả những kho tàng tri thức mà nhân loại đã tạo ra” là câu nói của…",
		answers: [
			"C. Mác.",
			"Ph. Ăngghen.",
			"V.I. Lênin.",
			"Hồ Chí Minh.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 42 của chương 3 của tài liệu, chỉ ra rằng Đồng thời, V.I.Lênin cũng cho rằng, trong xã hội xã hội chủ nghĩa, những người cộng sản sẽ làm giàu tri thức... 'Người ta chỉ có thể trở thành người cộng sản khi biết làm giàu trí óc của mình...'.",
	},
	{
		question: "Người đầu tiên đưa chủ nghĩa xã hội từ lí thuyết thành thực tiễn sinh động là…",
		answers: [
			"C. Mác.",
			"V.I. Lênin.",
			"I.V. Stalin.",
			"Hồ Chí Minh.",
		],
		correct: 1,
		explanation: "Dựa trên kiến thức lịch sử phong trào (Chương 1 và Chương 3), chỉ ra rằng V.I.Lênin lãnh đạo thành công Cách mạng Tháng Mười (1917), biến chủ nghĩa xã hội từ khoa học lý thuyết trở thành hiện thực với Nhà nước Xô Viết.",
	},
	{
		question: "Ai là người đưa ra tư tưởng độc lập dân tộc gắn liền với chủ nghĩa xã hội?",
		answers: [
			"V.I. Lênin.",
			"Hồ Chí Minh.",
			"Đặng Tiểu Bình.",
			"Phạm Văn Đồng.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 16 của tài liệu (phần đóng góp của Đảng và Bác Hồ, áp dụng vào nội dung con đường cách mạng VN Chương 3), chỉ ra rằng Độc lập dân tộc gắn liền với chủ nghĩa xã hội là tư tưởng cốt lõi của Chủ tịch Hồ Chí Minh.",
	},
	{
		question: "Câu nói: “Chủ nghĩa xã hội hay là chết” là của…",
		answers: [
			"V.I. Lênin.",
			"Fidel Castro.",
			"Hồ Chí Minh.",
			"Đặng Tiểu Bình.",
		],
		correct: 1,
		explanation: "Dựa trên kiến thức nền về lịch sử phong trào cộng sản quốc tế, câu khẩu hiệu nổi tiếng 'Socialismo o Muerte' (Chủ nghĩa xã hội hay là chết) là của vị lãnh tụ cách mạng Cuba Fidel Castro.",
	},
	{
		question: "C.Mác: “Đối với chúng ta, chủ nghĩa cộng sản không phải là một…. cần phải sáng tạo ra, không phải là một…. hiện thực phải khuôn theo. Chúng ta gọi chủ nghĩa cộng sản là một phong trào… nó xoá bỏ trạng thái hiện nay”.",
		answers: [
			"lí tưởng, trạng thái, hiện thực.",
			"trạng thái, lí tưởng, hiện thực",
			"trạng thái, hiện thực, lí tưởng.",
			"hiện thực, lí tưởng, trạng thái.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 45 của chương 3 của tài liệu, chỉ ra rằng Xuất phát từ quan điểm: chủ nghĩa cộng sản không phải là một trạng thái cần sáng tạo ra, không phải là một lý tưởng mà hiện thực phải tuân theo mà là kết quả của phong trào hiện thực.",
	},
	{
		question: "Điền từ thích hợp vào chỗ trống: “Vậy thì danh từ ……. có nghĩa là gì? Vận dụng vào kinh tế, có phải nó có nghĩa là trong chế độ hiện nay có những thành phần, những bộ phận, những mảnh của cả chủ nghĩa tư bản lẫn chủ nghĩa xã hội? Bất cứ ai cũng đều thừa nhận là có” (V.I. Lênin).",
		answers: [
			"quá độ.",
			"nhảy vọt.",
			"phát triển.",
			"đan xen.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng V.I.Lênin cho rằng: 'Vậy thì danh từ quá độ có nghĩa là gì? Vận dụng vào kinh tế...'",
	},
	{
		question: "Nội dung nào dưới đây là đặc điểm nổi bật của thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Sự đan xen vừa thống nhất vừa đấu tranh giữa những yếu tố của xã hội cũ và những nhân tố mới của chủ nghĩa xã hội.",
			"Sự xác lập vai trò thống trị của giai cấp công nhân thông qua đội tiên phong là Đảng Cộng sản.",
			"Xây dựng thành công chủ nghĩa xã hội.",
			"Tiến hành công nghiệp hoá, hiện đại hoá đất nước, xây dựng cơ sơ vật chất - kĩ thuật cho chủ nghĩa xã hội.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Xã hội của thời kỳ quá độ là xã hội có sự đan xen của nhiều tàn dư... của chủ nghĩa tư bản và những yếu tố mới mang tính chất xã hội chủ nghĩa.",
	},
	{
		question: "Nội dung nào dưới đây là thực chất của thời kì quá độ?",
		answers: [
			"Thời kì cải biến cách mạng từ xã hội tiền tư bản và tư bản chủ nghĩa sang xã hội xã hội chủ nghĩa.",
			"Thời kì tiếp tục cuộc đấu tranh của giai cấp công nhân chống giai cấp tư sản.",
			"Thời kì giai cấp công nhân phát triển kinh tế, xây dựng cơ sở vật chất - kĩ thuật cho chủ nghĩa xã hội.",
			"Thời kì giai cấp công nhân tiến hành công nghiệp hoá, hiện đại hoá đất nước.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 45 của chương 3 của tài liệu, chỉ ra rằng Thực chất của thời kỳ quá độ lên chủ nghĩa xã hội là thời kỳ cải biến cách mạng từ xã hội tiền tư bản chủ nghĩa và tư bản chủ nghĩa sang xã hội xã hội chủ nghĩa.",
	},
	{
		question: "Nội dung nào dưới đây là đặc điểm kinh tế của thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Tiến hành công nghiệp hoá, hiện đại hoá đất nước.",
			"Tồn tại nền kinh tế nhiều thành phần.",
			"Tồn tại duy nhất thành phần kinh tế tập thể.",
			"Phát triển lực lượng sản xuất.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực kinh tế: Thời kỳ quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội, về phương diện kinh tế, tất yếu tồn tại nền kinh tế nhiều thành phần.",
	},
	{
		question: "Nội dung nào dưới đây là đặc điểm trên lĩnh vực chính trị của thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Thiết lập, tăng cường chuyên chính vô sản.",
			"Tồn tại nhiều tư tưởng khác nhau.",
			"Giai cấp công nhân nắm và sử dụng quyền lực nhà nước trấn áp giai cấp tư sản.",
			"Giai cấp công nhân tổ chức xây dựng và bảo vệ chế độ mới.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực chính trị, là việc thiết lập, tăng cường chuyên chính vô sản mà thực chất của nó là việc giai cấp công nhân nắm và sử dụng quyền lực nhà nước trấn áp giai cấp tư sản.",
	},
	{
		question: "Tiếp tục cuộc đấu tranh giai cấp giữa giai cấp vô sản đã chiến thắng nhưng chưa hoàn toàn chiến thắng với giai cấp tư sản đã thất bại nhưng chưa phải thất bại hoàn toàn là đặc điểm của thời kì quá độ trên phương diện…",
		answers: [
			"chính trị.",
			"kinh tế.",
			"tư tưởng, văn hoá.",
			"xã hội.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 46 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực chính trị... là tiếp tục cuộc đấu tranh giai cấp giữa giai cấp vô sản đã chiến thắng... với giai cấp tư sản đã thất bại.",
	},
	{
		question: "Nội dung nào dưới đây là đặc điểm trên lĩnh vực tư tưởng, văn hoá của thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Tồn tại nhiều giai cấp, tầng lớp.",
			"Tồn tại nhiều tư tưởng khác nhau.",
			"Tồn tại sự khác biệt giữa lao động trí óc và lao động chân tay.",
			"Tồn tại nhiều thành phần kinh tế đối lập",
		],
		correct: 1,
		explanation: "Dựa trên Trang 47 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực tư tưởng - văn hóa: Thời kỳ quá độ... còn tồn tại nhiều tư tưởng khác nhau, chủ yếu là tư tưởng vô sản và tư tưởng tư sản.",
	},
	{
		question: "Giai cấp công nhân từng bước xây dựng văn hoá vô sản, nền văn hoá mới xã hội chủ nghĩa, tiếp thu giá trị văn hoá dân tộc và tinh hoa văn hoá nhân loại, bảo đảm đáp ứng nhu cầu văn hoá tinh thần ngày càng tăng của nhân dân là đặc điểm của thời kì quá độ trên phương diện…",
		answers: [
			"chính trị.",
			"kinh tế.",
			"tư tưởng, văn hoá",
			"xã hội.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 47 của chương 3 của tài liệu, chỉ ra rằng Trên lĩnh vực tư tưởng - văn hóa: Giai cấp công nhân thông qua đội tiên phong... từng bước xây dựng văn hóa vô sản, nền văn hóa mới xã hội chủ nghĩa, tiếp thu giá trị văn hóa...",
	},
	{
		question: "Nội dung nào dưới đây không phải là đặc điểm trên lĩnh vực xã hội của thời kì quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Tồn tại sự khác biệt giữa thành thị, nông thôn.",
			"Tồn tại sự khác biệt giữa lao động trí óc và lao động chân tay.",
			"Tồn tại nhiều hủ tục, tệ nạn xã hội.",
			"Tồn tại nhiều tư tưởng khác nhau.",
		],
		correct: 3,
		explanation: "Dựa trên Trang 47 của chương 3 của tài liệu, chỉ ra rằng Tồn tại nhiều tư tưởng khác nhau thuộc về 'Đặc điểm trên lĩnh vực tư tưởng - văn hóa', không phải thuộc về lĩnh vực xã hội (cơ cấu xã hội, bất bình đẳng, v.v.).",
	},
	{
		question: "Nội dung nào dưới đây là con đường phát triển của cách mạng Việt Nam được Chủ tịch Hồ Chí Minh nêu ra trong Chánh cương vắn tắt của Đảng?",
		answers: [
			"Làm tư sản dân quyền cách mạng để đi tới xã hội cộng sản.",
			"Làm tư sản dân quyền cách mạng và thổ địa cách mạng để đi tới xã hội cộng sản.",
			"Làm thổ địa cách mạng và tư sản dân quyền cách mạng để đi tới xã hội cộng sản.",
			"Làm tư sản dân quyền và thổ địa cách mạng để đi thẳng tới xã hội xã hội chủ nghĩa và cộng sản chủ nghĩa.",
		],
		correct: 1,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu (liên kết cùng cương lĩnh 1930), chỉ ra rằng Cương lĩnh năm 1930 của Đảng đã chỉ rõ: Sau khi hoàn thành cách mạng dân tộc, dân chủ nhân dân (tư sản dân quyền và thổ địa), sẽ tiến lên chủ nghĩa xã hội.",
	},
	{
		question: "Con đường quá độ bỏ qua chế độ tư bản chủ nghĩa ở Việt Nam được đề cập lần đầu tiên ở văn kiện nào dưới đây của Đảng?",
		answers: [
			"Cương lĩnh chính trị đầu tiên của Đảng tháng 2 năm 1930.",
			"Luận cương chính trị tháng 10 năm 1930.",
			"Chính cương của Đảng Lao động tháng 2 năm 1951.",
			"Cương lĩnh xây dựng đất nước trong thời kì quá độ lên chủ nghĩa xã hội tháng 6 năm 1991.",
		],
		correct: 0,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu, chỉ ra rằng Cương lĩnh năm 1930 của Đảng đã chỉ rõ: Sau khi hoàn thành cách mạng dân tộc, dân chủ nhân dân, sẽ tiến lên chủ nghĩa xã hội (chính là xác lập con đường quá độ bỏ qua TBCN từ sớm).",
	},
	{
		question: "Con đường cách mạng Việt Nam là quá độ lên chủ nghĩa xã hội bỏ qua chế độ tư bản chủ nghĩa là một tất yếu vì…",
		answers: [
			"Đảng Cộng sản Việt Nam đã có đường lối đúng đắn.",
			"sự phát triển của lực lượng sản xuất.",
			"phù hợp với đặc điểm của đất nước và xu thế phát triển của thời đại.",
			"đáp ứng được nguyện vọng và mong ước của nhân dân ta.",
		],
		correct: 2,
		explanation: "Dựa trên Trang 48 của chương 3 của tài liệu, chỉ ra rằng Quá độ lên chủ nghĩa xã hội bỏ qua chế độ tư bản chủ nghĩa là sự lựa chọn duy nhất đúng... phản ánh xu thế phát triển của thời đại, phù hợp với quan điểm khoa học, cách mạng và sáng tạo của chủ nghĩa Mác - Lênin.",
	},
];