const cnxhPtitBank = [
	{
		question: "Nguồn gốc lý luận trực tiếp ra đời chủ nghĩa xã hội khoa học là",
		answers: [
			"Triết học cổ điển Đức",
			"Kinh tế chính trị học cổ điển Anh",
			"Chủ nghĩa xã hội không tưởng – phê phán",
			"Cả ba nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chủ nghĩa xã hội không tưởng – phê phán, mà đại biểu là H.Xanh Ximông, được xác định là tiền đề lý luận trực tiếp của chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Thực chất của TKQĐ lên CNXH là gì?",
		answers: [
			"Là cuộc cải biến cách mạng về kinh tế",
			"Là cuộc cải biến cách mạng về chính trị",
			"Là cuộc cải biến cách mạng về tư tưởng và văn hoá",
			"Tất cả các nội dung đã nêu đều đúng",
		],
		correct: 3,
		explanation: "Dựa trên trang số 45 và 46 của chương 3 của tài liệu, thời kỳ quá độ lên chủ nghĩa xã hội là thời kỳ cải biến cách mạng trên tất cả các lĩnh vực: kinh tế, chính trị, văn hóa và xã hội.",
	},
	{
		question: "Thời kỳ quá độ lên chủ nghĩa xã hội trên phạm vi cả nước ta bắt đầu",
		answers: [
			"8/1945",
			"5/1954",
			"4/1975",
			"2/1930",
		],
		correct: 2,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm, thời kỳ quá độ lên chủ nghĩa xã hội ở Việt Nam bắt đầu từ năm 1954 ở miền Bắc và từ năm 1975 trên phạm vi cả nước, sau khi đất nước hoàn toàn độc lập và thống nhất.",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa xuất hiện đầu tiên ở nước nào?",
		answers: [
			"Pháp",
			"Đức",
			"Nga",
			"Mỹ",
		],
		correct: 2,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm, dân chủ xã hội chủ nghĩa xuất hiện đầu tiên ở nước Nga sau Cách mạng tháng Mười Nga năm 1917.",
	},
	{
		question: "Đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa mang bản chất...",
		answers: [
			"giai cấp nông dân",
			"giai cấp công nhân",
			"tầng lớp trí thức",
			"tầng lớp doanh nhân",
		],
		correct: 1,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa có tính...",
		answers: [
			"nhân dân rộng rãi",
			"dân tộc sâu sắc",
			"Cách mạng",
			"Cả tính nhân dân rộng rãi và tính dân tộc sâu sắc",
		],
		correct: 3,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu và phần giải thích cuối tài liệu trắc nghiệm, đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa bao gồm tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là ...",
		answers: [
			"Chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tập thể về tư liệu sản xuất chủ yếu",
			"Chế độ công hữu về tư liệu sản xuất chủ yếu",
			"Tất cả các chế độ sở hữu đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất chủ yếu của toàn xã hội.",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa vừa mang tính... vừa mang tính... vừa mang tính...",
		answers: [
			"Giai cấp... tầng lớp",
			"Giai cấp... dân tộc",
			"Giai cấp... dân tộc... nhân loại",
			"Giai cấp... dân tộc... nhân dân",
		],
		correct: 3,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Chọn phương án đúng nhất: Nhà nước xã hội chủ nghĩa mang",
		answers: [
			"bản chất giai cấp công nhân và nhân dân lao động.",
			"bản chất giai cấp công nhân và giai cấp nông dân.",
			"ban chất giai cấp công nhân, tính quần chúng rộng rãi.",
			"bản chất giai cấp công nhân, tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
		],
		correct: 3,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, có tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Chọn phương án đúng nhất: Hệ thống chính trị xã hội chủ nghĩa ở Việt Nam hiện nay bao gồm...",
		answers: [
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, Mặt trận Tổ quốc Việt Nam.",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, các tổ chức xã hội.",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, các tổ chức chính trị - xã hội.",
		],
		correct: 3,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm, hệ thống chính trị xã hội chủ nghĩa ở Việt Nam bao gồm Đảng Cộng sản Việt Nam, Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam và các tổ chức chính trị - xã hội.",
	},
	{
		question: "Điền vào chỗ trống: Trong xu hướng thứ nhất, do sự thức tỉnh và sự trưởng thành của ý thức dân tộc mà các cộng đồng dân cư muốn .... để xác lập dân tộc độc lập.",
		answers: [
			"đoàn kết.",
			"hợp tác với nhau.",
			"tách ra.",
			"hợp nhất lại.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 86 của chương 6 của tài liệu và phần giải thích cuối tài liệu trắc nghiệm, trong xu hướng thứ nhất, các cộng đồng dân cư muốn tách ra để hình thành cộng đồng dân tộc độc lập.",
	},
	{
		question: "Điền vào chỗ trống: Quyền bình đẳng giữa các dân tộc là quyền... của các dân tộc.",
		answers: [
			"phát triển.",
			"sống còn.",
			"Thiêng liêng.",
			"Cao cả.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, quyền bình đẳng giữa các dân tộc là quyền cơ bản, thiêng liêng và là cơ sở để thực hiện quyền dân tộc tự quyết.",
	},
	{
		question: "Điền vào chỗ trống: Quyền dân tộc tự quyết là quyền ... đối với vận mệnh của dân tộc mình.",
		answers: [
			"tự quyết định.",
			"làm chủ.",
			"tự lo liệu.",
			"tự do phát triển",
		],
		correct: 0,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, quyền dân tộc tự quyết là quyền của các dân tộc tự quyết định lấy vận mệnh của dân tộc mình.",
	},
	{
		question: "Chọn phương án đúng nhất: Dưới chủ nghĩa xã hội, tôn giáo vẫn tồn tại do các nguyên nhân:",
		answers: [
			"Nhận thức, chính trị.",
			"Nhận thức, kinh tế, tâm lý, chính trị, văn hoá.",
			"Nhận thức, văn hoá, tư tưởng.",
			"Nhận thức, kinh tế, văn hoá, tư tưởng.",
		],
		correct: 1,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm và nội dung trang 90, 91 của giáo trình, tôn giáo vẫn còn tồn tại dưới chủ nghĩa xã hội do các nguyên nhân nhận thức, kinh tế, tâm lý, chính trị và văn hóa.",
	},
	{
		question: "Trong chủ nghĩa xã hội cần phải...",
		answers: [
			"đấu tranh xóa bỏ tôn giáo",
			"tạo điều kiện cho tôn giáo phát triển",
			"đảm bảo tôn trọng quyền tự do tín ngưỡng và không tín ngưỡng của nhân dân",
			"hạn chế sự phát triển của tôn giáo",
		],
		correct: 2,
		explanation: "Dựa trên trang số 92 của chương 6 của tài liệu, nguyên tắc giải quyết vấn đề tôn giáo trong chủ nghĩa xã hội là tôn trọng và bảo đảm quyền tự do tín ngưỡng, không tín ngưỡng của nhân dân.",
	},
	{
		question: "Sự bất lực của con người trước sức mạnh tự phát của tự nhiên và xã hội là nội dung của nguyên nhân nào lý giải sự tồn tại của tôn giáo trong tiến trình xây dựng chủ nghĩa xã hội?",
		answers: [
			"Chính trị - xã hội",
			"Nhận thức",
			"Kinh tế",
			"Tâm lý",
		],
		correct: 2,
		explanation: "Dựa trên trang số 91 của chương 6 của tài liệu, sự bất lực của con người trước sức mạnh tự phát của tự nhiên và xã hội thuộc nguồn gốc tự nhiên, kinh tế - xã hội của tôn giáo. Trong các lựa chọn hiện có, nội dung này phù hợp nhất với nguyên nhân kinh tế.",
	},
	{
		question: "Khoa học chưa lý giải được nhiều hiện tượng tự nhiên, xã hội và của con người là nội dung của nguyên nhân nào lý giải sự tồn tại của tôn giáo trong tiến trình xây dựng chủ nghĩa xã hội?",
		answers: [
			"Văn hóa",
			"Tâm lý",
			"Chính trị - xã hội",
			"Nhận thức",
		],
		correct: 3,
		explanation: "Dựa trên trang số 91 của chương 6 của tài liệu, khi khoa học chưa giải thích được một số hiện tượng tự nhiên, xã hội và con người, các hiện tượng đó thường được giải thích thông qua lăng kính tôn giáo. Đây là nguyên nhân thuộc về nhận thức.",
	},
	{
		question: "Chủ nghĩa xã hội là gì?",
		answers: [
			"Là phong trào thực tiễn, phong trào đấu tranh của nhân dân lao động chống các giai cấp thống trị",
			"Là trào lưu tư tưởng, lý luận phản ánh lý tưởng giải phóng nhân dân lao động khỏi áp bức, bóc lột, bất công;",
			"Là một khoa học - Chủ nghĩa xã hội khoa học;",
			"Là một chế độ xã hội hiện thực tốt đẹp, xã hội xã hội chủ nghĩa",
			"Tất cả các nội dung đã nêu",
		],
		correct: 4,
		explanation: "Dựa trên trang số 34 của chương 3 của tài liệu, chủ nghĩa xã hội có thể được tiếp cận trên nhiều góc độ: phong trào thực tiễn, trào lưu tư tưởng lý luận, một khoa học và một chế độ xã hội hiện thực tốt đẹp.",
	},
	{
		question: "Phát minh nào không phải là một trong những tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Học thuyết Tế bào",
			"Học thuyết Tiến hóa",
			"Thuyết Nguyên tử",
			"Định luật bảo toàn và chuyển hóa năng lượng",
		],
		correct: 2,
		explanation: "Dựa trên trang số 4 và 5 của chương 1 của tài liệu, ba phát minh vạch thời đại trong vật lý học và sinh học là học thuyết tế bào, học thuyết tiến hóa, định luật bảo toàn và chuyển hóa năng lượng. Thuyết nguyên tử không thuộc nhóm ba tiền đề này.",
	},
	{
		question: "Tư tưởng xã hội chủ nghĩa là gì?",
		answers: [
			"Là một hệ thống những quan niệm phản ánh những nhu cầu, những ước mơ, nguyện vọng của các giai cấp lao động về một xã hội không có áp bức và bóc lột",
			"Là những thành tựu của con người đạt được trong quá trình đấu tranh giải phóng giai cấp.",
			"Là chế độ xã hội không có áp bức bóc lột, mọi người đều bình đẳng tự do.",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên trang số 34 của chương 3 của tài liệu, tư tưởng xã hội chủ nghĩa là trào lưu tư tưởng, lý luận phản ánh lý tưởng giải phóng nhân dân lao động khỏi áp bức, bóc lột và bất công.",
	},
	{
		question: "Những yếu tố tư tưởng XHCN được xuất hiện từ khi nào?",
		answers: [
			"Chế độ tư bản chủ nghĩa ra đời",
			"Sự xuất hiện chế độ tư hữu, xuất hiện giai cấp thống trị và bóc lột",
			"Sự xuất hiện giai cấp công nhân",
			"Thời cộng sản nguyên thủy",
		],
		correct: 1,
		explanation: "Dựa trên nguyên lý chung xuyên suốt chương 1 và chương 3 của tài liệu, tư tưởng và khát vọng về chủ nghĩa xã hội xuất hiện khi bắt đầu có sự áp bức, bóc lột do chế độ tư hữu sinh ra.",
	},
	{
		question: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Là những quy luật và tính quy luật chính trị – xã hội của quá trình phát sinh, hình thành và phát triển hình thái kinh tế - xã hội cộng sản chủ nghĩa",
			"Là những quy luật kinh tế hình thành, phát triển và hoàn thiện của các hình thái kinh tế - xã hội.",
			"Là những quy luật và tính quy luật chính trị – xã hội của quá trình phát sinh, hình thành và phát triển hình thái kinh tế - xã hội tư bản chủ nghĩa",
			"Tất cả các nội dung đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên trang số 19 của chương 1 của tài liệu, đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là những quy luật, tính quy luật chính trị - xã hội của quá trình phát sinh, hình thành và phát triển hình thái kinh tế - xã hội cộng sản chủ nghĩa.",
	},
	{
		question: "Hạn chế của chủ nghĩa xã hội không tưởng trước Mác là...",
		answers: [
			"Chưa thấy được sứ mệnh lịch sử của giai cấp công nhân",
			"Chưa chỉ ra được con đường đấu tranh cách mạng",
			"Không luận chứng được một cách khoa học về bản chất của chủ nghĩa tư bản và quy luật phát triển của chủ nghĩa tư bản",
			"Tất cả các hạn chế đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chủ nghĩa xã hội không tưởng trước Mác có các hạn chế: chưa phát hiện được quy luật vận động của chủ nghĩa tư bản, chưa thấy được lực lượng xã hội tiên phong là giai cấp công nhân và chưa chỉ ra được biện pháp hiện thực để cải tạo xã hội.",
	},
	{
		question: "Nguồn gốc lý luận trực tiếp ra đời chủ nghĩa xã hội khoa học là....",
		answers: [
			"Triết học cổ điển Đức",
			"Kinh tế chính trị học cổ điển Anh",
			"Chủ nghĩa xã hội không tưởng – phê phán",
			"Cả ba nội dung đã nêu",
		],
		correct: 2,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chủ nghĩa xã hội không tưởng – phê phán được xác định là tiền đề lý luận trực tiếp cho sự ra đời của chủ nghĩa xã hội khoa học.",
	},
	{
		question: "Ai là người đã có công lao biến chủ nghĩa xã hội từ khoa học trở thành hiện thực?",
		answers: [
			"C. Mac",
			"Ph. Anh Ngân",
			"V.Lênin",
			"Hồ Chí Minh",
		],
		correct: 2,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm và trang số 10 của chương 1, V.I. Lênin có vai trò đưa chủ nghĩa xã hội khoa học từ lý luận trở thành hiện thực sau Cách mạng tháng Mười Nga năm 1917.",
	},
	{
		question: "Ai là người đã có công lao biến chủ nghĩa xã hội từ không tưởng trở thành khoa học?",
		answers: [
			"C. Mác và Ph. Ăngghen",
			"V.ILênin",
			"Hồ Chí Minh",
			"Tất cả các nhân vật đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên trang số 10 của chương 1 của tài liệu, C. Mác và Ph. Ăngghen có công lao phát triển chủ nghĩa xã hội từ không tưởng thành khoa học.",
	},
	{
		question: "Trong phương thức sản xuất tư bản chủ nghĩa, mâu thuẫn trong lĩnh vực kinh tế là mâu thuẫn giữa....",
		answers: [
			"Lực lượng sản xuất mang tính xã hội hóa với quan hệ sản xuất mang tính xã hội tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính cá nhân với quan hệ sản xuất mang tính xã hội tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính xã hội hóa với quan hệ sản xuất mang tính tư nhân tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính cá nhân với quan hệ sản xuất mang tính tư nhân tư bản chủ nghĩa",
		],
		correct: 2,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, lực lượng sản xuất trong chủ nghĩa tư bản ngày càng mang tính xã hội hóa cao, nhưng quan hệ sản xuất lại dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất.",
	},
	{
		question: "Quy luật chính trị - xã hội phản ánh quan hệ nào sau đây?",
		answers: [
			"Quan hệ giữa các thiết chế văn hóa",
			"Quan hệ giữa các giai cấp, tầng lớp trong xã hội.",
			"Quan hệ giữa các cộng đồng dân cư trong xã hội",
			"Quan hệ giữa các tổ chức trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên trang số 18 và 19 của chương 1 của tài liệu, đối tượng của chủ nghĩa xã hội khoa học là các quy luật chính trị - xã hội, phản ánh con đường, hình thức và phương pháp đấu tranh cách mạng của giai cấp công nhân cùng các tầng lớp nhân dân.",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là...",
		answers: [
			"Xây dựng lý luận về đảng kiểu mới của giai cấp công nhân.",
			"Xây dựng lý luận về đảng kiểu mới của giai cấp nông dân.",
			"Xây dựng lý luận về đảng của nhiều giai cấp, tầng lớp trong xã hội",
			"Xây dựng lý luận về đảng của các dân tộc thuộc địa và phụ thuộc",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, V.I. Lênin đã xây dựng lý luận về đảng cách mạng kiểu mới của giai cấp công nhân.",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Xây dựng lý luận về cách mạng dân chủ kiểu mới.",
			"Xây dựng lý luận về cách mạng dân tộc kiểu mới",
			"Xây dựng lý luận về cách mạng phong kiến kiểu mới",
			"Xây dựng lý luận về cách mạng xã hội kiểu mới",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, V.I. Lênin đã hoàn chỉnh lý luận về cách mạng xã hội chủ nghĩa, chuyên chính vô sản và cách mạng dân chủ tư sản kiểu mới.",
	},
	{
		question: "Cuộc cách mạng công nghiệp lần thứ nhất trong phương thức sản xuất tư bản chủ nghĩa diễn ra đầu tiên ở quốc gia nào?",
		answers: [
			"Anh.",
			"Pháp",
			"Đức",
			"Nga.",
		],
		correct: 0,
		explanation: "Dựa trên kiến thức chung và trang số 5 của chương 1 của tài liệu, cuộc cách mạng công nghiệp lần thứ nhất diễn ra đầu tiên ở Anh, gắn với sự phát triển sớm của chủ nghĩa tư bản và kinh tế chính trị học cổ điển Anh.",
	},
	{
		question: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là:",
		answers: [
			"Những quy luật kinh tế của phương thức sản xuất tư bản chủ nghĩa và sự ra đời của phương thức sản xuất mới - phương thức sản xuất cộng sản chủ nghĩa",
			"Những quy luật khách quan của quá trình cách mạng xã hội chủ nghĩa.",
			"Những quy luật vận động, phát triển chung nhất của tự nhiên, xã hội và tư duy.",
			"Tất cả các phương án đã nêu đều sai",
		],
		correct: 3,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm, chủ nghĩa xã hội khoa học không chỉ nghiên cứu quy luật kinh tế mà còn nghiên cứu các quy luật chính trị - xã hội của quá trình phát triển từ chủ nghĩa tư bản lên chủ nghĩa xã hội. Các lựa chọn còn lại chưa mô tả chính xác và đầy đủ đối tượng nghiên cứu này.",
	},
	{
		question: "Một trong những đóng góp quan trọng của Đảng Cộng sản Việt Nam vào lý luận của chủ nghĩa xã hội khoa học là...",
		answers: [
			"Tư tưởng độc lập dân tộc gắn liền với chủ nghĩa xã hội.",
			"Tư tưởng dân chủ",
			"Tư tưởng nhân văn",
			"Tư tưởng đoàn kết",
		],
		correct: 0,
		explanation: "Dựa trên trang số 16 của chương 1 của tài liệu, độc lập dân tộc gắn liền với chủ nghĩa xã hội được xác định là quy luật của cách mạng Việt Nam.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp tiên phong cách mạng vì họ là giai cấp:",
		answers: [
			"Đại biểu cho phương thức sản xuất tiên tiến",
			"Được trang bị lý luận khoa học cách mạng",
			"Luôn đi đầu trong mọi phong trào cách mạng",
			"Tất cả các đặc điểm đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên trang số 23 của chương 2 của tài liệu, giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến, được trang bị lý luận khoa học cách mạng và có tinh thần cách mạng triệt để.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết nội bộ giai cấp vì họ có chung:",
		answers: [
			"Địa vị kinh tế - xã hội",
			"Điều kiện làm việc",
			"Điều kiện sống",
			"Tất cả các yếu tố đã nêu",
		],
		correct: 0,
		explanation: "Dựa trên trang số 26 của chương 2 của tài liệu, trong xã hội tư bản chủ nghĩa, giai cấp công nhân không có tư liệu sản xuất chủ yếu và phải bán sức lao động, nên sự đoàn kết nội bộ giai cấp bắt nguồn cơ bản từ địa vị kinh tế - xã hội chung.",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết với các giai cấp, tầng lớp lao động khác vì họ:",
		answers: [
			"Có chung lợi ích kinh tế",
			"Đều bị giai cấp tư sản bóc lột",
			"Có chung nguyện vọng được giải phóng",
			"Tất cả các lý do đã nêu",
		],
		correct: 3,
		explanation: "Dựa trên trang số 24 của chương 2 của tài liệu, sự đoàn kết giữa giai cấp công nhân và các tầng lớp lao động khác bắt nguồn từ việc họ cùng có lợi ích, cùng chịu sự bóc lột và cùng có mục tiêu chống bất công, giải phóng xã hội.",
	},
	{
		question: "Nguyên nhân sâu xa dẫn đến sự thay thế hình thái kinh tế - xã hội tư bản chủ nghĩa bằng hình thái kinh tế - xã hội cộng sản chủ nghĩa là gì?",
		answers: [
			"Mâu thuẫn giữa tư liệu lao động với đối tượng lao động trong nền sản xuất hàng hóa tư bản chủ nghĩa",
			"Mâu thuẫn giữa lực lượng sản xuất mang tính xã hội hóa ngày càng cao với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất chủ yếu",
			"Mâu thuẫn giữa phương thức sản xuất cộng sản chủ nghĩa với phương thức sản xuất tư bản chủ nghĩa",
			"Mâu thuẫn giữa các giai cấp, tầng lớp lao động trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, nguyên nhân sâu xa của sự thay thế hình thái kinh tế - xã hội tư bản chủ nghĩa là mâu thuẫn giữa lực lượng sản xuất ngày càng xã hội hóa cao với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa.",
	},
	{
		question: "Tiền đề vật chất cho sự ra đời của chủ nghĩa xã hội là gì?",
		answers: [
			"Là điện khí hóa nền sản xuất",
			"Là tự động hóa nền sản xuất",
			"Là tin học hóa nền sản xuất",
			"Là xã hội hóa lực lượng sản xuất",
		],
		correct: 3,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, sự phát triển của lực lượng sản xuất với tính xã hội hóa ngày càng cao là tiền đề vật chất cho sự ra đời của hình thái kinh tế - xã hội cộng sản chủ nghĩa.",
	},
	{
		question: "Chỉ ra luận điểm chính xác nhất ?",
		answers: [
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu phong kiến",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất hàng hóa",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất tự cấp tự túc",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu tư bản",
		],
		correct: 3,
		explanation: "Dựa trên trang số 25 của chương 2 của tài liệu, xã hội xã hội chủ nghĩa hướng tới xóa bỏ chế độ tư hữu về tư liệu sản xuất, cụ thể là chế độ tư hữu tư bản chủ nghĩa.",
	},
	{
		question: "Đặc điểm chủ yếu của thời kỳ quá độ lên chủ nghĩa xã hội là gì?",
		answers: [
			"Chính quyền của giai cấp lao động được thành lập. Nhân dân lao động hoàn toàn làm chủ xã hội",
			"Hệ tư tưởng chính trị của giai cấp công nhân là hệ tư tưởng duy nhất tồn tại trong xã hội. Giai cấp công nhân là chủ thể toàn bộ giá trị văn hóa tinh thần của xã hội",
			"Tồn tại đan xen và đấu tranh lẫn nhau giữa những nhân tố của xã hội mới và những tàn dư của xã hội cũ trên mọi lĩnh vực của đời sống xã hội",
			"Tồn tại kinh tế thị trường định hướng xã hội chủ nghĩa, ở đó, các chủ thể kinh tế đều chịu sự chi phối của quy luật thị trường",
		],
		correct: 2,
		explanation: "Dựa trên trang số 46 của chương 3 của tài liệu, xã hội trong thời kỳ quá độ có sự đan xen giữa những tàn dư của xã hội cũ và những yếu tố mới mang tính chất xã hội chủ nghĩa trên mọi lĩnh vực của đời sống xã hội.",
	},
	{
		question: "Dân chủ là gì?",
		answers: [
			"Là công bằng trong xã hội và thực thi công bằng trong xã hội thi quyền làm chủ của nhân dân",
			"Là quyền lực thuộc về nhân dân và thực thi quyền làm chủ của nhân dân",
			"Là tự do của công dân và đảm bảo tự do cho công dân",
			"Là bình đẳng của công dân và thực thi bình đẳng cho công dân",
		],
		correct: 1,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm và trang số 56 của chương 4 của tài liệu, dân chủ xuất phát từ chữ Hy Lạp \"Demokratos\", có nghĩa là quyền lực thuộc về nhân dân.",
	},
	{
		question: "Chế độ dân chủ đầu tiên ra đời gắn với xã hội nào?",
		answers: [
			"Xã hội cộng sản nguyên thủy",
			"Xã hội chiếm hữu nô lệ",
			"Xã hội phong kiến",
			"Xã hội tư bản chủ nghĩa",
		],
		correct: 1,
		explanation: "Dựa trên trang số 57 của chương 4 của tài liệu, khi trình độ lực lượng sản xuất phát triển, chế độ tư hữu ra đời trong xã hội chiếm hữu nô lệ và nền dân chủ chủ nô xuất hiện.",
	},
	{
		question: "Sự ra đời của nhà nước xã hội chủ nghĩa gắn với sự kiện nào?",
		answers: [
			"Giai cấp công nhân lật đổ nhà nước của giai cấp bóc lột, giành được chính quyền",
			"Giai cấp công nhân đấu tranh chống lại nhà nước của giai cấp bóc lột",
			"Giai cấp công nhân đấu tranh đòi tình trạng áp bức bóc lột của giai cấp tư sản",
			"Giai cấp công nhân đấu tranh đòi tăng lương, giảm giờ làm, cải thiện điều kiện lao động",
		],
		correct: 0,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, nhà nước xã hội chủ nghĩa ra đời là kết quả của cuộc cách mạng do giai cấp vô sản và nhân dân lao động tiến hành nhằm lật đổ nhà nước của giai cấp bóc lột và giành chính quyền.",
	},
	{
		question: "Bản chất của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các giai cấp, tầng lớp trong xã hội",
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các dân tộc, tôn giáo và các cộng đồng khác trong xã hội",
			"Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, tính nhân dân rộng rãi và tính dân tộc sâu sắc",
			"Nhà nước xã hội chủ nghĩa mang bản chất chính trị của các giai cấp, tầng lớp trong lịch sử",
		],
		correct: 2,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, về chính trị, nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, có tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là:",
		answers: [
			"Chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tập thể về tư liệu sản xuất chủ yếu",
			"Chế độ công hữu về tư liệu sản xuất chủ yếu",
			"Chế độ chiếm hữu tư nhân về ruộng đất",
		],
		correct: 2,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất chủ yếu của toàn xã hội.",
	},
	{
		question: "Kiểu nhà nước nào sau đây được V.I. Lênin gọi là nhà nước “nửa nhà nước”?",
		answers: [
			"Nhà nước chủ nô",
			"Nhà nước tư sản",
			"Nhà nước phong kiến .",
			"Nhà nước xã hội chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên trang số 64 của chương 4 của tài liệu, phần câu hỏi ôn tập có nội dung về việc vì sao nhà nước xã hội chủ nghĩa được Lênin gọi là nhà nước \"nửa nhà nước\".",
	},
	{
		question: "Cơ sở kinh tế của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Chế độ sở hữu xã hội về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tư nhân về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu hỗn hợp về tư liệu sản xuất",
			"Chế độ sở hữu tập thể về tư liệu sản xuất",
		],
		correct: 0,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, cơ sở kinh tế của nhà nước xã hội chủ nghĩa là chế độ công hữu về tư liệu sản xuất chủ yếu, tức chế độ sở hữu xã hội.",
	},
	{
		question: "Công cụ hữu hiệu nhất để Nhà nước pháp quyền xã hội chủ nghĩa quản lý xã hội là gì?",
		answers: [
			"Kế hoạch",
			"Chính sách",
			"Pháp luật",
			"Chủ trương",
		],
		correct: 2,
		explanation: "Dựa trên trang số 62 của chương 4 của tài liệu, nhà nước pháp quyền được tổ chức và hoạt động trên cơ sở pháp luật, công dân được giáo dục pháp luật, hiểu biết pháp luật và tuân thủ pháp luật.",
	},
	{
		question: "Đặc điểm của nhà nước pháp quyền xã hội chủ nghĩa là gì?",
		answers: [
			"Quản lý xã hội bằng pháp luật",
			"Quản lý xã hội bằng chính sách",
			"Quản lý xã hội bằng dư luận",
			"Quản lý xã hội bằng niềm tin",
		],
		correct: 0,
		explanation: "Dựa trên trang số 62 của chương 4 của tài liệu, nhà nước pháp quyền xã hội chủ nghĩa được tổ chức và hoạt động dựa trên cơ sở Hiến pháp và pháp luật.",
	},
	{
		question: "Vì sao giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động lại liên minh với nhau trong thời kỳ quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Vì GCCN, giai cấp nông dân và các tầng lớp lao động có sự thống nhất về lợi ích và mục đích",
			"Vì GCCN, giai cấp nông dân và các tầng lớp lao động đều có ý thức giác ngộ cách mạng cao",
			"Vì giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động đều có tổ chức đảng của mình",
			"Vì giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động đều có trình độ văn hóa cao",
		],
		correct: 0,
		explanation: "Dựa trên trang số 70 của chương 5 của tài liệu, trong thời kỳ quá độ lên chủ nghĩa xã hội, các giai cấp và tầng lớp lao động liên minh với nhau do có những lợi ích phù hợp và mục đích chung trong quá trình xây dựng xã hội mới.",
	},
	{
		question: "Vì sao các giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội vừa có sự đấu tranh vừa có sự liên minh?",
		answers: [
			"Vì nền kinh tế trong thời kỳ quá độ lên chủ nghĩa xã hội là kinh tế thị trường",
			"Vì trình độ văn hóa của các giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH có khác nhau",
			"Vì lợi ích của các giai cấp và tầng lớp trong TKQĐ lên CNXH vừa có sự đối kháng vừa có sự thống nhất",
			"Vì hệ tư tưởng của các giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH có mâu thuẫn với nhau.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 69 của chương 5 của tài liệu, cơ cấu xã hội - giai cấp trong thời kỳ quá độ biến đổi trong mối quan hệ vừa có mâu thuẫn, đấu tranh, vừa có liên minh với nhau.",
	},
	{
		question: "Giai cấp công nhân Việt Nam trong thời kỳ quá độ lên chủ nghĩa xã hội biến đổi theo xu hướng nào?",
		answers: [
			"Xu hướng trí thức hóa và trí thức hóa",
			"Xu hướng nông dân hóa",
			"Xu hướng dân tộc hóa",
			"Xu hướng khu vực hóa",
		],
		correct: 0,
		explanation: "Dựa trên trang số 27 của chương 2 của tài liệu, giai cấp công nhân Việt Nam có xu hướng trí tuệ hóa tăng nhanh. Trong đề, cụm \"trí thức hóa và trí thức hóa\" có lỗi lặp từ.",
	},
	{
		question: "Chọn phương án đúng nhất: Theo quan điểm của chủ nghĩa Mác - Lênin, động lực của cách mạng xã hội chủ nghĩa là:",
		answers: [
			"Giai cấp nông dân và giai cấp tư sản",
			"Giai cấp công nhân và giai cấp tư sản",
			"Giai cấp công nhân và giai cấp địa chủ",
			"Giai cấp công nhân và giai cấp nông dân",
		],
		correct: 3,
		explanation: "Dựa trên trang số 70 của chương 5 của tài liệu, giai cấp công nhân liên minh với người bạn đồng minh tự nhiên của mình là giai cấp nông dân trong cách mạng xã hội chủ nghĩa.",
	},
	{
		question: "Chỉ ra luận điểm không chính xác?",
		answers: [
			"Quyền bình đẳng dân tộc là cơ sở cho quyền tự quyết dân tộc",
			"Quyền tự quyết dân tộc là ảo tưởng đối với các dân tộc kém phát triển",
			"Quyền bình đẳng và quyền tự quyết dân tộc không tự nhiên mà có được",
			"Quyền bình đẳng và quyền tự quyết dân tộc đi liền với nhau",
		],
		correct: 1,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, quyền tự quyết là quyền cơ bản của các dân tộc trong việc tự quyết định vận mệnh của dân tộc mình. Vì vậy, quan điểm cho rằng quyền tự quyết dân tộc là ảo tưởng đối với các dân tộc kém phát triển là không chính xác.",
	},
	{
		question: "Yếu tố nào quyết định đến thực hiện quyền bình đẳng dân tộc?",
		answers: [
			"Xóa bỏ tình trạng chênh lệch trong sự phát triển kinh tế, văn hóa của các dân tộc",
			"Xóa bỏ tình trạng giai cấp này áp bức giai cấp khác, trên cơ sở xóa bỏ chế độ tư hữu",
			"Các nhà nước dân tộc có chủ trương, chính sách đúng đắn trong giải quyết quan hệ dân tộc",
			"Các đảng chính trị có đường lối đúng đắn định hướng quan hệ dân tộc",
		],
		correct: 1,
		explanation: "Dựa trên phần giải thích cuối tài liệu trắc nghiệm, để thực hiện quyền bình đẳng dân tộc cần xóa bỏ nạn người áp bức, bóc lột người; về cơ sở sâu xa là xóa bỏ chế độ chiếm hữu tư nhân về tư liệu sản xuất.",
	},
	{
		question: "Chỉ ra luận điểm không chính xác?",
		answers: [
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó là giải pháp hữu hiệu để thực hiện quyền bình đẳng và quyền tự quyết dân tộc",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó là hạt nhân đoàn kết các lực lượng cách mạng trong đấu tranh chống áp bức, bóc lột",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó thể hiện rõ lập trường của giai cấp công nhân trong giải quyết quan hệ dân tộc",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó thể hiện rõ xu thế toàn cầu hóa và khu vực hóa trong vấn đề dân tộc",
		],
		correct: 3,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, liên hiệp công nhân các dân tộc nhằm đoàn kết đấu tranh, bảo vệ độc lập dân tộc và tiến bộ xã hội. Nội dung này không được xác lập chỉ vì xu thế toàn cầu hóa hay khu vực hóa.",
	},
	{
		question: "Theo Chủ tịch Hồ Chí Minh, con đường để đấu tranh cho độc lập, tự do, chủ quyền của dân tộc Việt Nam là gì?",
		answers: [
			"Cách mạng phong kiến",
			"Cách mạng tư sản",
			"Cách mạng vô sản",
			"Cách mạng không ngừng",
		],
		correct: 2,
		explanation: "Dựa trên kiến thức cơ bản xuyên suốt và trang số 16 của chương 1 của tài liệu, độc lập dân tộc phải gắn liền với chủ nghĩa xã hội; con đường cách mạng vô sản được xem là con đường giải phóng dân tộc triệt để.",
	},
	{
		question: "Tôn giáo là gì?",
		answers: [
			"Tôn giáo là niềm tin của con người tồn tại với hệ thống quan niệm và hoạt động bao gồm đối tượng tôn thờ, giáo lý, giáo luật, lễ nghi và tổ chức",
			"Tôn giáo là niềm tin của con người được khái quát thành triết lý luận khoa học và cách mạng, thể hiện lập trường chính trị của giai cấp công nhân và nhân dân lao động trong đấu tranh giải cấp",
			"Tôn giáo là một tổ chức chính trị - xã hội đặc biệt, ra đời nhằm thực hiện vai trò thống trị chính trị của một giai cấp nhất định trong xã hội",
			"Tôn giáo là một tổ chức xã hội, là đại diện cho quần chúng nhân dân lao động trong công xã nguyên thủy , là tổ chức tiền thân của nhà nước trong xã hội có sự phân chia giai cấp.",
		],
		correct: 0,
		explanation: "Dựa trên trang số 90 của chương 6 của tài liệu, tôn giáo là một thực thể xã hội có niềm tin sâu sắc vào đấng siêu nhiên, có hệ thống giáo thuyết gồm giáo lý, giáo luật, lễ nghi, đồng thời có cơ sở thờ tự và tổ chức nhân sự.",
	},
	{
		question: "Yếu tố quan trọng nhất làm cho các tôn giáo tồn tại lâu dài là gì?",
		answers: [
			"Ý thức phản kháng của nhân dân đối với bất công xã hội",
			"Niềm tin vào sự tồn tại của các đấng siêu nhiên thần thánh",
			"Khát vọng được giải thoát",
			"Niềm tin vào thế giới hiện thực",
		],
		correct: 1,
		explanation: "Dựa trên trang số 90 của chương 6 của tài liệu, cốt lõi của tôn giáo là niềm tin sâu sắc vào đấng siêu nhiên, đấng tối cao hoặc thần linh để tôn thờ.",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Xây dựng lý luận về đảng kiểu mới của giai cấp công nhân.",
			"Xây dựng lý luận về đảng kiểu mới của giai cấp nông dân.",
			"Xây dựng lý luận về đảng của nhiều giai cấp, tầng lớp trong xã hội.",
			"Xây dựng lý luận về đảng của các dân tộc thuộc địa và phụ thuộc",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, V.I. Lênin đã xây dựng lý luận về đảng cách mạng kiểu mới của giai cấp công nhân.",
	},
];