const cnxh_ptitBank = [
	{
		question: "Nguồn gốc lý luận trực tiếp ra đời chủ nghĩa xã hội khoa học là",
		answers: [
			"Triết học cổ điển Đức",
			"Kinh tế chính trị học cổ điển Anh",
			"Chủ nghĩa xã hội không tưởng – phê phán Đang hoạt động",
			"Cả a, b và c",
		],
		correct: 2,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chỉ ra rằng \"Chủ nghĩa không tưởng phê phán mà đại biểu là H.Xanh Ximông... là tiền đề lý luận\", từ nội dung này (và đối chiếu với nội dung lặp lại ở Câu 24), ta suy ra được là \"Đáp án C\" (Lưu ý: chữ \"Đang hoạt động\" trong đề là lỗi đánh máy từ chữ \"Pháp\").",
	},
	{
		question: "Thực chất của TKQĐ lên CNXH là gì?",
		answers: [
			"Là cuộc cải biến cách mạng về kinh tế",
			"Là cuộc cải biến cách mạng về chính trị",
			"Là cuộc cải biến cách mạng về tư tưởng và văn hoá",
			"Tất cả các câu đều đúng",
		],
		correct: 3,
		explanation: "Dựa trên trang số 45 và 46 của chương 3 của tài liệu, chỉ ra rằng \"Thực chất của thời kỳ quá độ lên chủ nghĩa xã hội là thời kỳ cải biến cách mạng... trên tất cả các lĩnh vực, kinh tế, chính trị, văn hóa, xã hội\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Thời kỳ quá độ lên chủ nghĩa xã hội trên phạm vi cả nước ta bắt đầu",
		answers: [
			"8/1945",
			"5/1954",
			"4/1975",
			"2/1930",
		],
		correct: 2,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Thời kỳ quá độ lên CNXH ở Việt Nam bắt đầu từ năm 1954 ở miền Bắc và từ năm 1975 trên phạm vi cả nước, sau khi đất nước đã hoàn toàn độc lập và cả nước thống nhất\", từ nội dung này, ta suy ra được là \"Đáp án C (tương ứng với thời điểm 4/1975 cho cả nước)\".",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa xuất hiện đầu tiên ở nước nào?",
		answers: [
			"Pháp",
			"Đức",
			"Nga",
			"Mỹ",
		],
		correct: 2,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Dân chủ xã hội chủ nghĩa xuất hiện đầu tiên ở nước Nga. Điều này đã xảy ra sau cách mạng tháng 10 Nga năm 1917\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa mang bản chất...",
		answers: [
			"giai cấp nông dân",
			"giai cấp công nhân",
			"tầng lớp trí thức",
			"tầng lớp doanh nhân",
		],
		correct: 1,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, chỉ ra rằng \"Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi, tính dân tộc sâu sắc\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Đặc trưng chính trị của nền dân chủ xã hội chủ nghĩa có tính...",
		answers: [
			"nhân dân rộng rãi",
			"dân tộc sâu sắc",
			"Cách mạng",
			"Cả A. B đều đúng",
		],
		correct: 3,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu và phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Tính nhân dân rộng rãi được thể hiện... Tính dân tộc sâu sắc được thể hiện...\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là ...",
		answers: [
			"Chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tập thể về tư liệu sản xuất chủ yếu",
			"Chế độ công hữu về tư liệu sản xuất chủ yếu",
			"Cả A, B, C",
		],
		correct: 2,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, chỉ ra rằng \"Nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất chủ yếu của toàn xã hội\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Dân chủ xã hội chủ nghĩa vừa mang tính... vừa mang tính... vừa mang tính...",
		answers: [
			"Giai cấp... tầng lớp",
			"Giai cấp... dân tộc",
			"Giai cấp... dân tộc... nhân loại",
			"Giai cấp... dân tộc... nhân dân",
		],
		correct: 3,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, chỉ ra rằng \"Dân chủ xã hội chủ nghĩa vừa có bản chất giai cấp công nhân, vừa có tính nhân dân rộng rãi, tính dân tộc sâu sắc\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chọn phương án đúng nhất: Nhà nước xã hội chủ nghĩa mang",
		answers: [
			"bản chất giai cấp công nhân và nhân dân lao động.",
			"bản chất giai cấp công nhân và giai cấp nông dân.",
			"ban chất giai cấp công nhân, tính quần chúng rộng rãi.",
			"bản chất giai cấp công nhân, tính nhân dân rộng rãi và tính dân tộc sâu sắc.",
		],
		correct: 3,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, chỉ ra rằng \"Về chính trị: Nhà nước xã hội chủ nghĩa (nhà nước chuyên chính vô sản) mang bản chất của giai cấp công nhân, có tính nhân dân rộng rãi và tính dân tộc sâu sắc\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chọn phương án đúng nhất: Hệ thống chính trị xã hội chủ nghĩa ở Việt Nam hiện nay bao gồm...",
		answers: [
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, Mặt trận Tổ quốc Việt Nam.",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, các tổ chức xã hội.",
			"Đảng Cộng sản Việt Nam, Nhà nước xã hội chủ nghĩa, các tổ chức chính trị - xã hội.",
		],
		correct: 3,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Hệ thống chính trị xã hội chủ nghĩa ở Việt Nam bao gồm Đảng Cộng Sản Việt Nam, Nhà nước Cộng Hòa Xã Hội Chủ Nghĩa Việt Nam và các tổ chức chính trị xã hội...\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Điền vào chỗ trống: Trong xu hướng thứ nhất, do sự thức tỉnh và sự trưởng thành của ý thức dân tộc mà các cộng đồng dân cư muốn .... để xác lập dân tộc độc lập.",
		answers: [
			"đoàn kết.",
			"hợp tác với nhau.",
			"tách ra.",
			"hợp nhất lại.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 86 của chương 6 của tài liệu và phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"cộng đồng dân cư muốn tách ra để hình thành cộng đồng dân tộc độc lập\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Điền vào chỗ trống: Quyền bình đẳng giữa các dân tộc là quyền... của các dân tộc.",
		answers: [
			"phát triển.",
			"sống còn.",
			"Thiêng liêng.",
			"Cao cả.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, chỉ ra rằng \"Ý nghĩa: Là quyền cơ bản, thiêng liêng, là cơ sở để thực hiện quyền dân tộc tự quyết\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Điền vào chỗ trống: Quyền dân tộc tự quyết là quyền ... đối với vận mệnh của dân tộc mình.",
		answers: [
			"tự quyết định.",
			"làm chủ.",
			"tự lo liệu.",
			"tự do phát triển",
		],
		correct: 0,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, chỉ ra rằng \"Là quyền của các dân tộc tự quyết định lấy vận mệnh của dân tộc mình\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Chọn phương án đúng nhất: Dưới chủ nghĩa xã hội, tôn giáo vẫn tồn tại do các nguyên nhân:",
		answers: [
			"Nhận thức, chính trị.",
			"Nhận thức, kinh tế, tâm lý, chính trị, văn hoá.",
			"Nhận thức, văn hoá, tư tưởng.",
			"Nhận thức, kinh tế, văn hoá, tư tưởng.",
		],
		correct: 1,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Tôn giáo vẫn còn tồn tại dưới Chủ nghĩa Xã hội do các nguyên nhân như: + Nhận thức... + Tâm lý... + Chính trị... + Văn hóa\" (cùng với nguyên nhân Kinh tế ở trang 90, 91 Giáo trình), từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Trong chủ nghĩa xã hội cần phải...",
		answers: [
			"đấu tranh xóa bỏ tôn giáo",
			"tạo điều kiện cho tôn giáo phát triển",
			"đảm bảo tôn trọng quyền tự do tín ngưỡng và không tín ngưỡng của nhân dân",
			"hạn chế sự phát triển của tôn giáo",
		],
		correct: 2,
		explanation: "Dựa trên trang số 92 của chương 6 của tài liệu, chỉ ra rằng \"Nguyên tắc giải quyết vấn đề tôn giáo... Tôn trọng, bảo đảm quyền tự do tín ngưỡng và không tín ngưỡng của nhân dân\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Sự bất lực của con người trước sức mạnh tự phát của tự nhiên và xã hội là nội dung của nguyên nhân nào lý giải sự tồn tại của tôn giáo trong tiến trình xây dựng chủ nghĩa xã hội?",
		answers: [
			"Chính trị - xã hội",
			"Nhận thức",
			"Kinh tế",
			"Tâm lý",
		],
		correct: 2,
		explanation: "Dựa trên trang số 91 của chương 6 của tài liệu, chỉ ra rằng \"Nguồn gốc tự nhiên, kinh tế - xã hội... do không giải thích được... lo sợ trước sự thống trị của các lực lượng xã hội nên con người trông chờ vào sự giải phóng của một lực lượng siêu nhiên\", từ nội dung này, ta suy ra được là \"Đáp án C (hoặc A, vì cùng chung cụm nguồn gốc Kinh tế - Xã hội)\".",
	},
	{
		question: "Khoa học chưa lý giải được nhiều hiện tượng tự nhiên, xã hội và của con người là nội dung của nguyên nhân nào lý giải sự tồn tại của tôn giáo trong tiến trình xây dựng chủ nghĩa xã hội?",
		answers: [
			"Văn hóa",
			"Tâm lý",
			"Chính trị - xã hội",
			"Nhận thức",
		],
		correct: 3,
		explanation: "Dựa trên trang số 91 của chương 6 của tài liệu, chỉ ra rằng \"Nguồn gốc nhận thức... khi những điều mà khoa học chưa giải thích được, thì điều đó thường được giải thích thông qua lăng kính các tôn giáo\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chủ nghĩa xã hội là gì?",
		answers: [
			"Là phong trào thực tiễn, phong trào đấu tranh của nhân dân lao động chống các giai cấp thống trị",
			"Là trào lưu tư tưởng, lý luận phản ánh lý tưởng giải phóng nhân dân lao động khỏi áp bức, bóc lột, bất công;",
			"Là một khoa học - Chủ nghĩa xã hội khoa học;",
			"Là một chế độ xã hội hiện thực tốt đẹp, xã hội xã hội chủ nghĩa",
			"Cả A,B,C,D",
		],
		correct: 4,
		explanation: "Dựa trên trang số 34 của chương 3 của tài liệu, chỉ ra rằng \"Chủ nghĩa xã hội được tiếp cận trên một số góc độ: Một là phong trào thực tiễn... Hai là trào lưu tư tưởng, lý luận... Ba là một khoa học... Bốn là một chế độ xã hội tốt đẹp\", từ nội dung này, ta suy ra được là \"Đáp án E\".",
	},
	{
		question: "Phát minh nào không phải là một trong những tiền đề khoa học tự nhiên cho sự ra đời của chủ nghĩa xã hội khoa học?",
		answers: [
			"Học thuyết Tế bào",
			"Học thuyết Tiến hóa",
			"Thuyết Nguyên tử",
			"Định luật bảo toàn và chuyển hóa năng lượng",
		],
		correct: 2,
		explanation: "Dựa trên trang số 4 và 5 của chương 1 của tài liệu, chỉ ra rằng \"Ba phát minh 'vạch thời đại' trong vật lý học và sinh học đó là: Học thuyết tiến hóa, Định luật bảo toàn và chuyển hóa năng lượng, Học thuyết tế bào\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Tư tưởng xã hội chủ nghĩa là gì?",
		answers: [
			"Là một hệ thống những quan niệm phản ánh những nhu cầu, những ước mơ, nguyện vọng của các giai cấp lao động về một xã hội không có áp bức và bóc lột",
			"Là những thành tựu của con người đạt được trong quá trình đấu tranh giải phóng giai cấp.",
			"Là chế độ xã hội không có áp bức bóc lột, mọi người đều bình đẳng tự do.",
			"Cả a, b, c",
		],
		correct: 0,
		explanation: "Dựa trên trang số 34 của chương 3 của tài liệu, chỉ ra rằng \"trào lưu tư tưởng, lý luận phản ánh lý tưởng giải phóng nhân dân lao động khỏi áp bức, bóc lột, bất công\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Những yếu tố tư tưởng XHCN được xuất hiện từ khi nào?",
		answers: [
			"Chế độ tư bản chủ nghĩa ra đời",
			"Sự xuất hiện chế độ tư hữu, xuất hiện giai cấp thống trị và bóc lột",
			"Sự xuất hiện giai cấp công nhân",
			"Thời cộng sản nguyên thủy",
		],
		correct: 1,
		explanation: "Dựa trên nguyên lý chung (và xuyên suốt chương 1, chương 3) của tài liệu, đã chỉ ra rằng: Tư tưởng và khát vọng về CNXH xuất hiện khi bắt đầu có sự áp bức, bóc lột do chế độ tư hữu sinh ra. Từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Là những quy luật và tính quy luật chính trị – xã hội của quá trình phát sinh, hình thành và phát triển hình thái kinh tế - xã hội cộng sản chủ nghĩa",
			"Là những quy luật kinh tế hình thành, phát triển và hoàn thiện của các hình thái kinh tế - xã hội.",
			"Là những quy luật và tính quy luật chính trị – xã hội của quá trình phát sinh, hình thành và phát triển hình thái kinh tế - xã hội tư bản chủ nghĩa",
			"Cả a, b và c",
		],
		correct: 0,
		explanation: "Dựa trên trang số 19 của chương 1 của tài liệu, chỉ ra rằng \"đối tượng nghiên cứu của Chủ nghĩa xã hội khoa học: những qui luật, tính qui luật chính trị - xã hội của quá trình phát sinh, hình thành và phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Hạn chế của chủ nghĩa xã hội không tưởng trước Mác là...",
		answers: [
			"Chưa thấy được sứ mệnh lịch sử của giai cấp công nhân",
			"Chưa chỉ ra được con đường đấu tranh cách mạng",
			"Không luận chứng được một cách khoa học về bản chất của chủ nghĩa tư bản và quy luật phát triển của chủ nghĩa tư bản",
			"Cả A.B.C",
		],
		correct: 3,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chỉ ra rằng \"Hạn chế: Thứ nhất, không phát hiện ra được quy luật vận động... bản chất, quy luật vận động, phát triển của chủ nghĩa tư bản... Thứ hai, không phát hiện ra lực lượng xã hội tiên phong... giai cấp công nhân; không chỉ ra được những biện pháp hiện thực cải tạo xã hội\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Nguồn gốc lý luận trực tiếp ra đời chủ nghĩa xã hội khoa học là....",
		answers: [
			"Triết học cổ điển Đức",
			"Kinh tế chính trị học cổ điển Anh",
			"Chủ nghĩa xã hội không tưởng – phê phán",
			"Cả a, b và c",
		],
		correct: 2,
		explanation: "Dựa trên trang số 5 của chương 1 của tài liệu, chỉ ra rằng \"Chủ nghĩa không tưởng phê phán... là tiền đề lý luận\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Ai là người đã có công lao biến chủ nghĩa xã hội từ khoa học trở thành hiện thực?",
		answers: [
			"C. Mac",
			"Ph. Anh Ngân",
			"V.Lênin",
			"Hồ Chí Minh",
		],
		correct: 2,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm (và trang 10, chương 1), chỉ ra rằng \"Vai trò của Lê nin là đưa chủ nghĩa xã hội khoa học từ góc độ lý luận trở thành hiện thực sau sự kiện cách mạng tháng 10 Nga năm 1917\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Ai là người đã có công lao biến chủ nghĩa xã hội từ không tưởng trở thành khoa học?",
		answers: [
			"C. Mác và Ph. Ăngghen",
			"V.ILênin",
			"Hồ Chí Minh",
			"Cả A,B,C",
		],
		correct: 0,
		explanation: "Dựa trên trang số 10 của chương 1 của tài liệu, chỉ ra rằng \"công lao của C.Mác và Ph.Ăngghen là phát triển chủ nghĩa xã hội từ không tưởng thành khoa học\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Trong phương thức sản xuất tư bản chủ nghĩa, mâu thuẫn trong lĩnh vực kinh tế là mâu thuẫn giữa....",
		answers: [
			"Lực lượng sản xuất mang tính xã hội hóa với quan hệ sản xuất mang tính xã hội tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính cá nhân với quan hệ sản xuất mang tính xã hội tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính xã hội hóa với quan hệ sản xuất mang tính tư nhân tư bản chủ nghĩa",
			"Lực lượng sản xuất mang tính cá nhân với quan hệ sản xuất mang tính tư nhân tư bản chủ nghĩa",
		],
		correct: 2,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, chỉ ra rằng \"lực lượng sản xuất càng được cơ khi hóa, hiện đại hóa càng mang tính xã hội hóa cao, thì càng mâu thuẫn với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Quy luật chính trị - xã hội phản ánh quan hệ nào sau đây?",
		answers: [
			"Quan hệ giữa các thiết chế văn hóa",
			"Quan hệ giữa các giai cấp, tầng lớp trong xã hội.",
			"Quan hệ giữa các cộng đồng dân cư trong xã hội",
			"Quan hệ giữa các tổ chức trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên trang số 18 và 19 của chương 1 của tài liệu, đã chỉ ra rằng: Đối tượng của CNXHKH là quy luật chính trị - xã hội, phản ánh con đường, hình thức, phương pháp đấu tranh cách mạng của giai cấp công nhân và các tầng lớp nhân dân (tức quan hệ giữa các giai cấp, tầng lớp). Từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là...",
		answers: [
			"Xây dựng lý luận về đảng kiểu mới của giai cấp công nhân.",
			"Xây dựng lý luận về đảng kiểu mới của giai cấp nông dân.",
			"Xây dựng lý luận về đảng của nhiều giai cấp, tầng lớp trong xã hội",
			"Xây dựng lý luận về đảng của các dân tộc thuộc địa và phụ thuộc",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, chỉ ra rằng \"V.I.Lênin đã xây dựng lý luận về đảng cách mạng kiểu mới của giai cấp công nhân\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Xây dựng lý luận về cách mạng dân chủ kiểu mới.",
			"Xây dựng lý luận về cách mạng dân tộc kiểu mới",
			"Xây dựng lý luận về cách mạng phong kiến kiểu mới",
			"Xây dựng lý luận về cách mạng xã hội kiểu mới",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, chỉ ra rằng \"V.I.Lênin đã hoàn chỉnh lý luận về cách mạng xã hội chủ nghĩa và chuyên chính vô sản, cách mạng dân chủ tư sản kiểu mới...\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Cuộc cách mạng công nghiệp lần thứ nhất trong phương thức sản xuất tư bản chủ nghĩa diễn ra đầu tiên ở quốc gia nào?",
		answers: [
			"Anh.",
			"Pháp",
			"Đức",
			"Nga.",
		],
		correct: 0,
		explanation: "Dựa trên kiến thức chung và trang số 5 của chương 1 của tài liệu, đã chỉ ra rằng: Cách mạng công nghiệp ra đời sớm nhất gắn với tư tưởng \"Kinh tế chính trị học cổ điển Anh\". Từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Đối tượng nghiên cứu của chủ nghĩa xã hội khoa học là:",
		answers: [
			"Những quy luật kinh tế của phương thức sản xuất tư bản chủ nghĩa và sự ra đời của phương thức sản xuất mới - phương thức sản xuất cộng sản chủ nghĩa",
			"Những quy luật khách quan của quá trình cách mạng xã hội chủ nghĩa.",
			"Những quy luật vận động, phát triển chung nhất của tự nhiên, xã hội và tư duy.",
			"Cả A, B, C đều sai",
		],
		correct: 3,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Chủ nghĩa Xã hội Khoa học không chỉ nghiên cứu quy luật kinh tế mà còn bao gồm cả những quy luật chính trị xã hội của quá trình phát triển của Chủ nghĩa Tư bản sang chủ nghĩa Xã hội...\", do các đáp án A, B, C đều chưa mô tả chính xác và đầy đủ, từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Một trong những đóng góp quan trọng của Đảng Cộng sản Việt Nam vào lý luận của chủ nghĩa xã hội khoa học là...",
		answers: [
			"Tư tưởng độc lập dân tộc gắn liền với chủ nghĩa xã hội.",
			"Tư tưởng dân chủ",
			"Tư tưởng nhân văn",
			"Tư tưởng đoàn kết",
		],
		correct: 0,
		explanation: "Dựa trên trang số 16 của chương 1 của tài liệu, chỉ ra rằng \"Độc lập dân tộc gắn liền với chủ nghĩa xã hội là quy luật của cách mạng Việt Nam\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân là giai cấp tiên phong cách mạng vì họ là giai cấp:",
		answers: [
			"Đại biểu cho phương thức sản xuất tiên tiến",
			"Được trang bị lý luận khoa học cách mạng",
			"Luôn đi đầu trong mọi phong trào cách mạng",
			"Cả A, B, C",
		],
		correct: 3,
		explanation: "Dựa trên trang số 23 của chương 2 của tài liệu, chỉ ra rằng \"giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến... có những phẩm chất đặc biệt... Đó là một giai cấp cách mạng và có tinh thần cách mạng triệt để\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết nội bộ giai cấp vì họ có chung:",
		answers: [
			"Địa vị kinh tế - xã hội",
			"Điều kiện làm việc",
			"Điều kiện sống",
			"Cả A, B, C",
		],
		correct: 0,
		explanation: "Dựa trên trang số 26 của chương 2 của tài liệu, chỉ ra rằng \"Trong xã hội tư bản chủ nghĩa, giai cấp công nhân không có tư liệu sản xuất chủ yếu, phải bán sức lao động... (thuộc về Địa vị kinh tế - xã hội của giai cấp công nhân)\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Chọn phương án đúng nhất: Trong chế độ tư bản chủ nghĩa, giai cấp công nhân có thể đoàn kết với các giai cấp, tầng lớp lao động khác vì họ:",
		answers: [
			"Có chung lợi ích kinh tế",
			"Đều bị giai cấp tư sản bóc lột",
			"Có chung nguyện vọng được giải phóng",
			"Cả A, B, C",
		],
		correct: 3,
		explanation: "Dựa trên trang số 24 của chương 2 của tài liệu, đã chỉ ra rằng: Sự đoàn kết giữa giai cấp công nhân và các tầng lớp lao động khác bắt nguồn từ việc họ cùng chung lợi ích, cùng bị bóc lột và có chung mục tiêu chống bất công, giải phóng xã hội. Từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Nguyên nhân sâu xa dẫn đến sự thay thế hình thái kinh tế - xã hội tư bản chủ nghĩa bằng hình thái kinh tế - xã hội cộng sản chủ nghĩa là gì?",
		answers: [
			"Mâu thuẫn giữa tư liệu lao động với đối tượng lao động trong nền sản xuất hàng hóa tư bản chủ nghĩa",
			"Mâu thuẫn giữa lực lượng sản xuất mang tính xã hội hóa ngày càng cao với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa về tư liệu sản xuất chủ yếu",
			"Mâu thuẫn giữa phương thức sản xuất cộng sản chủ nghĩa với phương thức sản xuất tư bản chủ nghĩa",
			"Mâu thuẫn giữa các giai cấp, tầng lớp lao động trong xã hội",
		],
		correct: 1,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, chỉ ra rằng \"lực lượng sản xuất càng được cơ khi hóa, hiện đại hóa càng mang tính xã hội hóa cao, thì càng mâu thuẫn với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ chiếm hữu tư nhân tư bản chủ nghĩa\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Tiền đề vật chất cho sự ra đời của chủ nghĩa xã hội là gì?",
		answers: [
			"Là điện khí hóa nền sản xuất",
			"Là tự động hóa nền sản xuất",
			"Là tin học hóa nền sản xuất",
			"Là xã hội hóa lực lượng sản xuất",
		],
		correct: 3,
		explanation: "Dựa trên trang số 36 của chương 3 của tài liệu, chỉ ra rằng \"càng mang tính xã hội hóa cao, thì càng mâu thuẫn... Sự phát triển của lực lượng sản xuất... là tiền đề, điều kiện cho sự ra đời của hình thái KT-XH cộng sản chủ nghĩa\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chỉ ra luận điểm chính xác nhất ?",
		answers: [
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu phong kiến",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất hàng hóa",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ sản xuất tự cấp tự túc",
			"Xã hội xã hội chủ nghĩa thực hiện xóa bỏ chế độ tư hữu tư bản",
		],
		correct: 3,
		explanation: "Dựa trên trang số 25 của chương 2 của tài liệu, chỉ ra rằng \"xóa bỏ triệt để chế độ tư hữu về tư liệu sản xuất\" (cụ thể là tư hữu tư bản chủ nghĩa), từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Đặc điểm chủ yếu của thời kỳ quá độ lên chủ nghĩa xã hội là gì?",
		answers: [
			"Chính quyền của giai cấp lao động được thành lập. Nhân dân lao động hoàn toàn làm chủ xã hội",
			"Hệ tư tưởng chính trị của giai cấp công nhân là hệ tư tưởng duy nhất tồn tại trong xã hội. Giai cấp công nhân là chủ thể toàn bộ giá trị văn hóa tinh thần của xã hội",
			"Tồn tại đan xen và đấu tranh lẫn nhau giữa những nhân tố của xã hội mới và những tàn dư của xã hội cũ trên mọi lĩnh vực của đời sống xã hội",
			"Tồn tại kinh tế thị trường định hướng xã hội chủ nghĩa, ở đó, các chủ thể kinh tế đều chịu sự chi phối của quy luật thị trường",
		],
		correct: 2,
		explanation: "Dựa trên trang số 46 của chương 3 của tài liệu, chỉ ra rằng \"Xã hội của thời kỳ quá độ là xã hội có sự đan xen của nhiều tàn dư về mọi phương diện... và những yếu tố mới mang tính chất xã hội chủ nghĩa\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Dân chủ là gì?",
		answers: [
			"Là công bằng trong xã hội và thực thi công bằng trong xã hội thi quyền làm chủ của nhân dân",
			"Là quyền lực thuộc về nhân dân và [thực thi quyền làm chủ của nhân dân - in theo đính chính ở trang cuối]",
			"Là tự do của công dân và đảm bảo tự do cho công dân",
			"Là bình đẳng của công dân và thực thi bình đẳng cho công dân",
		],
		correct: 1,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm (đính chính lỗi đánh máy) và trang số 56 của chương 4 của tài liệu, chỉ ra rằng \"Dân chủ xuất phát từ chữ Hylạp “Demokratos”, có nghĩa là quyền lực thuộc về nhân dân\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Chế độ dân chủ đầu tiên ra đời gắn với xã hội nào?",
		answers: [
			"Xã hội cộng sản nguyên thủy",
			"Xã hội chiếm hữu nô lệ",
			"Xã hội phong kiến",
			"Xã hội tư bản chủ nghĩa",
		],
		correct: 1,
		explanation: "Dựa trên trang số 57 của chương 4 của tài liệu, chỉ ra rằng \"Trong chế độ chiếm hữu nô lệ: khi trình độ của lực lượng sản xuất phát triển, sự ra đời chế độ tư hữu, nền dân chủ chủ nô ra đời\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Sự ra đời của nhà nước xã hội chủ nghĩa gắn với sự kiện nào?",
		answers: [
			"Giai cấp công nhân lật đổ nhà nước của giai cấp bóc lột, giành được chính quyền",
			"Giai cấp công nhân đấu tranh chống lại nhà nước của giai cấp bóc lột",
			"Giai cấp công nhân đấu tranh đòi tình trạng áp bức bóc lột của giai cấp tư sản",
			"Giai cấp công nhân đấu tranh đòi tăng lương, giảm giờ làm, cải thiện điều kiện lao động",
		],
		correct: 0,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, chỉ ra rằng \"nhà nước xã hội chủ nghĩa ra đời là kết quả của cuộc cách mạng do giai cấp vô sản và nhân dân lao động tiến hành...\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Bản chất của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các giai cấp, tầng lớp trong xã hội",
			"Nhà nước xã hội chủ nghĩa là sự liên hiệp tự nguyện của các dân tộc, tôn giáo và các cộng đồng khác trong xã hội",
			"Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, tính nhân dân rộng rãi và tính dân tộc sâu sắc",
			"Nhà nước xã hội chủ nghĩa mang bản chất chính trị của các giai cấp, tầng lớp trong lịch sử",
		],
		correct: 2,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, chỉ ra rằng \"Về chính trị: Nhà nước xã hội chủ nghĩa... mang bản chất của giai cấp công nhân, có tính nhân dân rộng rãi và tính dân tộc sâu sắc\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Cơ sở kinh tế của nền dân chủ xã hội chủ nghĩa là:",
		answers: [
			"Chế độ tư hữu về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tập thể về tư liệu sản xuất chủ yếu",
			"Chế độ công hữu về tư liệu sản xuất chủ yếu",
			"Chế độ chiếm hữu tư nhân về ruộng đất",
		],
		correct: 2,
		explanation: "Dựa trên trang số 58 của chương 4 của tài liệu, chỉ ra rằng \"Nền dân chủ xã hội chủ nghĩa dựa trên chế độ công hữu về tư liệu sản xuất chủ yếu của toàn xã hội\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Kiểu nhà nước nào sau đây được V.I. Lênin gọi là nhà nước “nửa nhà nước”?",
		answers: [
			"Nhà nước chủ nô",
			"Nhà nước tư sản",
			"Nhà nước phong kiến .",
			"Nhà nước xã hội chủ nghĩa",
		],
		correct: 3,
		explanation: "Dựa trên trang số 64 của chương 4 của tài liệu, đã chỉ ra rằng: Tại mục câu hỏi ôn tập, câu số 4 nhắc tới \"Vì sao nhà nước xã hội chủ nghĩa được Lênin gọi là nhà nước 'nửa nhà nước'\". Từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Cơ sở kinh tế của nhà nước xã hội chủ nghĩa là gì?",
		answers: [
			"Chế độ sở hữu xã hội về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu tư nhân về tư liệu sản xuất chủ yếu",
			"Chế độ sở hữu hỗn hợp về tư liệu sản xuất",
			"Chế độ sở hữu tập thể về tư liệu sản xuất",
		],
		correct: 0,
		explanation: "Dựa trên trang số 60 của chương 4 của tài liệu, chỉ ra rằng \"Về kinh tế: Nhà nước xã hội chủ nghĩa có cơ sở kinh tế là chế độ công hữu về tư liệu sản xuất chủ yếu\" (Công hữu đồng nghĩa với sở hữu xã hội), từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Công cụ hữu hiệu nhất để Nhà nước pháp quyền xã hội chủ nghĩa quản lý xã hội là gì?",
		answers: [
			"Kế hoạch",
			"Chính sách",
			"Pháp luật",
			"Chủ trương",
		],
		correct: 2,
		explanation: "Dựa trên trang số 62 của chương 4 của tài liệu, chỉ ra rằng \"Nhà nước pháp quyền được hiểu là nhà nước mà ở đó, tất cả mọi công dân đều được giáo dục pháp luật và phải hiểu biết pháp luật, tuân thủ pháp luật\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Đặc điểm của nhà nước pháp quyền xã hội chủ nghĩa là gì?",
		answers: [
			"Quản lý xã hội bằng pháp luật",
			"Quản lý xã hội bằng chính sách",
			"Quản lý xã hội bằng dư luận",
			"Quản lý xã hội bằng niềm tin",
		],
		correct: 0,
		explanation: "Dựa trên trang số 62 của chương 4 của tài liệu, chỉ ra rằng \"Được tổ chức và hoạt động dựa trên cơ sở của Hiến pháp và pháp luật\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Vì sao giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động lại liên minh với nhau trong thời kỳ quá độ lên chủ nghĩa xã hội?",
		answers: [
			"Vì GCCN, giai cấp nông dân và các tầng lớp lao động có sự thống nhất về lợi ích và mục đích",
			"Vì GCCN, giai cấp nông dân và các tầng lớp lao động đều có ý thức giác ngộ cách mạng cao",
			"Vì giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động đều có tổ chức đảng của mình",
			"Vì giai cấp công nhân, giai cấp nông dân và các tầng lớp lao động đều có trình độ văn hóa cao",
		],
		correct: 0,
		explanation: "Dựa trên trang số 70 của chương 5 của tài liệu, chỉ ra rằng \"mỗi giai cấp đứng ở vị trí trung tâm đều phải tìm cách liên minh với các giai cấp, tầng lớp xã hội khác có những lợi ích phù hợp với mình để tập hợp lực lượng thực hiện những nhu cầu và lợi ích chung\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Vì sao các giai cấp, tầng lớp trong thời kỳ quá độ lên chủ nghĩa xã hội vừa có sự đấu tranh vừa có sự liên minh?",
		answers: [
			"Vì nền kinh tế trong thời kỳ quá độ lên chủ nghĩa xã hội là kinh tế thị trường",
			"Vì trình độ văn hóa của các giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH có khác nhau",
			"Vì lợi ích của các giai cấp và tầng lớp trong TKQĐ lên CNXH vừa có sự đối kháng vừa có sự thống nhất",
			"Vì hệ tư tưởng của các giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH có mâu thuẫn với nhau.",
		],
		correct: 2,
		explanation: "Dựa trên trang số 69 của chương 5 của tài liệu, chỉ ra rằng \"cơ cấu xã hội - giai cấp biến đổi và phát triển trong mối quan hệ vừa có mâu thuẫn, đấu tranh, vừa có mối quan hệ liên minh với nhau\", từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Giai cấp công nhân Việt Nam trong thời kỳ quá độ lên chủ nghĩa xã hội biến đổi theo xu hướng nào?",
		answers: [
			"Xu hướng trí thức hóa và trí thức hóa",
			"Xu hướng nông dân hóa",
			"Xu hướng dân tộc hóa",
			"Xu hướng khu vực hóa",
		],
		correct: 0,
		explanation: "Dựa trên trang số 27 của chương 2 của tài liệu, chỉ ra rằng \"Xu hướng “trí tuệ hóa” tăng nhanh\" (và trung lưu hóa), từ nội dung này, ta suy ra được là \"Đáp án A\" (dù trong đề có lỗi lặp từ \"trí thức hóa\").",
	},
	{
		question: "Chọn phương án đúng nhất: Theo quan điểm của chủ nghĩa Mác - Lênin, động lực của cách mạng xã hội chủ nghĩa là:",
		answers: [
			"Giai cấp nông dân và giai cấp tư sản",
			"Giai cấp công nhân và giai cấp tư sản",
			"Giai cấp công nhân và giai cấp địa chủ",
			"Giai cấp công nhân và giai cấp nông dân",
		],
		correct: 3,
		explanation: "Dựa trên trang số 70 của chương 5 của tài liệu, chỉ ra rằng \"liên minh với 'người bạn đồng minh tự nhiên' của mình là giai cấp nông dân\", từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Chỉ ra luận điểm không chính xác?",
		answers: [
			"Quyền bình đẳng dân tộc là cơ sở cho quyền tự quyết dân tộc",
			"Quyền tự quyết dân tộc là ảo tưởng đối với các dân tộc kém phát triển",
			"Quyền bình đẳng và quyền tự quyết dân tộc không tự nhiên mà có được",
			"Quyền bình đẳng và quyền tự quyết dân tộc đi liền với nhau",
		],
		correct: 1,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, đã chỉ ra rằng: Quyền tự quyết là quyền cơ bản của \"các dân tộc tự quyết định lấy vận mệnh của dân tộc mình\". Việc cho rằng nó là \"ảo tưởng\" đối với dân tộc kém phát triển là đi ngược với lý luận cơ bản. Từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Yếu tố nào quyết định đến thực hiện quyền bình đẳng dân tộc?",
		answers: [
			"Xóa bỏ tình trạng chênh lệch trong sự phát triển kinh tế, văn hóa của các dân tộc",
			"Xóa bỏ tình trạng giai cấp này áp bức giai cấp khác, trên cơ sở xóa bỏ chế độ tư hữu",
			"Các nhà nước dân tộc có chủ trương, chính sách đúng đắn trong giải quyết quan hệ dân tộc",
			"Các đảng chính trị có đường lối đúng đắn định hướng quan hệ dân tộc",
		],
		correct: 1,
		explanation: "Dựa trên phần Giải thích cuối tài liệu Trắc nghiệm, chỉ ra rằng \"Trong tuyên ngôn, Mác đã chỉ ra rằng, để thực hiện quyền bình đẳng dân tộc hãy xóa bỏ nạn người áp bức bóc lột người... ta phải xóa bỏ chế độ chiếm hữu tư nhân về tư liệu sản xuất\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Chỉ ra luận điểm không chính xác?",
		answers: [
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó là giải pháp hữu hiệu để thực hiện quyền bình đẳng và quyền tự quyết dân tộc",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó là hạt nhân đoàn kết các lực lượng cách mạng trong đấu tranh chống áp bức, bóc lột",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó thể hiện rõ lập trường của giai cấp công nhân trong giải quyết quan hệ dân tộc",
			"“Liên hiệp giai cấp công nhân các dân tộc” là nội dung quan trọng nhất trong Cương lĩnh dân tộc của chủ nghĩa Mác - Lênin, bởi nó thể hiện rõ xu thế toàn cầu hóa và khu vực hóa trong vấn đề dân tộc",
		],
		correct: 3,
		explanation: "Dựa trên trang số 87 của chương 6 của tài liệu, đã chỉ ra rằng: Liên hiệp công nhân các dân tộc nhằm đoàn kết đấu tranh và bảo vệ độc lập, tiến bộ xã hội, không phải chỉ vì xu thế toàn cầu hóa hay khu vực hóa. Từ nội dung này, ta suy ra được là \"Đáp án D\".",
	},
	{
		question: "Theo Chủ tịch Hồ Chí Minh, con đường để đấu tranh cho độc lập, tự do, chủ quyền của dân tộc Việt Nam là gì?",
		answers: [
			"Cách mạng phong kiến",
			"Cách mạng tư sản",
			"Cách mạng vô sản",
			"Cách mạng không ngừng",
		],
		correct: 2,
		explanation: "Dựa trên kiến thức cơ bản xuyên suốt và trang số 16 của chương 1 của tài liệu, đã chỉ ra rằng: Độc lập dân tộc phải gắn liền với chủ nghĩa xã hội (chỉ có con đường cách mạng vô sản mới giải phóng triệt để dân tộc). Từ nội dung này, ta suy ra được là \"Đáp án C\".",
	},
	{
		question: "Tôn giáo là gì?",
		answers: [
			"Tôn giáo là niềm tin của con người tồn tại với hệ thống quan niệm và hoạt động bao gồm đối tượng tôn thờ, giáo lý, giáo luật, lễ nghi và tổ chức",
			"Tôn giáo là niềm tin của con người được khái quát thành triết lý luận khoa học và cách mạng, thể hiện lập trường chính trị của giai cấp công nhân và nhân dân lao động trong đấu tranh giải cấp",
			"Tôn giáo là một tổ chức chính trị - xã hội đặc biệt, ra đời nhằm thực hiện vai trò thống trị chính trị của một giai cấp nhất định trong xã hội",
			"Tôn giáo là một tổ chức xã hội, là đại diện cho quần chúng nhân dân lao động trong công xã nguyên thủy , là tổ chức tiền thân của nhà nước trong xã hội có sự phân chia giai cấp.",
		],
		correct: 0,
		explanation: "Dựa trên trang số 90 của chương 6 của tài liệu, chỉ ra rằng \"Tôn giáo là một thực thể xã hội... có niềm tin sâu sắc vào đấng siêu nhiên... có hệ thống giáo thuyết (giáo lý, giáo luật, lễ nghi)... có hệ thống cơ sở thờ tự, có tổ chức nhân sự\", từ nội dung này, ta suy ra được là \"Đáp án A\".",
	},
	{
		question: "Yếu tố quan trọng nhất làm cho các tôn giáo tồn tại lâu dài là gì?",
		answers: [
			"Ý thức phản kháng của nhân dân đối với bất công xã hội",
			"Niềm tin vào sự tồn tại của các đấng siêu nhiên thần thánh",
			"Khát vọng được giải thoát",
			"Niềm tin vào thế giới hiện thực",
		],
		correct: 1,
		explanation: "Dựa trên trang số 90 của chương 6 của tài liệu, chỉ ra rằng tôn giáo có cốt lõi là \"có niềm tin sâu sắc vào đấng siêu nhiên, đấng tối cao, thần linh để tôn thờ (niềm tin tôn giáo)\", từ nội dung này, ta suy ra được là \"Đáp án B\".",
	},
	{
		question: "Một trong những đóng góp của V.I. Lênin đối với chủ nghĩa xã hội khoa học là gì?",
		answers: [
			"Xây dựng lý luận về đảng kiểu mới của giai cấp công nhân.",
			"Xây dựng lý luận về đảng kiểu mới của giai cấp nông dân.",
			"Xây dựng lý luận về đảng của nhiều giai cấp, tầng lớp trong xã hội.",
			"Xây dựng lý luận về đảng của các dân tộc thuộc địa và phụ thuộc",
		],
		correct: 0,
		explanation: "Dựa trên trang số 11 của chương 1 của tài liệu, chỉ ra rằng \"V.I.Lênin đã xây dựng lý luận về đảng cách mạng kiểu mới của giai cấp công nhân\", từ nội dung này, ta suy ra được là \"Đáp án a\".",
	},
];